### ISSUE TITLE
The coverage and pipeline badges are not appearing on PyPI

### ISSUE THREAD

**Issue by mianasbat** [lemurheavy/coveralls-public#1375] opened 2019-11-15 14:44 UTC
We have few libraries on PyPI server. Their code for general setup and interface is the same. In a couple of repos [scikit-surgercore](https://pypi.org/project/scikit-surgerycore/) and [scikit-surgeryutils](https://pypi.org/project/scikit-surgeryutils/) the badges of pipeline and coverage are not visible whereas in the other repo [scikit-surgerydavinci](https://pypi.org/project/scikit-surgerydavinci/) all the badges are shown. It is strange because the links are working fine but only the badge is not appearing.

I checked the setup.cfg in projects which is reading description from README.rst. The code part for badges is same for both working and non working repos. I checked the gitlab-server to search for .svg images but couldnt find them.

My questions is why badges are not appearing. How PyPI get the badges. Any help on how to fix them? The fix should not be very difficult because the links are working fine.

**Comment by afinetooth** [comment] 2020-04-06 21:41
@mianasbat I see the badges are appearing on the first two repos mentioned above.

I'll take it this means the issue is resolved and will close it for now. 

Just reply if you need follow-up.

**Closed by afinetooth** 2020-04-06 21:41 UTC
