### ISSUE TITLE
Github Actions: PR comment with coverage not being updated

### ISSUE THREAD

**Issue by AlCalzone** [lemurheavy/coveralls-public#1370] opened 2019-10-29 09:48 UTC
Ever since I switched to Github Actions I only get one comment in PRs with the first coverage percentage, but that comment is not updated for the following commits.

https://github.com/AlCalzone/node-zwave-js/pull/369
![grafik](https://user-images.githubusercontent.com/17641229/67756029-8ef4d280-fa39-11e9-97d9-b0382bb06681.png)
This is what the coveralls website has to say:
https://coveralls.io/github/AlCalzone/node-zwave-js?branch=endpoint-interview
![grafik](https://user-images.githubusercontent.com/17641229/67756063-a0d67580-fa39-11e9-8896-ecb4baf262ef.png)

**Comment by AlCalzone** [comment] 2019-10-29 20:15
Here's another example

![grafik](https://user-images.githubusercontent.com/17641229/67805385-3c470500-fa91-11e9-9125-f2f046cac503.png)

**Comment by merlinnot** [comment] 2019-10-30 17:37
In my case comments are not being added at all. Did you find any solution to this problem?

**Comment by merlinnot** [comment] 2019-10-30 17:55
Thanks! As it apparently is a different bug, I opened a separate issue.

**Comment by thenineteen** [comment] 2020-09-05 03:50
There are a lot of these coverage badge discrepancy issues. Especially after deleting a build in coveralls.

**Comment by afinetooth** [comment] 2020-09-17 23:53
@AlCalzone @merlinnot @thenineteen apologies for the delayed response, but as the original post here goes back to Oct 2019 and now pertains to a number of subjects, I'd like to close this issue and ask that, if you're still having issues similar to the above, please open a new issue pertaining to each. 

We've addressed potential root causes for a number of these issues in the past 5-6 months (not receiving PR comments, PR comments being delivered late, not receiving more than one PR comment for the same PR, discrepancies in badge coverage, etc). At this point, to effectively address a specific issue we'd need a recent example.

@thenineteen, since your comment is more recent, feel free to email us at support@coveralls.io referencing this issue. If you can provide a link to at least one affected coveralls build in the email, we can examine a set of potential root causes and hopefully reply quickly with some insight or a fix.

Thanks.

**Closed by afinetooth** 2020-09-17 23:53 UTC
Labels: coverage-discrepancies, github-action, potential-bug, repo-changes

**Comment by thenineteen** [comment] 2020-09-18 00:39
Thanks

My issues have actually been fixed

Just in case it may help others, half of my problems were due to cache issues which were solved simply by pressing `ctrl+F5` on my main github repository site, forcing the badge to be updated
