### ISSUE TITLE
Feature request: Configure Failure state. Coverage change and total coverage.

### ISSUE THREAD

**Issue by jcoyne** [lemurheavy/coveralls-public#609] opened 2015-08-27 13:17 UTC
It's annoying that builds are marked as failure when coverage decreases by a minimal amount (usually due to removing covered code) even though the total coverage is pretty good.  If we be awesome if you could configure failure as either "coverage decreased by > x% OR total coverage is below y%"  Perhaps these variables could go into .coveralls.yml

In my own personal case, I'd like to configure the build such that this was passing:
<img width="459" alt="screen shot 2015-08-27 at 8 11 37 am" src="https://cloud.githubusercontent.com/assets/92044/9521359/0db8158a-4c94-11e5-9a6f-8c6d70f0650e.png">

**Comment by laughinghan** [comment] 2016-06-08 02:35
I think this is a duplicate of #565?

> usually due to removing covered code

Exactly!!! I rant about this here: https://github.com/lemurheavy/coveralls-public/issues/565#issuecomment-212583659

**Closed** 2020-04-10 13:33 UTC
Labels: legacy, marked-for-closure
