### ISSUE TITLE
`/builds` API Endpoint returning incomplete data

### ISSUE THREAD

**Issue by ErnestFistozz** [lemurheavy/coveralls-public#1724] opened 2023-07-20 19:43 UTC
Hi,

I am getting a rather interesting yet strange response from the `builds` endpoint. The total number of builds is said to be `8` but the builds array consist of `5`. According to the documentation, the default page size is `10`, so the 8 is still within the boundary. Otherwise I would have expected it to have multiple pages.

See below image and the the `/GET` request URL
API: [BUILD](https://coveralls.io/github/ErnestFistozz/codecov-coveralls.json?page=1)

![build_endpoint](https://github.com/lemurheavy/coveralls-public/assets/20247618/11d59b80-1716-41bb-86b2-e692a977db83)

**Comment by afinetooth** [comment] 2023-07-21 00:31
Hi @ErnestFistozz. Yes, the issue is probably that our page set is `5`, which is atypical. But if you change the page number on that URL, you'll see the remaining 3 builds in your collection of builds:
https://coveralls.io/github/ErnestFistozz/codecov-coveralls.json?page=2

<img width="763" alt="Screenshot 2023-07-20 at 5 30 06 PM" src="https://github.com/lemurheavy/coveralls-public/assets/918667/9c92fb95-ac45-45ff-a30e-7b44924354dc">

I have added a card to our backlog requesting the consideration of changing the page set to `10` to match the common default.

I will close this for now, but please re-open if necessary, or just re-comment and I'll re-open the issue.

**Closed as completed by afinetooth** 2023-07-21 00:31 UTC
Labels: api

**Comment by ErnestFistozz** [comment] 2023-07-21 09:19
Hi @afinetooth 

Thanks for getting back to me. Given that the default set size is `5`, shouldn't the pages then be `2` instead of `1` (referring my to my earlier screenshot). 
From my screenshot, the response says:

```json
page: 1,
pages: 1,
builds: [
...
]
```
which one can assume it to be `1/1` where its `current_page/total_pages`. I would have expected something like:
```json
page: 1,
pages: 2,
builds: [
...
]
```
To show that there are a total of `two` pages (each representing a max of `5` builds). Do you have a query parameter I can use as part of the endpoint to limit the size. I have tried `page_size, size, limit` and `page_limit`, they all still return the same `1/1` response. Essentially, I would like to iterate through all my builds and therefore, it would be nice to know the `total number of pages` before hand. Thanks again.

**Comment by afinetooth** [comment] 2023-07-27 00:28
@ErnestFistozz you are so right, my bad for not catching that.

I actually see that our view code is expecting a page set of `10`, so there is an issue with code elsewhere. I've submitted this for a fix and will update you here.

**Comment by iurev** [comment] 2023-08-22 15:44
Hi @afinetooth, can you check two APIs below? I added new param `per_page` just in case it's needed, it's 10 by default.
https://coveralls.io/github/ErnestFistozz/codecov-coveralls.json?page=1
https://coveralls.io/github/ErnestFistozz/codecov-coveralls.json?page=1&per_page=3

**Comment by afinetooth** [comment] 2023-08-22 15:49
@iurev this looks great, thank you! 🙏 

@ErnestFistozz, will you please have a look at our changes in the context of your repo and confirm they work as expected / desired? Thanks. 🙏

**Comment by ErnestFistozz** [comment] 2023-08-23 10:31
@afinetooth and @iurev 

This is great. Thanks you.
