### ISSUE TITLE
Highlight individual lines for which coverage changed

### ISSUE THREAD

**Issue by mjarvis** [lemurheavy/coveralls-public#459] opened 2015-02-12 20:15 UTC
When a coverage report is generated, it tells me which files had coverage changed, along with the count of what changed, IE +2 or -2 lines, but when I click through to the individual file, I cannot see a way to determine which lines changed.

I'd like to know which lines coverage was added to, compared to the last coverage report. instead all I can see is overall which lines in the file were hit or missed.

For example, if a user adds a line of code, and does not test it, I would like to see that specific line highlighted, or if a user adds test coverage, I would like to see which lines they added coverage for.

Right now I can only see which files they added or removed coverage from, not what they did in that file.

**Comment by tofu-rocketry** [comment] 2015-02-18 11:46
:+1:

**Comment by abraham-chan** [comment] 2015-10-07 23:04
:+1:

**Comment by ScottFreeCode** [comment] 2017-07-09 05:11
Looks like this is a duplicate of #359

Functions and branches would be nice too; Coveralls added branch coverage summaries not too long ago.

**Comment by thoni56** [comment] 2020-02-07 12:29
Yeah, this would really help. Sometimes the coverage for some module goes down then up again. I don't know if this is depending on how I run my tests, but it would be extremely helpful if you could see the exact lines which had different coverage between two builds.

Also when you are stepwise upping your coverage it would be good to quickly see that the targeted lines where actually hit. So a button that just filtered out those lines, would make it very easy to ensure that your new test actually hit the correct lines. Now you have to make a note of which lines you are targeting and then navigate to them through the file structure.

**Closed** 2021-05-17 02:32 UTC
Labels: legacy, marked-for-closure
