### ISSUE TITLE
Unexpectedly getting 422 {"message":"Couldn't find a repository matching this job.","error":true} on private repository that previously worked

### ISSUE THREAD

**Issue by Niceplace** [lemurheavy/coveralls-public#1570] opened 2021-08-17 16:15 UTC
@afinetooth Apologies for tagging, this is a bit of a blocker for us :( We will merge builds anyways using local coverage information but our pipeline requires to have specific coverage thresholds as part of our quality process. Any pointers would be greatly appreciated. I already send an email to support yesterday but I continued to debug after this.

**Context:**

Using Github action with NodeJS project for a private repository (Github Enterprise) & debug activated.
Fails to publish using self-hosted and/or Github provided runners.

Everything seemed to work fine until August 13 for this specific repository, I can see all coverage info in coveralls.
All existing & new PRs fail to publish to coveralls with the 422 error. 

The repository is: https://coveralls.io/github/pleo-io/qe-metrics-collector

Here is my workflow configuration:

```
      - name: Coveralls
        uses: coverallsapp/github-action@1.1.3
        env:
          NODE_COVERALLS_DEBUG: 1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: "Unit tests"
```

Here is some potentially relevant information I was able to pull off of the debug logs (self-hosted runner):

```
 [debug] "2021-08-17T16:00:19.339Z"  'user options undefined'
[debug] "2021-08-17T16:00:19.340Z"  'No valid .coveralls.yml file found'
[debug] "2021-08-17T16:00:19.353Z"  {
  service_pull_request: '356',
  run_at: '2021-08-17T16:00:19.340Z',
  service_job_id: '1139954156',
  repo_token: '***',
  service_name: 'github',
  flag_name: 'Unit tests',
  git: {
    head: {
      id: '9034fd3ecde412339bef3ab14189faf6c1eba710',
      committer_name: 'GitHub',
      committer_email: 'noreply@github.com',
      message: 'Merge b2649bd4a449623c2a949ae6909c8a4cdfd7c010 into ae338179156f89b0207fff7ddc87fd764ea5c4b5',
      author_name: 'Simon',
      author_email: 'Niceplace@users.noreply.github.com'
    },
    branch: 'refs/pull/356/merge',
    remotes: [ [Object] ]
  }
}
[debug] "2021-08-17T16:00:19.355Z"  'in: ' ''
```

Here is some potentially relevant information I was able to pull off of the debug logs (github hosted runner: `ubuntu-latest`):

```
 [debug] "2021-08-17T16:11:05.687Z"  'user options undefined'
[debug] "2021-08-17T16:11:05.688Z"  'No valid .coveralls.yml file found'
[debug] "2021-08-17T16:11:05.712Z"  {
  service_pull_request: '356',
  run_at: '2021-08-17T16:11:05.688Z',
  service_job_id: '1139991767',
  repo_token: '***',
  service_name: 'github',
  flag_name: 'Unit tests',
  git: {
    head: {
      id: 'd0be6fa1f59e831b6b48c0a3bcfe8a73fccac41e',
      committer_name: 'GitHub',
      committer_email: 'noreply@github.com',
      message: 'Merge f59aa74e653ffaf03367a4d841d95cd8a688a884 into ae338179156f89b0207fff7ddc87fd764ea5c4b5',
      author_name: 'Simon',
      author_email: 'Niceplace@users.noreply.github.com'
    },
    branch: 'refs/pull/356/merge',
    remotes: [ [Object] ]
  }
}
[debug] "2021-08-17T16:11:05.713Z"  'in: ' ''
```

Cheers ! :)

**Comment by afinetooth** [comment] 2021-08-17 19:46
HI @Niceplace. 

Sent you a reply via email with some insight from additional debug output I found in your build log. 

I think you may be running two integrations in parallel, which results in posting to the Coveralls API twice, where the first post from the first integration is looking to match `COVERALLS_REPO_TOKEN` but not finding it because the second integration, Coveralls Github Action, sets that to `secrets.GIHUB_TOKEN`. I think the solution is to remove [this line](https://github.com/connectdotz/vscode-jest/actions/runs/1136993291/workflow#L93) from your workflow file.

I'll wait to get your response to verify the fix before publishing more details.

**Comment by Niceplace** [comment] 2021-08-17 22:05
I'm a bit confused :/ 

The line that you linked (see screenshot below) has no match in our workflow file, we are using the Coveralls Github action from within the workflow and not a js executable in our project.

<img width="714" alt="image" src="https://user-images.githubusercontent.com/8710189/129805113-bbeb18f7-1b81-4be8-a708-925bdd7a21e8.png">

The usage of the env variable `COVERALLS_REPO_TOKEN` with the coveralls action was a temporary test to see if that would somehow recreate the link between my build and coveralls. Before that, I had multiple runs with only:

```
      - name: Coveralls
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
```

And that still failed with the same 422. Removing the reference to `COVERALLS_REPO_TOKEN` does not seem to fix my problem. I think I might need to delete the repository from coveralls and start from scratch 

Last note: 

> Sent you a reply via email with some insight from additional debug output I found in your build log.

Unfortunately, it seems that I did not get any additional email after sending the debug log + workflow info. I apologize for dragging you across two different communication channels for this. What would you prefer, here or by email?

Thank you for all your assistance so far, cheers ! :)

**Comment by afinetooth** [comment] 2021-08-18 01:57
@Niceplace I'm sorry, I don't know where I picked that up. I had a million tabs open and might have clicked on the wrong one? Let me review your workflow file and verbose build log from email and get back to you there (and here).

**Comment by afinetooth** [comment] 2021-09-07 23:37
For those following along here, the root cause is still inconclusive and the issue is not yet fully resolved.

From the Coveralls side, our direct requests to the repo at Github (for testing) fail due to IP access restrictions, so we would normally cite this as the cause.

However, we helped the customer, previously, to allow our set of IP addresses and several other repos with the same setup are not failing.

I will post an update here if there's a resolution.

**Comment by afinetooth** [comment] 2021-09-08 20:59
Update:
For this particular situation, devops team for the customer traced the issue back to token-level permissions for the given user or app.

Not likely to apply generally.

For those still searching for a solution to "422 Couldn't find a repository matching this job." we recommend [searching issues with this filter](https://github.com/lemurheavy/coveralls-public/issues?q=is%3Aissue+is%3Aopen+Couldn%27t+find+a+repository+matching+this+job.).

Closing for now.

**Closed as completed by afinetooth** 2021-09-08 20:59 UTC
Labels: github-action, 4xx-error, error-messages
