### ISSUE TITLE
Bump coverallsapp/github-action from 1.2.4 to 2.0.0  fails with "Nothing to report, exit code 1"

### ISSUE THREAD

**Issue by lukka** [lemurheavy/coveralls-public#1702] opened 2023-03-20 20:29 UTC
[upgrading coverallapp/github-action from 1.2.4 to 2.0](https://github.com/lukka/run-vcpkg/pull/185) looks like reporting unexpected failures, e.g.:

https://github.com/lukka/run-vcpkg/actions/runs/4472335222/jobs/7858368993?pr=185

where the step fails and the last part of the output is:

>  
>   🚨 Nothing to report
>   Error: Process completed with exit code 1.
> 

Any hint on what is the fix to complete the migration to `v2.0`?

**Comment by afinetooth** [comment] 2023-03-21 14:32
@lukka checking internally, will follow up.

**Comment by mrexox** [comment] 2023-03-21 16:10
@lukka, you can notice that jobs for **ubuntu** and **windows** runner never reported coverage at all. In v2 version of github action we've added a check - exit with an error if there is nothing to report.

I think the issue is in the difference of LCOV content:
- For [macOS runner the path is root-relative](https://github.com/mrexox/run-vcpkg/actions/runs/4480525996/jobs/7876790019#step:6:11)
- For [ubuntu runner the path is relative to subdir (I guess it's `__tests__/theAssets/vcpkg_project`)](https://github.com/mrexox/run-vcpkg/actions/runs/4480525996/jobs/7876789745#step:6:11)
- The same pattern for [windows runner](https://github.com/mrexox/run-vcpkg/actions/runs/4480525996/jobs/7876790258#step:6:11)

I'm not sure why there's such a difference between macOS runner and others. Maybe it is something internal to coverage tools used in your project.

However I can recommend a [workaround](https://github.com/mrexox/run-vcpkg/pull/1). This is not the best solution, but at least it works. If you have time and will to find out why paths are different in LCOV file, it would be great. But if not - you can either use a workaround or just skip reporting coverage for runners other than `macOS`.

**Comment by lukka** [comment] 2023-03-22 05:48
@afinetooth @mrexox thanks a lot for the detailed explanation! The PR you created worked fine, just merged it, and I really appreciated your help and the coveralls service!
Indeed the problem is still a mystery, I may find out sooner or later.

**Comment by afinetooth** [comment] 2023-03-27 19:31
I will close this, but feel free to reopen if you hit any other issues.

**Closed as completed by afinetooth** 2023-03-27 19:31 UTC
