### ISSUE TITLE
"Couldn't find a repository matching this job." status 422 for public repo

### ISSUE THREAD

**Issue by kortschak** [lemurheavy/coveralls-public#1264] opened 2019-02-17 01:31 UTC
Today I have seen a series of Coveralls build failures for a public repository with CI builds being done by Travis-CI. This appears to be a long standing recurrent issue #715, #408, #984 etc.

Travis-CI [log for build](https://travis-ci.org/gonum/exp/jobs/494373885).
```
Bad response status from coveralls: 422
{"message":"Couldn't find a repository matching this job.","error":true}
```

Though [other builds](https://travis-ci.org/gonum/exp/builds/494373883) for the same PR succeed.

**Comment by kortschak** [comment] 2019-02-17 01:35
Resyncing the repo at coveralls did not fix this.

**Comment by jacktuck** [comment] 2019-02-17 14:35
I'm intermittently getting the same error

```/home/travis/build/jacktuck/unfurl/node_modules/coveralls/bin/coveralls.js:18
        throw err;
        ^
Bad response: 422 {"message":"Couldn't find a repository matching this job.","error":true}```

https://travis-ci.org/jacktuck/unfurl/jobs/494500772

**Comment by chrisgleissner** [comment] 2019-02-17 18:46
Same here. Had to detach a few builds from coveralls for now to bypass the issue which breaks them.

**Comment by chrvadala** [comment] 2019-02-18 13:37
I have the same issue here https://travis-ci.org/chrvadala/mqtt-dispatcher.

**Comment by jeromesimeon** [comment] 2019-02-18 20:30
Having the same issue, the last few days. On https://travis-ci.org/accordproject/cicero Restarting the build often works.

**Comment by kortschak** [comment] 2019-02-18 20:34
@jeromesimeon restarting never works for me with this.

**Comment by jeromesimeon** [comment] 2019-02-18 20:37
@kortshack Thanks. It might be a different issue then, but the symptoms are the same and it started a few days ago. Definitely intermittent for us.

**Comment by kortschak** [comment] 2019-02-18 20:59
Yeah, I don't doubt it's the same cause. I don't understand how the differences arise. My approach for now is to just make the coveralls failure a warning event rather than an error event.

**Comment by zmckinnon** [comment] 2019-02-19 02:11
Getting similar here: https://travis-ci.org/zmckinnon/dice-tower
```
Failed to upload to coveralls
UnprocessableEntity - Couldn't find a repository matching this job.
```

**Comment by srepollock** [comment] 2019-02-19 06:45
I've just started running into the same problem on my own builds. I've added a `COVERALLS_REPO_TOKEN` with my API key as an environment variable with Travis to keep it secure, yet I'm still getting the same issue. Is there another token name that Coveralls looks for? I'm trying not to put the token in plain text and commit it...

Also, is this a duplicate of #984? Has this been going on since June?

**Comment by kortschak** [comment] 2019-02-19 09:10
The situation has degenerated. I am now seeing 100% failure in this mode.

**Comment by kortschak** [comment] 2019-02-19 09:18
@anjin @nickmerwin Is anyone home?

**Comment by kanekotic** [comment] 2019-02-19 10:05
there seems to be a general issue, it happens in all my repos, and also other people are having the same issue. 
https://github.com/nickmerwin/node-coveralls/issues/166

**Comment by ericmorand** [comment] 2019-02-19 10:06
@kortschak, Same here, 100% failures now.

**Comment by kortschak** [comment] 2019-02-19 10:11
We are now investigating moving to codecov.

**Comment by sb10** [comment] 2019-02-19 10:49
Also getting failures for my public repo starting today. Yesterday was fine.

**Comment by agbeltran** [comment] 2019-02-19 14:39
We are having a similar (same?) issue here: https://travis-ci.org/FAIRsharing/jsonldschema/jobs/495412051

```Submitting coverage to coveralls.io...
Coverage submitted!
Couldn't find a repository matching this job.
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/bin/coveralls", line 10, in <module>
    sys.exit(main())
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/coveralls/cli.py", line 80, in main
    log.info(result['url'])
KeyError: 'url'```

It worked ok till recently.

cc @terazus

**Comment by qcoumes** [comment] 2019-02-19 16:53
Also gettings 100% failure here.

**Comment by jeromesimeon** [comment] 2019-02-19 16:56
Same.

**Comment by alex-w** [comment] 2019-02-19 18:10
Also gettings 100% failure

**Comment by mischah** [comment] 2019-02-19 18:40
Same here.

You can fix your Travis builds be moving coveralls to the `after_success` lifecycle hook like this:
https://github.com/micromata/generator-baumeister/commit/acf06820f03cc09635b08c6e98888f67853fd2ec

You won’t get coverage updates as long as coveralls is broken, but your builds won’t fail because the exit code of `after_success`, `after_failure`, `after_script`, `after_deploy` and subsequent stages do not affect the build result.

See [Travis docs](https://docs.travis-ci.com/user/job-lifecycle/#breaking-the-build).

**Comment by nickmerwin** [comment] 2019-02-19 19:20
Hi all, we've identified this as an intermittent Travis API failure and are working on a solution.

**Comment by srepollock** [comment] 2019-02-19 19:39
A few notes everyone: instead of spamming "same" let's make use of some sweet emojis to show support! We all get these emails and it just ends up spamming the inbox. We can always reference the issue in our own project's issues that don't spam everyone but still keeps the track record :+1:. Just a good habit to carry into other projects as well and start early!

Aside, as you can see in the thread here, I switched to to [Codecov](https://codecov.io/). I've used it before, and was using it before I came to Coveralls. Codecov looks like it has a lot more support, and some big names in the industry use it as well. I also really enjoy the graphs it outputs and documentation. It's also Open Source, unlike Coveralls here (whose repository is just a link to the issues?).

Hope you all can resolve your issue, because it appears this has been going on quite some time with no response...

**Comment by nickmerwin** [comment] 2019-02-19 20:02
Hi everyone, turned out we had our webserver IPs accidentally blacklisted by Travis, so we couldn't query their API to get job info as coverage data was posted.

Apologies for the gap in service here! We're adding failsafes to warn us early about this in the future.

**Closed by nickmerwin** 2019-02-19 20:02 UTC

**Comment by Ismaestro** [comment] 2019-06-18 20:44
This is happening right now again. @nickmerwin that is cool, but maybe we should think in a more proper way to avoid this problem in the future...

**Comment by victorkarangwa4** [comment] 2020-01-10 14:52
Hi guys,
I solved this issue by updating COVERALLS_REPO_TOKEN in .circleci/config.yml.
You can check if COVERALLS_REPO_TOKEN you are having is the same as the one generated by coveralls.io.

**Comment by estroz** [comment] 2020-05-22 00:13
This seems to still be an issue on travis.

**Comment by bkielbasa** [comment] 2020-05-22 19:42
same here - it stoped working

**Comment by afinetooth** [comment] 2020-05-22 22:17
Per https://github.com/lemurheavy/coveralls-public/issues/632#issuecomment-632887974,
we think the recent occurrence is a GitHub issue: https://www.githubstatus.com/

**Comment by ndelvalle** [comment] 2020-05-29 13:29
I also have this issue today:
```
Bad response: 422 {"message":"service_job_id (340775507) must be unique for Travis Jobs not supplying a Coveralls Repo Token","error":true}
```

**Comment by Lucasjuv** [comment] 2020-08-19 18:59
Have this issue today:
`{"message":"service_job_id (375382350) must be unique for Travis Jobs not supplying a Coveralls Repo Token","error":true}
`

**Comment by afinetooth** [comment] 2020-08-21 18:41
Hi @Lucasjuv per [my comment here](https://github.com/lemurheavy/coveralls-public/issues/1477#issuecomment-678434241), if you want to email us a support@coveralls.io with the link to your coveralls project, we'll look into it further for you.

**Comment by binarymist** [comment] 2022-05-08 05:51
This still seems to be an issue

**Comment by afinetooth** [comment] 2022-05-09 23:43
Hi @binarymist. There are different causes for these different 422 results, so it would be ideal to cover them in separate issues dedicated to each root cause.

In your case, is this happening after you've migrated from Travis CI to Github Actions?

If not, what is your use case? And what is the message that comes along with your 422 status code?

Thanks.
