### ISSUE TITLE
Coveralls reporting a decrease overall (using parallel), even though nothing changed

### ISSUE THREAD

**Issue by auto-differentiation-dev** [lemurheavy/coveralls-public#1653] opened 2022-07-26 06:39 UTC
Hi,

We're struggling to understand why the coverage in a PR decreased in the overall coveralls reporting, even though the detailed numbers below suggest otherwise (and none of the test code was changed). It seems that it's one of the parallel jobs that is reported, not the overall result. 

Here is a screenshot for reference:

<img width="1110" alt="image" src="https://user-images.githubusercontent.com/107129969/180939874-5a750cf4-99e1-4510-988d-ad7e19f73372.png">

This is the link: https://coveralls.io/builds/51121924
And it corresponds to this PR: https://github.com/xcelerit/XAD/pull/13

Any ideas?

**Comment by afinetooth** [comment] 2022-07-26 23:34
Hi @xcelerit-dev. Thanks for reporting your issue.

This is something that's been happening lately, for a handful of repos as far as we know ([example 1](https://github.com/lemurheavy/coveralls-public/issues/1632) | [example 2](https://github.com/lemurheavy/coveralls-public/issues/1631)). Specifically, the behavior is that PRs will show a decrease in coverage that, by the evidence, should not occur. Then, when the jobs in the PR build are re-run, the PR's coverage % corrects itself.

Note these side-by-side comparisons between your base branch (LEFT) and your PR branch (RIGHT).

First, it shows the decrease you found suspect:
![Screen Shot 2022-07-26 at 4 13 40 PM](https://user-images.githubusercontent.com/918667/181128465-1af18562-c521-4ff1-894b-4e56a1b411c2.png)

It looks suspect to me for the same reasons, and, in addition, while each individual job has the exact same coverage % compared to the base build, the run details tell a different numbers story:

Base:
![Screen Shot 2022-07-26 at 4 21 21 PM](https://user-images.githubusercontent.com/918667/181128624-3d6ded51-aa32-485b-9e7a-e02b5138eb53.png)

PR:
![Screen Shot 2022-07-26 at 4 21 40 PM](https://user-images.githubusercontent.com/918667/181128651-41099d7c-bd40-4d59-aff4-51fdb8092700.png)

A build's coverage % always complies with the numbers in the RUN DETAILS.

After I re-run the jobs in the PR build:
![Screen Shot 2022-07-26 at 4 17 24 PM](https://user-images.githubusercontent.com/918667/181128745-1d79a339-a347-4fb6-8331-2457f5ba8c4e.png)

We now see no change in coverage between base and PR. And the RUN DETAILS align in terms of relevant lines covered (even while hits per line changes a bit but does not affect coverage %).

Unfortunately, we don't know the root cause of this issue. For some users it is consistent, for some occasional. Is it _**occasional**_ or _**persistent**_ for you?

In your case, there is one thing I see wrong that I would like to correct to see if it has an impact (which could fix your builds, or otherwise be helpful in determining the root cause of the shared issue):

Your builds are not sending status updates, and this can sometimes be cause by an expired OAuth token (of your repo owner in this case), which can cause other problems like failed API calls to Github, which could potentially have a role in what's happening with the first run of the PR build.

To fix this I would normally reassign repo ownership to another user of the repo, ideally one with Admin access to the repo. But in your case, I see you are the only user, and that you _have_ Admin access. 

Unless there is another user you're aware of that we can test with, we'll have to find out why status updates aren't reaching Github with the permissions that are attached to your OAuth token.

Do you have any insight into why that may be?

Please give me a few moments to explore further and I'll get back with my own findings.

BTW, to set expectations, if resolving this issue doesn't fix your PR builds (meaning: stop future PR builds from reporting false coverage drops), then you are squarely in the group of repos having this problem with no current known cause. It means I'll have to add you to the ticket with those other projects and update you with any progress from there.

**Comment by afinetooth** [comment] 2022-07-27 00:00
Ok, it turns out I was wrong. You were not the owner of your repo. You were the only _user_ of the repo, but your repo _had_ no owner. I made you the owner and re-ran your builds, and they started sending status updates. (You can check Github to verify status updates on your last three (3) builds.)

Please proceed and let me know, here, if any of your next PR builds also show an incorrect decrease in coverage %.

I'm not sure if this change will resolve that issue, but it would be great to know. The other cases, BTW, did not have this issue AFAIK.

**Comment by auto-differentiation-dev** [comment] 2022-07-27 10:10
Thank you for all your investigations - that was helpful. However, we see this happening again for the next PR: 
- https://github.com/xcelerit/XAD/pull/15
- https://coveralls.io/builds/51193847

While we could modify thresholds etc to make sure we can keep working (get checks to pass), that's not a solution. The coverage badge will also keep fluctuating for no reason. 

What do you suggest we can do to get around this? Keep triggering new builds in the PRs until we get a consistent result?

**Comment by auto-differentiation-dev** [comment] 2022-07-27 12:18
We tried a rebuild of the whole workflow, but this only adds more jobs to the same coveralls build number and doesn't change the overall coverage percentage.

**Comment by afinetooth** [comment] 2022-07-28 23:56
Yes, I'm sorry to say, you're squarely in the pattern of this known but currently unresolved issue.

Just to make sure, using this PR build as a test:
https://coveralls.io/builds/51200176

![Screen Shot 2022-07-28 at 4 52 31 PM](https://user-images.githubusercontent.com/918667/181655947-409149d7-56d2-4ea1-b9f0-7a52cf98c4fc.png)

I re-ran the jobs in the build and see the coverage % change / correct itself:

![Screen Shot 2022-07-28 at 4 52 57 PM](https://user-images.githubusercontent.com/918667/181656009-a30fe9d9-7e15-4a69-b725-dd3c2128b6e0.png)

Sorry. I'll add you to the issue and share any updates.

**Comment by OndraM** [comment] 2022-09-08 13:05
Hi, we are affected as well:
- [This build](https://coveralls.io/builds/52303937) (which is `push` event build) reports in the header "First build on feature/test-page-constants at 64.607%" and also in the "source files" part it reports consistent `64.61 lib/` coverage.
- However [this build](https://coveralls.io/builds/52304289), which is PR build for the same branch and the same code, reports "coverage decreased (-29.0003%) to 35.606%". In the "source files" part here is still `64.61 lib/` coverage with "no change" reported. So these two numbers are for some reason inconsistent.

We are getting this behavior for all pull request builds not. However, push builds reports the coverage OK.

**Comment by afinetooth** [comment] 2022-09-08 22:50
Hi, @OndraM.

Thanks for the report. It sounds like we'll need to add you to this issue. Which I'll do as soon as I'm able to verify and make sure there isn't another underlying cause in your case.

We're experiencing an extremely high volume of support requests this week and are working through a backlog. We'll respond to your issue as soon as we possibly can.

Thanks.

**Comment by Torgen** [comment] 2022-09-17 18:22
If more data points helps, I think https://github.com/Torgen/codex-blackboard also has this issue. The coveralls site shows the aggregated coverage, but the comment and check result show the lowest single sub-result of the parallel runs.

**Comment by afinetooth** [comment] 2022-09-19 21:34
@xcelerit-dev @OndraM @Torgen 

## Workaround for this issue: the Rerun Build Webhook
While we've not yet identified a fix for this issue, we released a workaround today that should resolve it for you: the **Rerun Build Webhook**.

Since the nature of the issue appears to be that, for _some repos with parallel builds_: 

1. The coverage % of **pull_request** builds is calculated incorrectly (on the first build), but
2. Re-running the build (recalculating coverage) corrects the coverage %.

A **Rerun Build Webhook**, similar to the [(Close) Parallel Build Webhook](https://docs.coveralls.io/parallel-build-webhook), fixes the issue by triggering your build to re-calculate itself.

### Instructions
Call this at the end of your CI config, after calling the [(Close) Parallel Build Webhook](https://docs.coveralls.io/parallel-build-webhook).

Call it like this:

```
curl --location --request GET 'https://coveralls.io/rerun_build?repo_token=<YOUR REPO TOKEN>&build_num=<YOUR BUILD NUMBER>'
```

But substitute your `repo_token`, and your `build_num` (the same value you used for `build_num` in your [(Close) Parallel Build Webhook](https://docs.coveralls.io/parallel-build-webhook)).

_Please note a few differences between the Rerun Build Webhook and the (Close) Parallel Build Webhook:_ 

1. _The `/rerun_build` endpoint will accept a `GET` or a `POST`, and_
2. _The only two required URL params are your `repo_token` and the `build_num`, and `build_num` is a regular URL param and not part of a JSON body called "payload" as required by the (Close) Parallel Build Webhook:_

>```
>curl -k https://coveralls.io/webhook?repo_token=<YOUR REPO_TOKEN> -d "payload[build_num]=<YOUR BUILD NUMBER>&payload[status]=done"
>```

**Comment by auto-differentiation-dev** [comment] 2022-09-20 08:13
@afinetooth Thank you for the description. We'd like to test this, but we're wondering how we can get the `build_num` within a GitHub workflow yml file? This is our [ci.yml](https://github.com/xcelerit/XAD/blob/main/.github/workflows/ci.yml), and I guess the workaround would mean inserting the following extra step into the `coverage_finish` job:

```yaml
- name: Rerun coverage workaround
  run: |
    curl --location --request GET 'https://coveralls.io/rerun_build?repo_token=XXXX&build_num=YYYY'
```

The repo token (`XXXX`) is simple to get, but how would we get the `YYYY`? We're using the [coveralls github action](https://github.com/coverallsapp/github-action).

**Comment by auto-differentiation-dev** [comment] 2022-09-20 09:23
We worked out the required change. After placing a secret for the `COVERALLS_REPO_TOKEN`, the following workflow step appears to work fine: https://github.com/xcelerit/XAD/blob/main/.github/workflows/ci.yml#L324-L327

**Comment by afinetooth** [comment] 2022-09-20 14:19
@xcelerit-dev apologies. I forgot that some Coveralls integrations (like the Coveralls GitHub Action) have special features around the (Close) Parallel Build Webhook, such that you don't need to build the request.

You got it right. The `build_num` is `${{ env.GITHUB_RUN_ID }}` for the Coveralls GitHub Action.

This came up right away after I posted the solution [here](https://github.com/lemurheavy/coveralls-public/issues/1631#issuecomment-1251722073) as well, so you can see a longer explanation [there](https://github.com/lemurheavy/coveralls-public/issues/1631#issuecomment-1251722073).

**Comment by fabiode** [comment] 2023-07-11 09:39
@afinetooth Hi, thanks for the proposed workaround. It works sometimes, but it seems also to fetch random results from one of the parallel runs that had an even lower coverage result as a canonic value for the entire build. 

before the workaround we had `±0.3%`, now it can reach `-38.9%` change.

I'm not sure if I did something wrong, but I added the `rerun_build` request after `parallel_build_webhook`

```
- name: Rerun coverage workaround
  run: |
    curl --location --request GET 'https://coveralls.io/rerun_build?repo_token=XXXX&build_num=YYYY'
```

Replacing `XXXX` and `YYYY` by CircleCI env vars. 

I was wondering if anyone encountered this oscillation after the workaround.

**Comment by afinetooth** [comment] 2023-07-11 22:13
@fabiode Can you share the URLs for 2-3 recent builds that this is happening for? I feel like recent changes to our code should make this original issue far less likely to begin with. But I'd also like to verify that we received your rerun webhook, etc. If you repo is private or sensitive, please email us at suport@coveralls.io and mention [this issue](https://github.com/lemurheavy/coveralls-public/issues/1653). I will get it.

**Comment by afinetooth** [comment] 2023-08-10 22:26
@fabiode Got your request to support@coveralls.io and will reply there. Thanks.

**Closed as completed** 2023-09-18 17:07 UTC
Labels: bug, coverage-discrepancies
