### ISSUE TITLE
500 when trying to download an invoice

### ISSUE THREAD

**Issue by joseairosa** [lemurheavy/coveralls-public#1494] opened 2020-10-14 16:22 UTC
Hi there!

When trying to download any of our invoices I'm getting a 500 error.

<img width="1064" alt="image" src="https://user-images.githubusercontent.com/288866/96017312-c5418280-0e41-11eb-9a07-47c2611b35df.png">

Anyone experiencing the same?

**Comment by afinetooth** [comment] 2020-10-19 17:40
Hi @joseairosa, this should be fixed now. Thanks.

**Closed as completed by afinetooth** 2020-10-19 17:40 UTC
Labels: 5xx-error

**Comment by electblake** [comment] 2023-08-31 20:31
Happening again +1

**Comment by afinetooth** [comment] 2023-09-01 01:39
@electblake still now? Can you please share the Coveralls URL to your project? I can't reproduce.

**Update**:
I can provide a workaround if you, or someone on your team, has access to your subscription email. Let me know.

Finally, if you have a subscription you can always email us directly for faster support at support@coveralls.io.
