### ISSUE TITLE
badge in github not updating

### ISSUE THREAD

**Issue by ericblade** [lemurheavy/coveralls-public#1065] opened 2018-01-27 18:36 UTC
... i'm not sure where the source of this problem might lay -- browser? github? coveralls?

when I open my repo ( https://github.com/ericblade/mws-advanced ) I see a coveralls badge showing 63.  My coverage has never been at 63 on it.  When I click the badge, and go to the coveralls page, it shows the badge and coverage stats clearly being 88.  If I load the badge SVG directly into my browser, I see 88.  

Any ideas? I have tried clearing my cache, using different browsers.. it seems that when I source the image from coveralls, via github, it gives the wrong number, and I don't see how that would be.

**Comment by flihp** [comment] 2018-01-29 18:16
I think this is a duplicate of #971. I worked around this by using the badge from badges.io instead of the coveralls default.

**Comment by bytewalls** [comment] 2018-02-21 21:00
We have made some patches to solve some issues we were having with github caching badge resources, please let us know if this is a problem again.

**Closed by bytewalls** 2018-02-21 21:00 UTC

**Comment by thomscode** [comment] 2018-03-21 14:43
I'm seeing this issue as well. [GitHub Repo] shows 0% coverage, while [Coveralls Report] shows 100% coverage and the [embedded badge] URL when viewed in browser also shows 100% coverage. I've cleared browser cache, tried multiple browsers, and updated README file, all with no change.

[GitHub Repo]: https://github.com/pnnl/drupal-installer
[Coveralls Report]: https://coveralls.io/github/pnnl/drupal-installer?branch=master
[embedded badge]: https://coveralls.io/repos/github/pnnl/drupal-installer/badge.svg?branch=master

**Comment by bytewalls** [comment] 2018-03-21 18:43
@thomscode this is a caching issue with github caching the badges. 

I have reached out them try and get some clarification on how we can solve this issue outside of what their docs say and we are already doing.

**Comment by thomscode** [comment] 2018-03-22 14:48
Thanks

**Comment by mikhailsidorov** [comment] 2018-04-01 12:27
Hi guys. Have the same problem. Any ideas?

**Comment by moshfeu** [comment] 2018-11-02 06:13
@bytewalls It still happening :\

**Comment by moshfeu** [comment] 2018-11-02 20:09
A workaround is just add queryString param to the badge image url, for instance: `<img src="https://coveralls.io/repos/github/spread-the-code/git-commiter-nodejs/badge.svg?branch=master&kill_cache=1" />`

**Comment by Jacksonmwirigi** [comment] 2019-02-10 18:42
> ... i'm not sure where the source of this problem might lay -- browser? github? coveralls?
> 
> when I open my repo ( https://github.com/ericblade/mws-advanced ) I see a coveralls badge showing 63. My coverage has never been at 63 on it. When I click the badge, and go to the coveralls page, it shows the badge and coverage stats clearly being 88. If I load the badge SVG directly into my browser, I see 88.
> 
> Any ideas? I have tried clearing my cache, using different browsers.. it seems that when I source the image from coveralls, via github, it gives the wrong number, and I don't see how that would be.

Hi, i also had same problem where my badge shows 45% but on /coveralls.io page actually was 74%.
 I cleared my browser cache for the last 7 days and it worked.

**Comment by kk7ds** [comment] 2019-04-22 19:29
This is still broken for me. It's not related to browser cache, AFAICT. I can hand-edit the url all the time, but that's a terrible solution. This isn't broken for other badges, just coveralls...

**Comment by drupchen** [comment] 2019-06-30 06:58
Had the same bug, applied the workaround by @moshfeu

**Comment by iamdefinitelyahuman** [comment] 2019-06-30 14:10
The issue is that it's being cached by github, not locally.  There is a fix documented here:

https://help.github.com/en/articles/about-anonymized-image-urls

**Comment by floatingpurr** [comment] 2019-10-01 09:51
Same problem here. Not related to the browser's cache but to the GitHub's cache. Solved [removing the image from Camo's cach](https://help.github.com/en/articles/about-anonymized-image-urls#removing-an-image-from-camos-cache), e.g.,
```bash
$ curl -X PURGE https://camo.githubusercontent.com/4d04abe0044d94fefcf9af2133223....
> {"status": "ok", "id": "216-8675309-1008701"}
```

**Comment by Jaman-dedy** [comment] 2019-12-15 13:15
> Same problem here. Not related to the browser's cache but to the GitHub's cache. Solved [removing the image from Camo's cach](https://help.github.com/en/articles/about-anonymized-image-urls#removing-an-image-from-camos-cache), e.g.,
> 
> ```shell
> $ curl -X PURGE https://camo.githubusercontent.com/4d04abe0044d94fefcf9af2133223....
> > {"status": "ok", "id": "216-8675309-1008701"}
> ```

Did not work for me, still facing the same issue

**Comment by xuqingkuang** [comment] 2020-01-10 03:05
All solutions listed are not working for me ...

https://github.com/Tencent/Hippy

**Comment by meherett** [comment] 2020-06-23 05:43
In my case, by adding `&kill_cache=1` to badge seems solve problem.

[![Coverage Status](https://coveralls.io/repos/github/meherett/shuttle/badge.svg?branch=master&kill_cache=1)](https://coveralls.io/github/meherett/shuttle?branch=master)

```
[![Coverage Status](https://coveralls.io/repos/github/meherett/shuttle/badge.svg?branch=master&kill_cache=1)](https://coveralls.io/github/meherett/shuttle?branch=master)
```

<a href="https://coveralls.io/github/meherett/shuttle?branch=master"><img alt="Coverage Status" src="https://coveralls.io/repos/github/meherett/shuttle/badge.svg?branch=master&kill_cache=1"/></a>

```
<a href="https://coveralls.io/github/meherett/shuttle?branch=master">
     <img alt="Coverage Status" src="https://coveralls.io/repos/github/meherett/shuttle/badge.svg?branch=master&kill_cache=1"/>
</a>
```

**Comment by aflag** [comment] 2020-07-03 13:53
This is also an issue for me. Why does github have to cache those badges?

**Comment by Kissema** [comment] 2020-07-15 04:15
i solved the same issues with: CTRL + F5 (Chome browser)

**Comment by sixg0000d** [comment] 2020-11-21 12:40
> > Same problem here. Not related to the browser's cache but to the GitHub's cache. Solved [removing the image from Camo's cach](https://help.github.com/en/articles/about-anonymized-image-urls#removing-an-image-from-camos-cache), e.g.,
> > ```shell
> > $ curl -X PURGE https://camo.githubusercontent.com/4d04abe0044d94fefcf9af2133223....
> > > {"status": "ok", "id": "216-8675309-1008701"}
> > ```
> 
> Did not work for me, still facing the same issue

Did you just copy the camo link from the image?
I noticed that I should trim the last path of the URL, for example `https://camo.githubusercontent.com/111` instead of `https://camo.githubusercontent.com/111/222`. Then it worked fine and the images were refreshed in all my repositories.

**Comment by introkun** [comment] 2021-01-09 14:18
+1

**Comment by afinetooth** [comment] 2021-01-11 18:59
@introkun did you try the solutions above? If you want to share the coveralls URL to your repo I'll check it out for you.

**Comment by introkun** [comment] 2021-01-11 19:13
@afinetooth thanks, the workaround wirked for me.

**Comment by afinetooth** [comment] 2021-01-11 19:14
@introkun great, glad to hear it.

**Comment by HudsonSchumaker** [comment] 2022-04-19 13:34
I think you ha ve more than one action, still not  working. I have 2 repos one with one action and it is working and in the one with 3 actions is not working, always shows no status.

**Comment by afinetooth** [comment] 2022-04-19 17:47
Hi, @HudsonSchumaker. 

I think you may have been affected by a recent issue with status updates:
https://status.coveralls.io/incidents/cw09t217cxd0

Can you please open a new issue here, or email us at support@coveralls.io? Share your Coveralls Repo URL and the URLs for any builds that did not receive status updates? We will re-run those for you. 

The issue should be resolved now, btw, but let us know if you're still experiencing it. We are not 100% sure of its origin or that it won't recur. We are monitoring, but have not seen it happen for at least 12-hours.

**Comment by HudsonSchumaker** [comment] 2022-04-19 20:41
Hi, @afinetooth,
yes, seems was related to status updates, now is working fine.
thank you

**Comment by afinetooth** [comment] 2022-04-20 17:33
@HudsonSchumaker great, glad to hear it.
