### ISSUE TITLE
Exclude "tests" files from my coverarge report

### ISSUE THREAD

**Issue by buhtz** [lemurheavy/coveralls-public#1732] opened 2023-10-26 04:49 UTC
As an example

https://coveralls.io/github/bit-team/backintime

Python files containing unit tests are part of the report. That makes no sense to me. I am not interested in the coverage of uni test sources. I want to know the coverage of the productive sources.

I am confused why the coverals UI is not able to detect that by itself. How can I configure this?

**Comment by afinetooth** [comment] 2023-11-07 00:40
Hi, @buhtz. 

Coveralls is agnostic about the coverage reports you send it, which is to say that it takes for granted that they are correct. 

The step of excluding files, or specific code lines, from coverage reports is typically done at the level of your code coverage library, in its configuration file.

Assuming your coverage library is `coverage.py`, you can exclude test files from coverage reports by modifying your `.coveragerc` file&mdash;something like this:

```
# .coveragerc
[run]
omit =
    */tests/*
    */test_*.py
    *_test.py
    tests.py
```

([_reference_](https://coverage.readthedocs.io/en/7.3.2/excluding.html))

We used to have a feature that excluded certain directories from coverage reports, but we retired it because it was so rudimentary compared to the patterns and features supported by the configs of code coverage libraries.

**Comment by afinetooth** [comment] 2023-11-25 22:15
Hi @buhtz. Were you able to get this to work for you? I'm going to close this, but please re-open if the issue is unresolved.

**Closed as completed by afinetooth** 2023-11-25 22:15 UTC
Labels: documentation, set-up, troubleshooting
