### ISSUE TITLE
Coveralls builds stuck in PENDING COMPLETION

### ISSUE THREAD

**Issue by chuckdumont** [lemurheavy/coveralls-public#1461] opened 2020-07-18 17:13 UTC
Everything was working fine until a couple of months ago when I noticed that I was no longer seeing code coverage reports in pull requests.  Upon investigating, I noticed that all the recent coveralls builds were stuck in the PENDING COMPLETION state.  Clicking on the SET DONE button causes the build to complete and the PR to show the coverage notification (if it's still open).  

I'm doing parallel builds and I have the following in the [.travis.yml](https://github.com/OpenNTF/dojo-webpack-plugin/blob/master/.travis.yml):

```
notifications:
  webhooks: https://coveralls.io/webhook
```

Here's an example coveralls build that is still in the PENDING COMPLETION state: 
https://coveralls.io/builds/31535895

Like I said, this was all working fine until a couple of months ago.  I reviewed the commits that went in around the time it stopped working and I don't see anything that seems likely to have broke it.  I've since updated mocha, nyc and coveralls to the latest versions without avail.

Any suggestion on what else I might try?

**Comment by afinetooth** [comment] 2020-07-21 00:40
Hi @chuckdumont,

This usually indicates that the parallel webhook is not being called from CI, or, at least, that it's not being received with success on our end.

Have you tried sending it via the command line to see what results you get? 

This build would be a good candidate:
https://coveralls.io/builds/31535895

Try following the curl example here:
https://docs.coveralls.io/parallel-build-webhook

```
curl -k https://coveralls.io/webhook?repo_token=$COVERALLS_REPO_TOKEN -d "payload[build_num]=$BUILD_NUMBER&payload[status]=done"
```

Just use the build number from the build above for `payload[build_num]` and use the `TOKEN` in the header of that page for `COVERALLS_REPO_TOKEN`.

If that completes the build for you, then there's probably an issue at Travis. Right now, I'm not seeing the call to the webhook in the output for your build, so I couldn't assess if there was an error there, but I did notice that I'm not seeing `COVERALLS_REPO_TOKEN` mentioned in the output, so that could be your issue.

You're using Travis Pro (travis-ci.com), so try following the setup instructions here:
https://docs.coveralls.io/supported-ci-services

By adding a `.coveralls.yml` with:

```
service_name: travis-pro
repo_token: <TRAVIS ENV VAR>
```

Hope that helps. 

---

Another tip: Trying running coveralls in verbose mode [here](https://github.com/OpenNTF/dojo-webpack-plugin/blob/ca4b1f2a19d8bb81b5bd7e2352796f5b05dca6d3/package.json#L13):

```
nyc report --reporter=text-lcov | coveralls -v
```

That will add debug info to your CI output to let you see exactly what you're sending to our API. (For instance, if you're sending `COVERALLS_REPO_TOKEN` with the call to the parallel webhook.

**Comment by chuckdumont** [comment] 2020-07-22 19:06
@afinetooth - I tried the curl command as you suggested.

```
curl -k https://coveralls.io/webhook?repo_token=weKUV6HZUFMKXdV082bWUTsaTvdYk6k4u -d "payload[build_num]=137&payload[status]=done"
```

It returned a status of `{"done":true}`, but the job is still pending completion.  Any other suggestions?

**Comment by chuckdumont** [comment] 2020-07-24 14:52
@afinetooth - Can you re-open this issue?  The results of above seem to indicate a problem with coveralls, not travis or nyc.

**Comment by chuckdumont** [comment] 2020-08-04 15:34
@afinetooth - some more info.  The problem seems to be restricted to PR builds from my fork (I tried multiple branches).  Github's dependabot created a PR that was successfully updated with code coverage results just last week (https://github.com/OpenNTF/dojo-webpack-plugin/pull/297).  Commits to master also get code coverage results.  But any PRs that I create (e.g. https://github.com/OpenNTF/dojo-webpack-plugin/pull/298) from my fork never get code coverage results and the coverall builds remain stuck in PENDING COMPLETION.

Any ideas as to what might cause this?

Also, a correction to your previous comment about using Travis-pro.  That is not correct.  I'm using Travis CI (open source).

**Comment by afinetooth** [comment] 2020-08-05 01:30
@chuckdumont thanks. Opening this back up. Will reply shortly. Reading your other issue referencing this one and will reply where appropriate.

**Comment by afinetooth** [comment] 2020-08-05 02:17
Hi @chuckdumont,

**Re: curl command:**
Uncertain why this didn't work. I do see that the repo token has rolled, so the one you used is no longer valid. I suspect it was when you ran it. I can try running it from here, but want to get your approval first before I change the status of the build. Maybe you'd prefer to try it first with the new repo token?

**Re: Travis-pro v. Travis-ci.org:**
I was confused because when I click "Travis Build #137" on [this build page](https://coveralls.io/builds/31535895), I'm taken to a Travis build with a _travis-ci.com_ address. Specifically: https://travis-ci.com/github/OpenNTF/dojo-webpack-plugin/builds/172028184.

Speaking of that Travis build, I'm not seeing any call to our parallel builds webhook in any of the job logs. It may be my own lack of Travis knowledge on display here, but I would have expected to see it somewhere, either on the last job, or in an outer context. I will look into that more, to understand if and where that output should have appeared. 

I do see your config file there and it looks correct, so not sure why it wouldn't have fired. I see you've set three (3) _job_-specific `COVERALLS_PARALLEL=true` env vars; perhaps setting one more _global_ `COVERALLS_PARALLEL=true` env var would be worth trying?

**Finally, re: PR builds from your fork:**
This could be the issue. There's a known limitation with forked PRs, which is that the token we have for the repo is read-only for forked repos and therefore PR comments aren't accepted. The behavior is different from that described above, though. In these cases, the build will complete, but the PR comments just won't appear on any PR from a forked repo. 

Here's some background on the issue:
https://github.community/t/token-permissions-for-forks-once-again/16468

I feel like I might be misunderstanding this last one, though. I've only ever seen it when the developer is using GitHub Actions. The repo we obtain through the GH Action/App is the one that's affected this way. I don't know if it extends to your case.

One thing you could try is adding the [Coveralls Bot user](https://github.com/coveralls) to your forked repo as a contributor. I'm not sure it will work, but its worth a try.

Please update me on any progress.

In the meantime, I'll gather more info and update you if I discover anything more helpful.

**Comment by chuckdumont** [comment] 2020-08-05 12:33
You're correct that I changed the token.  I wanted to see if it made any difference (it didn't).

I tried running the command with the new token.  It completed successfully:

```
C:\>curl -k https://coveralls.io/webhook?repo_token=N318s7If94kLwqhEyj5Sz8QddBuCJznZC -d "payload[build_num]=137&payload[status]=done"
{"done":true}
```

But [the build](https://coveralls.io/builds/31535895) remains in the pending state.  Feel free to run the command yourself as much as necessary.

Thanks.

**Comment by afinetooth** [comment] 2020-08-05 20:56
Hi @chuckdumont,

I was able to reproduce this. I posted to our webhook endpoint several times and received the same success response you did, but the build did not complete.

To see whether the build was "complete-able" at all, we clicked the SET DONE button and that worked; so the build is now in "done" state.

I'm afraid we have no further insight as to _why_ the webhook post didn't work as that trigger. At this point, we'd ask that you share if it happens again so we can reproduce and look further into the root cause. While there are many potential obstacles to the webhook being called and succeeding, it's not something we've seen before that after the server responds with success the build does not complete.

Sorry for the inconvenience and thanks for your patience.

**Comment by chuckdumont** [comment] 2020-08-06 11:44
@afinetooth - here's another job in pending completion state: https://coveralls.io/jobs/66071024

It was kicked off by this travis job using the coveralls -v option: https://travis-ci.com/github/OpenNTF/dojo-webpack-plugin/builds/178740542

**Comment by afinetooth** [comment] 2020-08-07 21:20
Thanks @chuckdumont, ok a couple more suggestions:

**1) Set global env var**
As I mentioned above, I'm feeling a little paranoid about your env var syntax for `COVERALLS_PARALLEL=true`. I'm seeing here that it looks like those are being set on a per job level, and perhaps that's sufficient:
https://travis-ci.com/github/OpenNTF/dojo-webpack-plugin/builds/178740542/config

However, I'm familiar with this sample project demonstrating parallel builds with node-coveralls and travis:
https://github.com/coverallsapp/coveralls-node-demo/blob/master/.travis.yml

And that project sets the `COVERALLS_PARALLEL=true` env var with a `global` key above it, like:

```
env:
  global:
    - COVERALLS_PARALLEL=true
```

Note how the output of that project's Travis builds looks a bit different from yours as it regards the env vars:
https://travis-ci.org/github/coverallsapp/coveralls-node-demo/builds/679260889/config

Therefore, I think it might be a good idea to set an additional `COVERALLS_PARALLEL=true` env var at the global level like that. That makes me feel like our build, as the outer context for each job, will be aware of the fact that it's a parallel build and will be waiting for the "parallel build complete" webhook.

If that doesn't work, I might even try removing the job-based env vars and just sticking with the one at the global context.

**2) Try calling our webhook via `curl` on `after_script`**
We recently saw the notify webhook stop working at circle, so, while I have no evidence of the same at Travis, it would be good to verify you're able to make the call to our endpoint in another way. So, after trying step (1), you could try posting to our parallel build complete endpoint via `curl`, per the instructions here:
https://docs.coveralls.io/parallel-build-webhook#other-ci

Example:

```
curl -k https://coveralls.io/webhook?repo_token=$COVERALLS_REPO_TOKEN -d "payload[build_num]=$BUILD_NUMBER&payload[status]=done"
```

You can manage those variables as environment variables, per:
https://docs.travis-ci.com/user/environment-variables/

Or you can hand-code them for the purpose of your test. `$BUILD_NUMBER` should be the right env var for Travis. You can encrypt the value for `$COVERALLS_REPO_TOKEN` as suggested in the docs above, or again, just hard-code it and later refresh your repo token and generate a new one via your coveralls project SETTINGS.

`after_script` seems to be the right lifecycle hook for placement, per:
https://docs.travis-ci.com/user/job-lifecycle/

Hope that helps.

**Comment by chuckdumont** [comment] 2020-08-10 10:52
@afinetooth - I've made the changes you suggested.  Here is the PR: https://github.com/OpenNTF/dojo-webpack-plugin/pull/299/files

Unfortunately, the problem persists.  Here is the [travis build](https://travis-ci.com/github/OpenNTF/dojo-webpack-plugin/builds/179103340) and the associated [coveralls build](https://coveralls.io/builds/32644479) which remains in the pending completion state.

I tried to run the following command to complete the build:
```
curl -k https://coveralls.io/webhook?repo_token=N318s7If94kLwqhEyj5Sz8QddBuCJznZC -d "payload[build_num]=171&payload[status]=done
```

It completed with `{"done":true}` but the build remains in the PENDING COMPLETION state.

**Comment by chuckdumont** [comment] 2020-08-24 10:44
@afinetooth - any progress on this?  It seems to me that since the curl command issued directly to coveralls fails to change the status of the build (despite the response indicating success), this is an indication that Travis is not involved whatever is going wrong.  Have you been able to debug why the webhook command is failing to change the status?

**Comment by afinetooth** [comment] 2020-08-24 20:20
hi @chuckdumont sorry for the delay. 

i agree that the fact that the direct call via `curl` does not change the status here does indicate it's not related to Travis.

however, i also noticed that [all three (3) of your build's jobs at Travis](https://travis-ci.com/github/OpenNTF/dojo-webpack-plugin/builds/179103340) (Build 171) call the webhook, which should only be done for your last job.

here's an example, from job 171.2:

![Screen Shot 2020-08-24 at 1 11 29 PM](https://user-images.githubusercontent.com/918667/91091368-5434da00-e60b-11ea-97f4-c7bfccf6bfd1.png)

what i'm now thinking is that, if there _is_ any issue from your side, that might be it, which would be my bad for asking you to call the webhook from `after_script` (which apparently applies to each job).

i have resubmitted this to our dev team to have a closer look. I will also look more closely at some parallel build setups at Travis to verify I've given you the correct instructions.

feel free to follow up on this by emailing me at support@coveralls.io (just reference this issue).

**Comment by chuckdumont** [comment] 2020-09-04 11:32
If `after-script` is not the right place to call the webhook, then what is?

**Comment by afinetooth** [comment] 2020-09-18 18:38
@chuckdumont afraid I don't have a definitive answer for. [Preliminary research](https://docs.travis-ci.com/user/job-lifecycle/) suggests `after_success` might be an alternative.

However, since the issue doesn't seem to be Travis, let me suggest we go back to the original method of calling the webhook: 

```
notifications:
  webhooks: https://coveralls.io/webhook
```

If you're trying to unwind your latest config, here's a [sample project](https://github.com/coverallsapp/coveralls-node-demo), in Node, that was created to demonstrate parallel builds. (It's been implemented for Travis CI, CircleCI and GitHub Actions):
https://github.com/coverallsapp/coveralls-node-demo

Check out the [.travis.yml](https://github.com/coverallsapp/coveralls-node-demo/blob/master/.travis.yml) there and do your best to extend it for your use case. In other words, set a global env var, `COVERALLS_PARALLEL=true`, and rather than calling the webhook via `curl` on `after_script`, go back to the `notifications webhook`, which is apparently working for this sample project.

The related [coveralls builds](https://coveralls.io/github/coverallsapp/coveralls-node-demo) and [travis builds](https://travis-ci.org/github/coverallsapp/coveralls-node-demo) are also public and available for you to examine. (Just look for builds that say "VIA: travis-ci".) Example:

- https://coveralls.io/builds/33100204
- https://travis-ci.org/github/coverallsapp/coveralls-node-demo/builds/722548549

**Update**:
I see from your latest builds you've done the above and that your recent parallel builds are closed and PR comments have been delivered, so I'm hoping you've been able to resolve. 

I do see a list of jobs containing an apparent duplicate job:
![Screen Shot 2020-09-18 at 11 34 47 AM](https://user-images.githubusercontent.com/918667/93632897-f645a900-f9a2-11ea-8d10-0c039c1be067.png)

If that's an issue you want help working through, please email support@coveralls.io and reference this issue. Closing this issue per closing on the original subject.

**Comment by chuckdumont** [comment] 2020-09-23 11:48
@afinetooth - this issue is not resolved.  The only reason that PR builds have been delivered to recent jobs is because I have been manually completing the builds using the Coveralls web UI.

Please reopen this issue as the problem persists.  Also, please feel free to fork dojo-webpack-plugn and open your own pull request.  It seems that the problem is reproducible using forks other than my own.  For example, I had to manually complete the coveralls build for a recently opened PR from another user (https://github.com/OpenNTF/dojo-webpack-plugin/pull/311)

**Comment by afinetooth** [comment] 2020-09-23 17:31
@chuckdumont looking at one of your recent builds I see a clue:
https://coveralls.io/builds/33637596

I was noticing that, while your `.travis.yml` sets up with 3 parallel jobs, in your coveralls builds, four (4) jobs are displayed. (The ".1" build seems to repeat.)

If you look at the JOBS table for [_this_ build](https://coveralls.io/builds/33637596), you'll see that the duplicate ".1" build (at top) is actually very old, from 29 Nov 2017:

![Screen Shot 2020-09-23 at 10 18 46 AM](https://user-images.githubusercontent.com/918667/94046925-2bc50a80-fd86-11ea-8797-454fa33f9389.png)

I see the project was added to coveralls on 03 Oct 2017, so now I'm thinking the incoming POSTs are using repeated build numbers and our API is getting confused, thinking these jobs are for an old build that's closed, and not honoring the "complete" webhook _because_ the build was already closed.

Here's the job for the 193.1 job from 29 Nov 2017:
https://coveralls.io/jobs/31570979

And here's the one from the newer 193.1, from 22 Sep 2020:
https://coveralls.io/jobs/68057848

Note they are different jobs with the same name.

The 193.1 job from 29 Nov 2017:
https://coveralls.io/jobs/31570979

Is actually listed as job 1 of your current build (ordered by date):

![Screen Shot 2020-09-23 at 10 35 16 AM](https://user-images.githubusercontent.com/918667/94048520-7a73a400-fd88-11ea-9b9a-78a348400fd9.png)

And it's link tracks back to the [old Travis build](https://travis-ci.org/github/OpenNTF/dojo-webpack-plugin/jobs/308788174):

![Screen Shot 2020-09-23 at 10 36 27 AM](https://user-images.githubusercontent.com/918667/94048621-a3943480-fd88-11ea-8bf0-6d4ff4094f22.png)


We need to sort out why we're ending up with four (4) instead of three (3) builds. Looking into it further. Do you have any insights given the new info?

**Comment by afinetooth** [comment] 2020-09-23 17:39
Looking through your build history on coveralls (page 38/41):
https://coveralls.io/repos/182124/builds?page=38

Build 193 seems to have disappeared from the order:

![Screen Shot 2020-09-23 at 10 39 18 AM](https://user-images.githubusercontent.com/918667/94048892-0980bc00-fd89-11ea-8b72-dd9d5cfc37dd.png)

**Comment by afinetooth** [comment] 2020-09-23 17:45
Also, on page 10 of 41, it looks like the build number sequence restarted, right after build 662, around 29 Mar 2019:
https://coveralls.io/repos/182124/builds?page=10

![Screen Shot 2020-09-23 at 10 45 02 AM](https://user-images.githubusercontent.com/918667/94049434-d7238e80-fd89-11ea-8362-031a0fdfb3d6.png)

And on the first page of your build history:
https://coveralls.io/repos/182124/builds

It looks like the last build number using the original numbering series was build 664 on master on 23 Aug 2020:

![Screen Shot 2020-09-23 at 10 45 21 AM](https://user-images.githubusercontent.com/918667/94049462-e1de2380-fd89-11ea-8ae2-5b74121721d6.png)

**Comment by chuckdumont** [comment] 2020-09-27 03:03
@afinetooth - that's interesting.  I don't have any insight into why the duplicate build numbers, or why pull request builds seem to be on a different track vs. master for assigning build numbers.  It sounds like you're onto something though.

**Comment by afinetooth** [comment] 2020-10-09 01:13
@chuckdumont just looking at this again today, and I think I at least understand the source of those duplicate build numbers.

Look at this side-by-side:

![Screen Shot 2020-10-08 at 6 04 22 PM](https://user-images.githubusercontent.com/918667/95529777-b3b73100-0990-11eb-8253-a393173fe8f7.png)

We have one CI project at https://travis-ci.org/ (LEFT) that's build history tops out at Build 664, the last job we discussed for the first sequence above, and a second CI project at https://travis-ci.com/ (RIGHT) that tops out at Build 203, the last build for the second sequence of builds we discussed above.

Therefore, I think the issue is two-fold:

- You have two CI projects sending builds to coveralls
- Travis uses non-unique job IDs between it's fee and pro services (See [this issue](https://docs.coveralls.io/troubleshooting#i-see-random-commits-on-my-travis-pro-private-repo) from our [common issues & troubleshooting docs](https://docs.coveralls.io/troubleshooting))

Thus the cross-pollination. If the two CIs were from different services, I suspect they wouldn't interfere with one another.

Are you aware of the two separate CI projects and is that how you intend the project to run in CI?

If not, I would suggest switching back to the project at https://travis-ci.org/ with the longer history.

If so, I think you might be able to avoid the issue by tweaking the job number at Travis, perhaps with a prefix, etc.

Hope this helps get you to the bottom of this.

I'm going to close the issue for now (optimism), but if I'm missing something please re-open.

**Comment by chuckdumont** [comment] 2020-10-09 11:56
I've posted a [question](https://travis-ci.community/t/overlapping-build-numbers-between-travic-ci-org-and-travis-ci-com-causing-issues-with-coveralls/10126) on the travis-ci community forum.  We'll see what they say.

To be honest, this seems like a Coveralls bug to me.  travis-ci.org and travis-ci.com are different CI platforms.  Just because they have overlapping build numbers, that shouldn't be causing this problem.  Coveralls should be able to tell the difference between the two and send it's notifications to the correct target.

**Comment by afinetooth** [comment] 2020-10-09 17:01
@chuckdumont I understand your perspective and we do address the problem with the configuration step we recommend in this [issue](https://docs.coveralls.io/troubleshooting#i-see-random-commits-on-my-travis-pro-private-repo) from our [common issues & troubleshooting docs](https://docs.coveralls.io/troubleshooting):

> **I see random commits on my Travis-pro private repo.**
>
> Make sure you have “service_name: travis-pro” in your .coveralls.yml.
>
> Travis uses non-unique job id’s between its free and pro services, so when Coveralls doesn’t know that your service-name is Travis-pro, it looks up the info for those job ids using the free Travis API – that’s why they will show random committers, etc. The opposite cannot happen with the proper credentials, so you don’t need to worry that your data is leaking out. Once your ENV var is set to specify travis-pro, the correct info will be pulled from Travis’s pro API.

By this same token, I would recommend distinguishing your CI service by adding a `service-name` to your `.coveralls.yml`.

I looked at [your project](https://github.com/OpenNTF/dojo-webpack-plugin) and I don't see a `.coveralls.yml` file.

If you add one, and specify one of the two services&mdash;I'm recommending `travis-ci` for the older project with more history at https://travis-ci.org/, but `travis-pro` for the project at https://travis-ci.com/ will also work&mdash;that should help. 

However, I think running two CIs for the project will continue causing issues. Is there an important use case for running two CI projects? If that use case is compelling, then the backup recommendation is to tweak the job number at Travis Pro, perhaps with a prefix, etc. (NOTE: Just read your [question](https://travis-ci.community/t/overlapping-build-numbers-between-travic-ci-org-and-travis-ci-com-causing-issues-with-coveralls/10126) at Travis and I see you've already searched their docs for such a solution without luck. I'll keep following along there.)

**Comment by afinetooth** [comment] 2020-10-09 17:09
@chuckdumont having read your [question](https://travis-ci.community/t/overlapping-build-numbers-between-travic-ci-org-and-travis-ci-com-causing-issues-with-coveralls/10126) at Travis, I see that your project moved to Travis Pro (https://travis-ci.com/). If that's the future of the project then choosing that CI service and configuring your `.coveralls.yml` with `service-name: travis-pro` probably makes the most sense.

I do think it should stop the cross-pollination of old job numbers from Travis CI (https://travis-ci.org/).

**Comment by afinetooth** [comment] 2020-10-09 17:20
@chuckdumont replied to your [question](https://travis-ci.community/t/overlapping-build-numbers-between-travic-ci-org-and-travis-ci-com-causing-issues-with-coveralls/10126/2?u=afinetooth) at Travis.

**Comment by chuckdumont** [comment] 2020-10-10 21:51
@afinetooth - I added the .coveralls.yml as you suggested.  See the [pull request](https://github.com/OpenNTF/dojo-webpack-plugin/pull/313).  This seems to have gotten rid of the cross-pollination that you mentioned, but the [coveralls build](https://coveralls.io/jobs/68943930) is still did not complete.

**Comment by afinetooth** [comment] 2020-10-12 18:21
@chuckdumont, on the bright side, some progress.

I think the remaining issue lies in your [`.travis.yml`](https://github.com/OpenNTF/dojo-webpack-plugin/blob/master/.travis.yml).

Below is a comparison of [our `.travis.yml` config file (at Travis)](https://travis-ci.org/github/coverallsapp/coveralls-node-demo/jobs/721794770/config) for our demo parallel project (LEFT) compared to [your `.travis.yml` (at Travis)](https://travis-ci.com/github/OpenNTF/dojo-webpack-plugin/jobs/397848719/config) (RIGHT):

![Screen Shot 2020-10-12 at 11 09 58 AM](https://user-images.githubusercontent.com/918667/95777652-7a760e00-0c7b-11eb-9506-64a32cb23127.png)

I think the following changes will help:

- Outdent your `jobs:` section to the leftmost position. right now it looks like it's under `env:`
- Call `npm run coveralls` in each job, rather than in the `after_success:` block. remove `after_success:` block.

And then for good measure:

- call `npm run coveralls -v` (per [node-coveralls readme](https://www.npmjs.com/package/coveralls)) so we see the debug output in your next build log. 

Leave everything else as-is.

**Comment by chuckdumont** [comment] 2020-10-13 11:34
@afinetooth - I made the changes you requested in the [pull request](https://github.com/OpenNTF/dojo-webpack-plugin/pull/313), but the results are the same.  The Coveralls build is never completed.

I think we're missing the point by focusing on travis.  The fact that the curl request to set the status to done fails to do so, despite reporting successful completion, seems to indicate the issue is with coveralls, not travis.

**Comment by chuckdumont** [comment] 2020-10-13 12:29
@afinetooth - since this issue is still unresolved, could you reopen?  Thanks.

**Comment by afinetooth** [comment] 2020-10-13 16:01
@chuckdumont thanks for making those changes. reopening the issue. 

I think the issue is based on the build number already existing and being associated with a build that’s already been closed. 

Looking into a fix for you.

**Comment by afinetooth** [comment] 2020-10-13 16:27
@chuckdumont looking into it further, here's the supporting evidence that the issue is the old build numbers causing confusion (on our end):

Here's one of your most recent builds (209):
https://coveralls.io/jobs/69053509

The associated build at travis-ci.com:
https://travis-ci.com/github/OpenNTF/dojo-webpack-plugin/builds/189691770

Shows you're properly configured to call the webhook.

So, re-producing the webhook's action with this command:
`curl -k https://coveralls.io/webhook?repo_token=N318s7If94kLwqhEyj5Sz8QddBuCJznZC -d "payload[build_num]=209&payload[status]=done"`

Should close the build, but it doesn't:

Instead it responds with a success message:
`{"done":true,"url":"https://coveralls.io/builds/14518921","jobs":1}`

But the build returned in the success message is the _old_ build 209 from your project:
https://coveralls.io/builds/14518921

**Comment by afinetooth** [comment] 2020-10-13 16:46
@chuckdumont we're going to push a fix now. please standby.

**Comment by afinetooth** [comment] 2020-10-13 18:31
@chuckdumont, fix pushed. You should be good-to-go now.

I tested the `curl` call to the webhook for the latest build (209):
`curl -k https://coveralls.io/webhook?repo_token=N318s7If94kLwqhEyj5Sz8QddBuCJznZC -d "payload[build_num]=209&payload[status]=done"`

And this time received the correct build with the success response:
`{"done":true,"url":"https://coveralls.io/builds/34134841","jobs":4}`

Also, verified the build is now closed:
https://coveralls.io/builds/34134841

The fix should address builds with duplicate job numbers going forward. 

Sorry it took as long as it did, but appreciate you helping us suss it out. Thanks for your patience.

**Closed as completed by afinetooth** 2020-10-13 18:31 UTC
Labels: parallel-builds

**Comment by vtjnash** [comment] 2020-11-12 05:03
I think I've been hitting this problem too. I'm one of the maintainers of the Coveralls submission tool for Julia, and recent builds for our tool aren't showing up in the UI anymore. While I know I can promote the latest job (https://travis-ci.com/github/JuliaCI/Coverage.jl/builds/200215224) manually with `curl -k https://coveralls.io/webhook?repo_token=$token -d "payload[build_num]=923&payload[status]=done"`, since I've done that for all of the other builds since April, I don't know why the automatic submissions aren't working anymore. The only recent change I know of is that we've also moved from the old travis-ci.org website to the new travis-ci.com website.

Help would be appreciated!
