### ISSUE TITLE
Coverage info sent from Travis CI, but not updating on Coveralls

### ISSUE THREAD

**Issue by josephspurrier** [lemurheavy/coveralls-public#281] opened 2014-04-12 08:38 UTC
My build is here: https://coveralls.io/builds/676447

I set up another project at the same time and it is working fine. I've deleted my repo from Coveralls, added it back, and then added another commit, but it still doesn't work.

Here is the log from Travis CI:

```
$ php vendor/bin/coveralls -v
Load coverage clover log:
  - /home/travis/build/josephspurrier/surfstack-filtering/build/logs/clover.xml
Found [32m1[0m source file:
  - [32m100.00%[0m SurfStack/Filtering/Validate.php
Coverage: [32m100.00% (41/41)[0m
Collect git info
Read environment variables
Dump submitting json file: /home/travis/build/josephspurrier/surfstack-filtering/build/logs/coveralls-upload.json
File size: [32m1.48[0m kB
Submitting to https://coveralls.io/api/v1/jobs
Finish submitting. status: 200 OK
Accepted Job #16.2
You can see the build on https://coveralls.io/jobs/1592941
```

**Comment by devonparsons** [comment] 2015-01-30 07:29
Same issue  
https://travis-ci.org/devonparsons/ruby-tricks/builds/48863509  
https://coveralls.io/builds/1832790

**Comment by nickmerwin** [comment] 2015-01-30 16:45
@devonparsons it looks like your test suite isn't generating coverage data since none of your source files are directly required.

Could you try requiring them first and then calling the methods directly in the spec examples?

**Comment by Swaagie** [comment] 2015-02-03 10:46
Issue still persists, see https://coveralls.io/builds/1853557, or any other build for that repo

**Comment by SmokinCaterpillar** [comment] 2015-02-03 14:40
Similar problem for me, my build succeeds but coverage data is not displayed.

https://travis-ci.org/SmokinCaterpillar/pypet/jobs/49314732

Even though the end of the log file it reads

    ==
    Reporting 23 files
    ==

    pypet/__init__.py - 14/75
    pypet/_version.py - 1/1
    pypet/annotations.py - 66/209
    pypet/compat.py - 19/70
    pypet/environment.py - 729/2532
    pypet/gitintegration.py - 8/100
    pypet/naturalnaming.py - 1135/3402
    pypet/parameter.py - 684/2475
    pypet/pypetconstants.py - 91/295
    pypet/pypetexceptions.py - 29/84
    pypet/pypetlogging.py - 32/81
    pypet/storageservice.py - 2004/5803
    pypet/trajectory.py - 1092/3635
    pypet/utils/__init__.py - 0/1
    pypet/utils/comparisons.py - 70/208
    pypet/utils/decorators.py - 61/174
    pypet/utils/explore.py - 25/72
    pypet/utils/hdf5compression.py - 29/82
    pypet/utils/helpful_classes.py - 30/59
    pypet/utils/helpful_functions.py - 91/228
    pypet/utils/ptcompat.py - 30/138
    pypet/utils/storage_factory.py - 23/69
    pypet/utils/to_new_tree.py - 74/137
    Coverage submitted!
    Job #724.7
    https://coveralls.io/jobs/4273886
    {u'url': u'https://coveralls.io/jobs/4273886', u'message': u'Job #724.7'}
    travis_time:end:066301f4:start=1422971429344054174,finish=1422971935537024728,duration=506192970554

coveralls says there's no data available:
https://coveralls.io/jobs/4273886

**Comment by SmokinCaterpillar** [comment] 2015-02-03 15:11
Sorry for bothering. Apparently this issued could be solved simply by waiting :-).
After some time coveralls did crunch the data and displayed it.

**Comment by LegoStormtroopr** [comment] 2015-03-09 09:43
I've been having similar issues for a while, its started after I added a .coverallsrc file, and sort of went a way after I removed it. But now occasionally some branches won't report properly.

* https://coveralls.io/builds/2071225
* https://coveralls.io/builds/2063383
* https://coveralls.io/builds/2019450

I made a StackOverflow post as well, but it didn't get much attention: http://stackoverflow.com/questions/28475470/broken-coveralls-no-longer-reporting-coverage-from-travisci

**Comment by Legoless** [comment] 2015-10-22 19:12
I have same issues and I am using Slather to upload data to Coveralls. Is there any catch why it worked and now it doesn't? Nothing changed really.

**Comment by gnzlbg** [comment] 2015-10-26 19:00
I am also having this issue.

**Comment by chfw** [comment] 2015-12-08 17:01
Same issue here: https://coveralls.io/github/chfw/pyexcel-io , no updates for two month

**Comment by benjaoming** [comment] 2015-12-20 14:43
Same issue in django-wiki and xhtml2pdf, Coveralls PR feedback gone, but they are still alive and PRs are showing on coveralls.io

**Comment by ket4yii** [comment] 2016-07-20 22:58
Same issue with PR's when I use coveralls status checking on github and build my project by travis-ci. Build is passed and travis says reports were sent, but nothing in PR status and coveralls dashboard.

**Comment by gund** [comment] 2016-09-30 17:16
I have same issue with node-coveralls but problem is a bit different:
Information about builds sent to [coveralls repo](https://coveralls.io/github/gund/ng2-http-interceptor) but coverage data always empty.

I'm reporting from Travis CI with simple command:
```bash
cat ./coverage/coverage.lcov | ./node_modules/coveralls/bin/coveralls.js -v
```

And what's strange - no output from this command (except warning about env variable)

If someone knows what can be the problem - please check [this issue](https://github.com/gund/ng2-http-interceptor/issues/1) - will be much appreciated.

Thanks

**Comment by vinniefalco** [comment] 2017-04-20 21:57
I'm having the same problem as well.

**Comment by vpotseluyko** [comment] 2017-05-08 23:10
+1

**Comment by vinniefalco** [comment] 2017-05-08 23:19
Still happening.

**Comment by jakirkham** [comment] 2017-05-09 02:13
Started happening to me on a project that has been sending coverage information and registering it fine up until the past 4hrs. After this point I can see the coverage data in Travis CI, the Travis CI job shows the data being submitted to Coveralls, but Coveralls fails to show the results. Here's a recent [build]( https://travis-ci.org/dask-image/dask-ndfourier/builds/230188983 ) and its Coveralls [data]( https://coveralls.io/builds/11429803 ). On Coveralls it claims the results are still pending even though Travis CI has already noted the results were sent.

**Comment by vinniefalco** [comment] 2017-05-09 03:35
This is too much trouble, if its not fixed in a few days I will just yank coveralls from my repo. It hasn't worked correctly in over 6 months now.

**Comment by ngdinhtoan** [comment] 2017-05-09 04:11
I am also having same issue.

**Comment by zengfenfei** [comment] 2017-05-09 05:19
Same problem with my Travis build: https://travis-ci.org/zengfenfei/ringcentral-ts/jobs/230185994

**Comment by Bamieh** [comment] 2017-05-09 11:07
same issue here.

**Comment by LeonardoGentile** [comment] 2017-05-09 11:27
Same here

**Comment by vpotseluyko** [comment] 2017-05-09 11:32
Right now coveralls api status reports degrated perfomance, they aree working at it.

**Comment by katbusch** [comment] 2017-05-09 22:39
You can check API status here: http://status.coveralls.io/

**Comment by apolukhin** [comment] 2017-05-21 11:17
Hit by that issue in here: https://coveralls.io/github/apolukhin/Boost-Cookbook-4880OS

On the main page last build of the _second_edition_ branch is reported to happen at 09 May, however here are some new builds https://coveralls.io/builds/11617782 that are NOT shown on the main page. Also, looks like last builds do not show the overall coverage AT ALL https://coveralls.io/builds/11617782

**Comment by vinniefalco** [comment] 2017-05-21 11:55
I pulled Coveralls from my repository. Its too much trouble, and codecov.io works.

**Comment by Bamieh** [comment] 2017-05-21 12:28
@vinniefalco i did the same, the issue is with coveralls itself not the node extension. in some projects i have both codecov and coveralls plugged in, in case any goes does i still have the second.

**Comment by vinniefalco** [comment] 2017-05-21 13:15
@Bamieh Yep, I had both for a while. But the problem is coveralls never indicates to Github that the "check" completed. So I have an amber dot at the top commit of the master branch that says "5/6 checks passed". Been that way for over 6 months. I removed coveralls so now I have 5/5 checks passed and I get a green checkmark.

**Comment by kuanb** [comment] 2018-03-06 17:26
So... What is the solution here? I see this, and variants of this issue peppered throughout the web, with no solution, save dumping Coveralls and switching to CodeCov.io. Surely that can't be the only answer after 4 years? (!!)

**Comment by barryrld** [comment] 2018-03-07 01:43
@kuanb I've just come across this issue today too. Coveralls had been working perfectly for me since November on a project, but it started reporting that there was no data and would only show the coverage data from a few days ago - when the last commit got successfully reported to Coveralls. I've been poking around trying to find others with similar issues. There doesn't appear to be an explanation as to why it stopped working from the commits made around that time.

For what it's worth, I saw that some people had made the move to codecov, so I thought I'd give it a shot. Codecov is working well now for me and it doesn't require an environment variable in the build system - in my case CircleCI. It's a small point. The experience seems to be a bit more refined on first glance, but I'll keep evaluating over the coming days.

If you're interested the package.json and CircleCI config I'm currently using are:

https://github.com/panacea-js/core/blob/master/package.json - notably the `codecov-report` script
https://github.com/panacea-js/core/blob/master/.circleci/config.yml - notably the `run: npm run codecov-report` run task

Hope this helps in some way - although not great for directly solving your Coveralls issue :disappointed:

**Comment by Bamieh** [comment] 2018-03-07 08:59
@barryrld @kuanb I have switched to codecov in almost all my projects, it also supports coverage for a full monorepo at once. while coveralls only works for one project per github repo.

**Comment by bytewalls** [comment] 2018-03-07 16:43
@barryrld we had a bad deploy yesterday which caused a job processing backlog, this situation has been fixed.

@bamieh Putting a note in our feature requests for support of multiple projects in a single repo.

I'm closing this issue for now, I believe we have resolved many peoples issues here, and improvements have been implemented since this issue was initially opened almost 4 years ago.

**Closed by bytewalls** 2018-03-07 16:43 UTC
Labels: legacy

**Comment by ddanet** [comment] 2018-03-07 19:04
Unfortunately Coveralls is just to unstable for us as well.  We are removing integrations for all of our projects and moving to alternate solution.   I'm hoping for smooth sailing for Coveralls.

**Comment by gnzlbg** [comment] 2018-03-08 08:47
@ddanet I can recommend codecov as well.

I first commented on this issue on Oct 26, 2015 and kept having these problems till mid 2017. I then migrated to codecov and everything worked without issues.

**Comment by Bamieh** [comment] 2018-03-08 13:22
@bytewalls thanks buddy! good luck

**Comment by wkschwartz** [comment] 2018-10-08 14:31
I'm also having this problem. Passing builds: [at Travis](https://travis-ci.org/wkschwartz/wrapitup/jobs/438438505). Coveralls has received the data but not showing any results: [at Coveralls](https://coveralls.io/jobs/40982337)

**Comment by erayerdin** [comment] 2018-10-16 18:10
I'm developing [this project](https://github.com/erayerdin/pyairmore) and [the job in my Travis build](https://travis-ci.org/erayerdin/pyairmore/jobs/442301118) seems to send the data below to coveralls successfully (taken with `--verbose`).

```
{"source_files": [{"name": "pyairmore/__init__.py", "source": "\"\"\"\nPyairmore package\n\"\"\"  # todo [1] package doc\n\n__version__ = \"0.1.0a4\"\n__author__ = \"Eray Erdin\"\n\n\nclass Refreshable:\n    # todo doc\n\n    def refresh(self) -> None:\n        raise NotImplementedError(\"This method needs to be overriden by children.\")\n", "coverage": [null, null, null, null, 1, 1, null, null, 1, null, null, 1, 0]}, {"name": "pyairmore/request.py", "source": "# todo 1 - doc for package\nimport ipaddress\n\nimport requests\n\n\nclass AirmoreSession(requests.Session):\n    # todo 1 - doc for class\n\n    def __init__(self, ip_address: ipaddress.IPv4Address, port: int = 2333):\n        # todo 2 - doc for init\n        super().__init__()\n\n        self.ip_address = ip_address  # type: ipaddress.IPv4Address\n        self.port = port  # type: int\n        self.is_mocked = False\n\n    @property\n    def is_server_running(self) -> bool:\n        response = self.post(\"/?Key=PhoneCheckAuthorization\")\n        body = response.text  # type: str\n\n        is_running = False\n\n        if body == '\"0\"':  # i don't know, server returns that if it is running\n            is_running = True\n\n        return is_running\n\n    def request_authorization(self) -> bool:\n        response = self.post(\"/?Key=PhoneRequestAuthorization\")\n\n        is_accepted = False\n\n        if response.text == \"true\":\n            is_accepted = True\n\n        return is_accepted\n\n    def request(self, method, url, params=None, data=None, headers=None, cookies=None, files=None, auth=None,\n                timeout=None, allow_redirects=True, proxies=None, hooks=None, stream=None, verify=None, cert=None,\n                json=None) -> requests.Response:\n        # todo 1 - doc for method\n        new_url = self.base_url + url\n\n        return super().request(method, new_url, params, data, headers, cookies, files, auth, timeout, allow_redirects,\n                               proxies, hooks, stream, verify, cert, json)\n\n    @property\n    def base_url(self) -> str:\n        prefix = \"http\"\n\n        if self.is_mocked:\n            prefix = \"mock\"\n\n        return \"{}://{}:{}\".format(prefix, self.ip_address, self.port)\n", "coverage": [null, 1, null, 1, null, null, 1, null, null, 1, null, 1, null, 1, 1, 1, null, 1, 1, 1, 1, null, 1, null, 1, 1, null, 1, null, 1, 1, null, 1, null, 1, 1, null, 1, null, 1, null, null, null, 1, null, 1, null, null, 1, 1, 1, null, 1, 1, null, 1], "branches": [25, 0, 26, 1, 35, 0, 36, 1, 53, 0, 54, 1, 25, 0, 28, 0, 35, 0, 38, 0, 53, 0, 56, 0]}, {"name": "pyairmore/services/__init__.py", "source": "# todo [1] package doc\nimport typing\n\nimport requests\n\nimport pyairmore.request\n\n\nclass ServerIdleException(Exception):\n    # todo 1 - class doc\n\n    def __init__(self, service):\n        message = \"Server is found idle while making request for {}. The reasons might be:\\n\" \\\n                  \" - You might not even have installed Airmore to your device.\\n\" \\\n                  \" - Sometimes your Airmore server goes idle for battery. You need to open it up again.\".format(\n            service.__class__.__name__\n        )\n        super().__init__(message)\n\n\nclass AuthorizationException(Exception):\n    # todo 1 - class doc\n\n    def __init__(self):\n        message = \"You are not authorized for this session. Please accept authorization on target device.\"\n        super().__init__(message)\n\n\nclass Service:\n    # todo 1 - class doc\n\n    def __init__(self, session: pyairmore.request.AirmoreSession):\n        # todo 2 - init doc\n\n        self.session = session\n        self._response = None  # type: requests.Response\n\n    def request(self, process_type: typing.ClassVar[\"Process\"]) -> requests.Response:\n        is_running = self.session.is_server_running\n\n        if not is_running:\n            raise ServerIdleException(self)\n\n        is_authorized = self.session.request_authorization()\n\n        if not is_authorized:\n            raise AuthorizationException()\n\n        process = process_type(self)\n        process.url = self.session.base_url + process.url\n        return self.session.send(process)\n\n\nclass Process(requests.PreparedRequest):\n    # todo 1 - class doc\n\n    def __init__(self, service: Service):\n        # todo 2 - init doc\n        super().__init__()\n\n        self.service = service\n\n    def prepare_url(self, url, params):\n        super().prepare_url(url, params)\n        self.url = self.service.session.base_url + url\n", "coverage": [null, 1, null, 1, null, 1, null, null, 1, null, null, 1, 0, null, null, null, null, 0, null, null, 1, null, null, 1, 0, 0, null, null, 1, null, null, 1, null, null, 1, 1, null, 1, 1, null, 1, 0, null, 1, null, 1, 0, null, 1, 1, 1, null, null, 1, null, null, 1, null, 1, null, 1, null, 1, 0, 0], "branches": [41, 0, 44, 1, 46, 0, 49, 1, 41, 0, 42, 0, 46, 0, 47, 0]}, {"name": "pyairmore/services/device.py", "source": "# todo 1 - package doc\n\nimport warnings\n\nfrom pyairmore.services import Service\n\ntry:\n    import PIL\n    import PIL.Image\nexcept ImportError:\n    warnings.warn(\"In order to use DeviceService::take_screenshot, you will need 'pillow' module to be installed.\",\n                  ImportWarning)\n\nimport typing\n\nimport pyairmore.request\nimport pyairmore.services\n\n\nclass DeviceDetail:  # todo 1 - device detail class\n    def __init__(self):\n        self.model = None  # type: str\n        self.brand = None  # type: str\n        self.device_name = None  # type: str\n        # phone_number might be \"\" from airmore server\n        self.phone_number = None  # type: str\n        self.imei = None  # type: str\n        self.imsi = None  # type: str\n        self.mac_address = None  # type: str\n        self.serial_number = None  # type: str\n        self.device_serial_number = None  # type: str\n        self.power = 0.0  # type: float\n        self.resolution = (0, 0)  # type: typing.Tuple[int]\n        self.is_root = False  # type: bool\n        self.sdk_version_id = 0  # type: int\n        self.sdk_version_name = None  # type: str\n        self.platform = 1  # type: int\n        self.app_version_code = 1  # type: int\n        self.app_version_name = None  # type:str\n        self.is_wifi_on = True  # type: bool\n        # all in bytes\n        self.external_sd_total_size = 0  # type: int\n        self.external_sd_available_size = 0  # type: int\n        self.internal_sd_total_size = 0  # type: int\n        self.internal_sdv_available_size = 0  # type: int\n        self.memory_total_size = 0  # type: int\n        self.memory_available_size = 0  # type: int\n        self.call_history_count = 0  # type: int\n        self.contacts_count = 0  # type: int\n        self.messages_count = 0  # type: int\n        self.pictures_count = 0  # type: int\n        self.pictures_total_size = 0  # type: int\n        self.songs_count = 0  # type: int\n        self.songs_total_size = 0  # type: int\n        self.videos_count = 0  # type: int\n        self.videos_total_size = 0  # type: int\n        self.apks_total_size = 0  # type: int\n        self.system_apks_count = 0  # type: int\n        self.user_apks_count = 0  # type: int\n\n#############\n# Processes #\n#############\n\n\nclass DeviceDetailProcess(pyairmore.services.Process):\n    # todo 1 - class doc\n\n    def __init__(self, service: pyairmore.services.Service):\n        super().__init__(service)\n\n        self.url = \"/?Key=PhoneGetDeviceInfo&IsDetail=true\"\n        self.method = \"POST\"\n\n\nclass DeviceScreenshotProcess(pyairmore.services.Process):\n\n    def __init__(self, service: Service):\n        super().__init__(service)\n\n        self.url = \"/?Key=PhoneRefreshScreen\"\n        self.method = \"POST\"\n\n\n############\n# Services #\n############\n\n\nclass DeviceService(pyairmore.services.Service):\n    # todo 1 - class doc\n    def __init__(self, session: pyairmore.request.AirmoreSession):\n        super().__init__(session)\n\n    def fetch_device_detail(self) -> DeviceDetail:\n        # todo 1 - fetch_device_detail doc\n        response = self.request(DeviceDetailProcess)\n        data = response.json()  # type: dict\n        detail = DeviceDetail()\n\n        detail.model = data.get(\"Model\", None)\n        detail.brand = data.get(\"Brand\", None)\n        detail.device_name = data.get(\"DeviceName\", None)\n        # if PhoneNumber is \"\", then stay None\n        detail.phone_number = None if data.get(\"PhoneNumber\", None) == \"\" else data.get(\"PhoneNumber\", None)\n        detail.imei = data.get(\"IMEI\", None)\n        detail.imsi = data.get(\"IMSI\", None)\n        detail.mac_address = data.get(\"MAC\", None)\n        detail.serial_number = data.get(\"SerialNum\", None)\n        detail.device_serial_number = data.get(\"DeviceSN\", None)\n        detail.power = data.get(\"Power\", 0.0) / 100\n\n        # resolution parsing\n        if \"*\" in data.get(\"Resolution\", \"\"):\n            detail.resolution = tuple(map(lambda x: int(x), data.get(\"Resolution\").split(\"*\", 1)))\n\n        detail.is_root = False if data.get(\"Root\", None) == 0 else True\n        detail.sdk_version_id = data.get(\"SDKVersionID\", 1)\n        detail.sdk_version_name = data.get(\"SDKVersionName\", None)\n        detail.platform = data.get(\"Platform\", 1)\n        detail.app_version_code = data.get(\"AppVersionCode\", 1)\n        detail.app_version_name = data.get(\"AppVersionName\", None)\n        detail.is_wifi_on = False if data.get(\"Wifi\", None) == 0 else True\n        detail.external_sd_total_size = data.get(\"ExtSDSize\", 0)\n        detail.external_sd_available_size = data.get(\"ExtSDAvaSize\", 0)\n        detail.internal_sd_total_size = data.get(\"SDSize\", 0)\n        detail.internal_sdv_available_size = data.get(\"SDVAvaSize\", 0)\n        detail.memory_available_size = data.get(\"MemoryAvaSize\", 0)\n        detail.memory_total_size = data.get(\"MemorySize\", 0)\n        detail.call_history_count = data.get(\"CallHistoryCount\", 0)\n        detail.contacts_count = data.get(\"ContactCount\", 0)\n        detail.messages_count = data.get(\"MsgCount\", 0)\n        detail.pictures_count = data.get(\"PicCount\", 0)\n        detail.pictures_total_size = data.get(\"PicSize\", 0)\n        detail.songs_count = data.get(\"MusicCount\", 0)\n        detail.songs_total_size = data.get(\"MusicSize\", 0)\n        detail.videos_count = data.get(\"VideoCount\", 0)\n        detail.videos_total_size = data.get(\"VideoSize\", 0)\n        detail.apks_total_size = data.get(\"APKSize\", 0)\n        detail.system_apks_count = data.get(\"SystemApkCount\", 0)\n        detail.user_apks_count = data.get(\"UserApkCount\", 0)\n\n        return detail\n\n    def take_screenshot(self) -> PIL.Image:\n        # todo 1 - take_screenshot doc\n\n        response = self.request(DeviceScreenshotProcess)\n        content = response.text\n        content = self.__purify_screenshot_base64_content(content)\n\n        from io import BytesIO\n        import base64\n\n        image = PIL.Image.open(BytesIO(base64.b64decode(content)))\n\n        return image\n\n    def __purify_screenshot_base64_content(self, encoded: str) -> str:\n        return encoded[22:]\n", "coverage": [null, null, 1, null, 1, null, 1, 1, 1, 0, 0, null, null, 1, null, 1, 1, null, null, 1, 1, 1, 1, 1, null, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, null, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, null, null, null, null, null, null, 1, null, null, 1, 1, null, 1, 1, null, null, 1, null, 1, 1, null, 1, 1, null, null, null, null, null, null, null, 1, null, 1, 1, null, 1, null, 1, 1, 1, null, 1, 1, 1, null, 1, 1, 1, 1, 1, 1, 1, null, null, 1, 1, null, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, null, 1, null, 1, null, null, 1, 1, 1, null, 1, 1, null, 1, null, 1, null, 1, 1], "branches": [114, 0, 115, 1, 115, 0, 115, 1, 115, 0, 117, 1, 114, 0, 117, 0]}], "git": {"branch": "master", "head": {"id": "2a5b11e60742415fbecdd1f59100634f21af8673", "author_name": "Eray Erdin", "author_email": "eraygezer.94@gmail.com", "committer_name": "Eray Erdin", "committer_email": "eraygezer.94@gmail.com", "message": "incremented version"}, "remotes": [{"name": "origin", "url": "https://github.com/erayerdin/pyairmore.git"}]}, "config_file": ".coveragerc", "repo_token": "[secure]", "service_name": "travis-ci", "service_job_id": "442301118", "service_pull_request": "false"}
```

And it gives the output:

```
==
Reporting 4 files
==
pyairmore/__init__.py - 4/13
pyairmore/request.py - 31/56
pyairmore/services/__init__.py - 24/65
pyairmore/services/device.py - 111/160
Coverage submitted!
{'message': 'Job #39.5', 'url': 'https://coveralls.io/jobs/41261862'}
Job #39.5
https://coveralls.io/jobs/41261862
```

which means coveralls can take the data successfully. However, it shows neither on [the project's coveralls page](https://coveralls.io/github/erayerdin/pyairmore] nor on [its job page](https://coveralls.io/jobs/41261862).
