### ISSUE TITLE
coveralls.io/builds/<sha>.json?repo_token=<token> does not work 

### ISSUE THREAD

**Issue by DenisPalnitsky** [lemurheavy/coveralls-public#1345] opened 2019-08-27 12:43 UTC
I have a private repo and try to get coverage for a recent commit hash using 
`curl "https://coveralls.io/builds/<sha>.json?repo_token=<token>"`
using newly generated token but I'm getting "Access Denied"

**Comment by ashishbedicn** [comment] 2019-09-09 07:39
Not working for me either.

**Comment by eyal0** [comment] 2019-12-04 03:53
Related #1380 

This is breaking the coveralls chrome extension.

**Comment by afinetooth** [comment] 2020-04-07 18:20
@DenisPalnitsky is this still an issue for you? (Not able to reproduce at this time.)

Closing the issue for now. Just reply if you have questions or need follow-up.

**Closed by afinetooth** 2020-04-07 18:20 UTC
Labels: set-up

**Comment by eyal0** [comment] 2020-04-08 15:42
This is still an issue for me. The chrome extension doesn't work. I tested it yesterday.

**Comment by willgdjones** [comment] 2020-04-10 16:16
I can also confirm that the Chrome Extension does not currently work for me :(.

**Comment by willgdjones** [comment] 2020-04-10 16:40
This is what is what is currently blocking me buying a Coveralls subscription. Codecov setup was painful and more expensive but ultimately worked in the end.
