### ISSUE TITLE
Coveralls Chrome extension causes some pages to hang

### ISSUE THREAD

**Issue by eyal0** [lemurheavy/coveralls-public#1147] opened 2018-06-20 08:49 UTC
After installing this Chrome extension: https://chrome.google.com/webstore/detail/coveralls/plmnloljehipkinecpeoehdnkjhbmcjc/support

My Chrome window hangs whenever I visit this link: https://github.com/pcb2gcode/pcb2gcode/commit/dd7a96d1d2394e48f5b9f992cf9b58a5df78c6a3

**Comment by bytewalls** [comment] 2018-06-20 16:44
Thanks for the report, we will work on getting a fix for this out. Sorry for the inconvenience.

If you don't want to totally uninstall the extension, clicking the logo in your toolbar will deactivate it. I'll let you know as soon as we release the fix.

**Comment by bytewalls** [comment] 2018-06-20 22:06
@eyal0 we have released a new version to address this problem sorry for the inconvenience.

**Comment by eyal0** [comment] 2018-06-21 09:35
I don't see it working yet.  At this link, the last update still says February: https://chrome.google.com/webstore/detail/coveralls/plmnloljehipkinecpeoehdnkjhbmcjc

**Comment by bytewalls** [comment] 2018-06-25 21:41
@eyal0, released a new version today. 

We were unable to recreate the issue, but believe it is caused by some bandwidth saving caching the plugin does. (It cache's some calls to coveralls where the data is static for up to 7 days) Some bad data was likely stored in the cache due to the previous bug which was fixed. Please let me know if version 0.0.4 does not solve your issue.

**Closed by bytewalls** 2018-06-25 21:41 UTC

**Comment by eyal0** [comment] 2018-06-26 07:52
My problem seems to be gone.  Great!

Is it possible to see coverage in the commit link of a PR?  For example, I see no coverage info here:

https://github.com/pcb2gcode/pcb2gcode/pull/166/files

I don't know if that's even possible or if it even makes sense to show coverage there.  Just curious.

**Comment by bytewalls** [comment] 2018-06-26 16:33
It is not currently possible with the chrome extension, but as noted with the version number it is early days for our chrome extension.

Adding the ability to see coverage information on a PR is absolutely on our list of things we want built in there. We are working on some other core infrastructure updates at the moment which need to be finished to make it a reality.

**Comment by eyal0** [comment] 2018-06-26 17:46
Really cool. Thanks for being so responsive!
