### ISSUE TITLE
Could not find badge in README

### ISSUE THREAD

**Issue by krhubert** [lemurheavy/coveralls-public#702] opened 2016-01-21 11:10 UTC
I have two repos and on both coveralls can't find badge in README but they are there.

repo: github.com/krhubert

**Comment by honzajavorek** [comment] 2016-01-21 15:20
The same:

- https://coveralls.io/github/apiaryio/blueprint-transactions
- https://github.com/apiaryio/blueprint-transactions

<img width="832" alt="screen shot 2016-01-21 at 16 20 04" src="https://cloud.githubusercontent.com/assets/283441/12484494/de1d85d6-c05a-11e5-9988-3aa700833fbc.png">

**Comment by quocvu** [comment] 2016-01-22 21:05
Same here https://coveralls.io/github/quocvu/node_test_sample

**Comment by AMDmi3** [comment] 2016-01-25 13:48
Same here:

https://coveralls.io/github/libSDL2pp/libSDL2pp
https://coveralls.io/github/AMDmi3/streetmangler

Readme is named  README.md though, but the badge code was pasted as-is.

**Comment by alexmurray** [comment] 2016-01-29 02:18
+1 https://coveralls.io/github/alexmurray/cstyle

**Comment by timmahrt** [comment] 2016-01-29 15:38
Same here.
https://coveralls.io/github/timmahrt/praatIO?branch=master

Using the restructured text badge text as suggested by coveralls:

.. image:: https://coveralls.io/repos/github/timmahrt/praatIO/badge.svg?branch=master
    :target: https://coveralls.io/github/timmahrt/praatIO?branch=master

**Comment by randomdude999** [comment] 2016-01-30 20:49
Try putting that text into `README`, not `README.md` or `README.rst`. If it'll work, the code is just checking `README`, not `README.*` or `README.[complex glob pattern used by GitHub to determine readme file]`. That would be an easily fixable issue. If that fails, the issue becomes more complex.

Also, +1 https://github.com/randomdude999/xkcd
https://coveralls.io/github/randomdude999/xkcd

**Comment by RawToast** [comment] 2016-02-02 18:36
This isn't an issue caused by the readme file's extension. The author's repo has the badge in README.md and coveralls is showing no issues:

https://github.com/lemurheavy/vanity_slug 
https://coveralls.io/github/nickmerwin/vanity_slug

**Comment by quocvu** [comment] 2016-02-02 18:46
It does show the badge, but the status is stale. It takes a while to update itself.  When my build passed for the first time, it was still showing 'failed' for over 24h.

**Comment by apavlenko** [comment] 2016-02-03 12:11
+1 https://coveralls.io/github/apavlenko/vmf

**Comment by c58** [comment] 2016-02-04 08:12
+1. Yesterday all works fine!

**Comment by davidsowerby** [comment] 2016-02-05 12:01
+1 I don't think this is  a "stale" issue - I tried using README (without extension) and README.md, as suggested above, but Coveralls still reports "We detected this repo isn’t badged! "

This was a new addition to Coveralls, but I've tried a few that display the Coveralls badge, clicked through to coveralls, and each reports that the repo is not badged.
 
https://coveralls.io/github/davidsowerby/q3c-testUtil

**Comment by Skarlso** [comment] 2016-02-05 12:40
https://github.com/Skarlso/goprogressquest Here as well. The image is fine. Everything is setup nicely. It even updates after Github refreshes the images ( or if I bust Github's image cache ), but it still says that the tag could not be found in the README.

**Comment by nickmerwin** [comment] 2016-02-05 17:49
Hi all, we've just deployed a fix for this. Thank you for your patience and happy covering!!

**Closed by nickmerwin** 2016-02-05 17:49 UTC

**Comment by Skarlso** [comment] 2016-02-05 18:36
Yaay, works! Thanks! :+1:

**Comment by AMDmi3** [comment] 2016-02-05 19:45
Fix confirmed :+1:
