### ISSUE TITLE
Appveyor + gitlab repo: how to get a token?

### ISSUE THREAD

**Issue by nicolashainaux** [lemurheavy/coveralls-public#1458] opened 2020-06-30 16:06 UTC
Hello,

I could link coveralls to my gitlab repo but then I cannot access the settings (I get the "four oh four" page when I click on the repo; maybe because "there have been no builds for this repo" yet?), so I cannot get a token to setup in appveyor, hence cannot send the coverage data to coveralls etc.

I've tried using a personal token generated from my account's settings, but this did not work.

**Comment by afinetooth** [comment] 2020-07-20 23:59
hi @nicolashainaux,

you should always be able to access the repo token from the start page for a project that has had no builds yet.

something makes me think the issue is with your oauth access token. have you tried logging out of coveralls and making sure to log back in with your GITLAB login, as opposed to, perhaps, your GITHUB login?

if that doesn't resolve it, please email us at support@coveralls.io with the link to your coveralls repo and we'll look into it for you.

closing for now.

**Closed as completed** 2020-07-21 00:52 UTC
Labels: potential-bug
