### ISSUE TITLE
Coverage from multiple jobs no longer being merged into a single coverage metric

### ISSUE THREAD

**Issue by diophore** [lemurheavy/coveralls-public#943] opened 2017-03-21 23:35 UTC
As recent as a couple of days ago, this had been working fine. For no apparent reason, now our coverage metric just reflects the coverage of the last job that reported for a given build.

![image](https://cloud.githubusercontent.com/assets/1282833/24175605/1702fab2-0e65-11e7-8d0f-0d29751e612d.png)

**Comment by diophore** [comment] 2017-03-21 23:37
Actually, that's the first job, not the last job. Regardless, where it used to give a combined coverage metric (greater than the two individual job metrics) it now just reports the value from one of the jobs as the coverage for that build.

**Comment by aleneum** [comment] 2017-03-22 08:47
Same problem [here](https://coveralls.io/github/tyarkoni/transitions), we also face this 'Total Files: 0' issues as seen in @diophore's screenshot.

**Comment by michalwski** [comment] 2017-03-22 09:47
The same happens [here](https://coveralls.io/builds/10714826) also the list of files below all the jobs is no longer available.

The last working coverage in my case is [this one](https://coveralls.io/builds/10681829)

**Comment by mensinda** [comment] 2017-03-22 11:42
Same [here](https://coveralls.io/builds/10716717). Coverals shows no data in the metric, but our GCC build [clearly has data](https://coveralls.io/jobs/24098355).

**Comment by GAumala** [comment] 2017-03-23 08:59
I'm also having this issue [here](https://coveralls.io/builds/10733242) "No data available on table"

**Comment by efx** [comment] 2017-03-23 16:19
same in a private repository: 
<img width="554" alt="screen shot 2017-03-23 at 12 19 19 pm" src="https://cloud.githubusercontent.com/assets/472721/24258047/fab73e7c-0fc2-11e7-877f-ba8cdf4a7ba4.png">

**Comment by mcqueary** [comment] 2017-03-23 21:41
We're also  having the "No data available in table" problem, as discussed in #944

**Comment by nickmerwin** [comment] 2017-03-26 21:29
Hi all, this is fixed now, apologies for the confusion!

**Closed by nickmerwin** 2017-03-26 21:29 UTC

**Comment by aronisstav** [comment] 2018-04-05 10:33
I am experiencing this issue again:

https://coveralls.io/builds/16358545

Is there a regression?

**Comment by aronisstav** [comment] 2018-04-05 13:59
It appears to be the case that the "build is completed" webhook is activated by the first job that finishes, even though my scripts have not been configured to do that. I keep investigating...

**Comment by tamccall** [comment] 2019-12-03 07:15
also experiencing this https://coveralls.io/builds/27220129

**Comment by tflori** [comment] 2020-02-16 12:57
Is it old or up to date? Because I have the same problems.

The last working build was https://coveralls.io/builds/27817458

The most recent build: https://coveralls.io/builds/28758410
