### ISSUE TITLE
Couldn't find a repository matching this job.

### ISSUE THREAD

**Issue by techoner** [lemurheavy/coveralls-public#1268] opened 2019-02-19 11:15 UTC
$ $HOME/gopath/bin/goveralls -service=travis-ci
Bad response status from coveralls: 422
{"message":"Couldn't find a repository matching this job.","error":true}
The command "$HOME/gopath/bin/goveralls -service=travis-ci" exited with 1.

**Comment by MrSwitch** [comment] 2019-02-19 11:26
This has occurred for me since between 14 to 20 hours ago.

**Comment by MrSwitch** [comment] 2019-02-19 11:28
Duplicate of #1264

**Comment by nickmerwin** [comment] 2019-02-19 20:31
Hi @techoner, turned out we had our webserver IPs accidentally blacklisted by Travis, so we couldn't query their API to get job info as coverage data was posted.

Apologies for the gap in service here! We're adding failsafes to warn us early about this in the future.

**Closed by nickmerwin** 2019-02-19 20:31 UTC

**Comment by piyushpyoaknorth** [comment] 2019-11-18 14:01
Hi,
I am seeing this error too. It worked a couple of time, and then started failing with this error.

I tried

1) Re-synching the repositories
2) Added the .coverall.yml file

But still does not seem to resolve this issue.

This happens only when I give the path to base_directory, while using the python-coveralls library

**Comment by mohawk2** [comment] 2020-11-05 12:45
I am seeing this error from GitHub Actions (though not from Travis):
- working (Travis): https://travis-ci.org/github/eserte/graphviz-makefile/jobs/741617298
- not working (GH Actions): https://github.com/eserte/graphviz-makefile/runs/1358225162

On another repo (https://github.com/graphviz-perl/GraphViz2/runs/1350929974) I tried the advice in #1264 of deleting and reenabling on coveralls.io, which didn't help. Doing the coveralls update on my local machine, giving the correct token, worked.

Advise please?

**Comment by afinetooth** [comment] 2020-11-05 21:47
Hi @mohawk2, the Github Action is a little different. The Action provides an access token that we leverage instead of the repo_token. It's fine to add that, but the Action is looking for its token, which should be setup in your workflow file as follows:

> [...]
>     - name: Coveralls
>        uses: coverallsapp/github-action@master
>          with:
>            github-token: ${{ secrets.GITHUB_TOKEN }}
> [...]

Reference here:
https://github.com/marketplace/actions/coveralls-github-action#standard-example

It looks like you're setting `secrets.GITHUB_TOKEN` to the env var, but for the Action, the relevant parameter is `github-token`.

Hope that works for you.

**Comment by afinetooth** [comment] 2020-11-05 21:51
@mohawk2 On a second look, I realize you may be doing this without the use of the [Coveralls Github Action](https://github.com/marketplace/actions/coveralls-github-action).

In that case, you'll want to set the env var `COVERALLS_REPO_TOKEN` to the real repo_token from your project start page, rather than the github token. 

Try that and let us know.

**Comment by mohawk2** [comment] 2020-11-05 22:42
@afinetooth Thanks! I created a particular secret called `COVERALLS_TOKEN` per instructions in https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets with the repo token on the relevant coveralls.io page (https://coveralls.io/github/graphviz-perl/GraphViz2), then referenced it in my GH action. It now works.

I will feed this back to the author of the Perl Coveralls reporting module to update the docs.

However, the message is terrible because it's misleading. **PLEASE** get this switched so it says something that indicates "right repo, wrong auth". That's a lot of time I lost because someone was lazy with their error-reporting.

**Comment by mohawk2** [comment] 2020-11-08 16:48
Thanks to https://github.com/kan/coveralls-perl/pull/33 there is now working coverage-reporting for Perl with no need for making the Coveralls secret.
