### ISSUE TITLE
Files are listed multiple times in the report file tree

### ISSUE THREAD

**Issue by Ark-kun** [lemurheavy/coveralls-public#1362] opened 2019-10-09 20:21 UTC
https://coveralls.io/builds/26215569

**Comment by TimoRoth** [comment] 2019-10-10 10:17
We are having the exact same issue, ever since this build:
https://coveralls.io/builds/25946564

All our files are counted 8 times, blowing up our lines of code from ~9.5k to ~75k. It's pretty obvious that this is somehow related to parallel CI jobs, but our setup has worked fine before, and we are following all the documented steps for parallel jobs.

**Comment by alexmojaki** [comment] 2019-10-25 09:21
Based on https://docs.coveralls.io/parallel-build-webhook, `COVERALLS_PARALLEL=true` is necessary, but also

```yml
notifications:
  webhooks: https://coveralls.io/webhook
```

This is no longer enough:

```yml
after_success:
  - coveralls
```

See the fix applied here: https://github.com/gristlabs/asttokens/pull/44

**Comment by Zlender** [comment] 2019-11-13 17:00
We are seeing similar issue where Tree and file reports shows the same file repeated 8 times even though we don't use parallel runners. We use phpcov to merge 4 reports before we send one clover.xml file to coveralls.io

**Comment by A-312** [comment] 2020-01-07 21:50
https://docs.coveralls.io/parallel-build-webhook doesn't fix the problem. :(

![image](https://user-images.githubusercontent.com/18501150/71932406-154b3480-31a0-11ea-9fcd-59f6bd8305d3.png)

 - https://travis-ci.org/zestedesavoir/zds-site/jobs/633954858/config?utm_medium=notification&utm_source=github_status
 - https://coveralls.io/builds/27964564

**Comment by afinetooth** [comment] 2020-04-06 22:39
Checking the thread to see if this issue is still active for anyone.

@Ark-kun @TimoRoth @A-312  I checked the latest builds on each of your projects and see the file duplication issue has gone away in them. 

I'll close the issue for now. Please reply if the issue is still active and you want some follow-up. Thanks.

**Comment by A-312** [comment] 2020-04-07 06:12
@afinetooth Because I never merged my PR with [PARALLEL BUILDS WEBHOOK](https://docs.coveralls.io/parallel-build-webhook)

**Comment by A-312** [comment] 2020-04-07 07:27
Coveralls [didn't start](https://coveralls.io/repos/23025/builds), I thought [I did all the needed changes](https://github.com/zestedesavoir/zds-site/pull/5680/commits/c582b7422a75c53d4e4d5e04d8cfb39bde08a720). 😕

**Comment by afinetooth** [comment] 2020-04-08 23:23
@A-312 thanks. I'll relay to our core team and we'll get back asap.

**Comment by afinetooth** [comment] 2020-04-08 23:31
@A-312 thanks. I'll relay to core team and we'll get back asap.

**Comment by A-312** [comment] 2020-04-08 23:35
> Coveralls [didn't start](https://coveralls.io/repos/23025/builds), I thought [I did all the needed changes](https://github.com/zestedesavoir/zds-site/pull/5680/commits/c582b7422a75c53d4e4d5e04d8cfb39bde08a720). 😕

I think, I forgot to do something. 😕

**Comment by nickmerwin** [comment] 2020-04-09 02:14
Hi @A-312, we tracked the cause of the issue down to your `docs` job, which runs `coveralls` but doesn't include any files in the API post. That was preventing the build on our side from being considered done even though the webhook had arrived.

We've deployed an update to properly handle this contingency. Can you please run another build to confirm?

**Comment by A-312** [comment] 2020-04-09 02:22
Hi,

I asked travis to rerun : https://travis-ci.com/github/zestedesavoir/zds-site/builds/159196064

>  That was preventing the build on our side from being considered done even though the webhook had arrived.

If I understand, my Job "docs" run `coveralls` but should not because we do nothing, is not it ?

**Comment by nickmerwin** [comment] 2020-04-09 02:39
@A-312 sorry, could you run that once more, please? We needed to delete the existing build on Coveralls to get a new one to confirm.

**Comment by A-312** [comment] 2020-04-09 02:41
Done https://travis-ci.com/github/zestedesavoir/zds-site/builds/159196064

**Comment by nickmerwin** [comment] 2020-04-09 03:08
@A-312 thanks, confirmed the update solved this issue.

I identified another issue with your repo's owner on Coveralls, detailed here: https://github.com/zestedesavoir/zds-site/pull/5680#issuecomment-611301988

I'm closing the issue for now, but will monitor it if any more questions arise.

**Closed by nickmerwin** 2020-04-09 03:08 UTC
Labels: documentation, parallel-builds, potential-bug, set-up

**Comment by A-312** [comment] 2020-04-09 08:37
> @A-312 thanks, confirmed the update solved this issue.

Also thanks, for your work
