### ISSUE TITLE
Coveralls bot is not commenting and commit messages are in HTML?

### ISSUE THREAD

**Issue by MichaelAkvo** [lemurheavy/coveralls-public#1609] opened 2022-01-05 09:16 UTC
Hi,

On a branch https://coveralls.io/github/akvo/akvo-rsr?branch=feature/4710-Improve-project-hierarchies that has a PR ( https://github.com/akvo/akvo-rsr/pull/4731 ), the bot isn't commenting despite being a collaborator

![image](https://user-images.githubusercontent.com/91939214/148188539-d793967a-c1df-4311-8ad5-fc17f0edc33f.png)

Additionally, the commit messages show on coverall.io really aren't the actual commit messages. Example

https://coveralls.io/builds/45384485
![image](https://user-images.githubusercontent.com/91939214/148188866-94bbbac0-1260-4341-9c71-a350c72c82ec.png)

Maybe the source of all of this is that coveralls isn't pointing to the right commit. The aforementioned build points to "bccee411 on github" --> https://github.com/akvo/akvo-rsr/commit/bccee411b572f0cc0f287269ad989984b7ef7ac0

![image](https://user-images.githubusercontent.com/91939214/148190928-ac7e2023-7edb-4bb4-86f9-6b6dec061697.png)

Maybe I'm missing the coveralls job logs, so I can't see what's wrong.

# Our setup

We use Semaphore CI:

 - [semaphore.yml](https://github.com/akvo/akvo-rsr/blob/9d0a2a39b0f948ffb94cae2687bd20e2b53065d0/.semaphore/semaphore.yml#L27)
 - [script calling docker-compose](https://github.com/akvo/akvo-rsr/blob/9d0a2a39b0f948ffb94cae2687bd20e2b53065d0/ci/build-semaphoreci.sh#L51)
 - [docker-compose with the variables being passed](https://github.com/akvo/akvo-rsr/blob/9d0a2a39b0f948ffb94cae2687bd20e2b53065d0/docker-compose.ci.yaml#L16)
 - [coveralls being called in the docker container](https://github.com/akvo/akvo-rsr/blob/9d0a2a39b0f948ffb94cae2687bd20e2b53065d0/scripts/docker/ci/build.sh#L55)

**Comment by afinetooth** [comment] 2022-01-05 20:52
Hi @MichaelAkvo. Per our email exchange about this, but also for readers with similar issues:

> On a branch https://coveralls.io/github/akvo/akvo-rsr?branch=feature/4710-Improve-project-hierarchies that has a PR ( akvo/akvo-rsr#4731 ), the bot isn't commenting despite being a collaborator

The cause of no PR comments here:
https://coveralls.io/github/akvo/akvo-rsr?branch=feature/4710-Improve-project-hierarchies

Is that coveralls never received any **pull_request** type builds on that branch:
https://coveralls.io/github/akvo/akvo-rsr?branch=feature/4710-Improve-project-hierarchies

![Screen Shot 2022-01-05 at 12 20 58 PM](https://user-images.githubusercontent.com/918667/148285371-1cc1f237-6627-49e9-b744-75134c2ac080.png)

Of six (6) builds on that branch, all are type **push**:

```
> repo.builds.where(branch: "feature/4710-Improve-project-hierarchies").map(&:service_event_type)
=> ["push", "push", "push", "push", "push", "push"]
```
 
Coveralls will only send PR comments for builds of type **pull_request**. 

You will need to make sure your **pull_request** builds are getting declared as such in your CI configuration. 

Specifically, to identify a build as type **pull_request**, the [Coveralls API](https://docs.coveralls.io/api-reference) is looking for a non-null value for the [service_pull_request](https://docs.coveralls.io/api-reference) param.

If you're not sure how to ensure that's happening, let me know. 

---

> Additionally, the commit messages show on coverall.io really aren't the actual commit messages. Example
> https://coveralls.io/builds/45384485

This can be a tough one to resolve. It happens for different reasons on different combinations of build OS, runner OS, etc.

The best way to start fixing it for your instance will be to enable [verbose mode](https://docs.coveralls.io/troubleshooting#put-it-in-verbose--v) on your integration and observe your verbose build log to see exactly where and when the value is being set for the param, [git[id[message]]](https://docs.coveralls.io/api-reference).

The way to enable [verbose mode](https://docs.coveralls.io/troubleshooting#put-it-in-verbose--v) varies by integration. Assuming you're using [coveralls-python](https://github.com/TheKevJames/coveralls-python), you'll want to invoke the `coveralls` command in `debug` mode (`coveralls debug`) per the [docs](https://coveralls-python.readthedocs.io/en/latest/troubleshooting.html?highlight=debug#troubleshooting).

---

> Maybe the source of all of this is that coveralls isn't pointing to the right commit. The aforementioned build points to "bccee411 on github" --> https://github.com/akvo/akvo-rsr/commit/bccee411b572f0cc0f287269ad989984b7ef7ac0

That is possible, but the first issue with [that build](https://coveralls.io/builds/45384485) is that it hasn't been declared a **pull_request** as far as coveralls is concerned.

I'm not convinced ephemeral commits is your issue right now. When that happens you typically don't get a value for branch name in the UI. Before examining that angle, I'd like to see where you get after modifying your CI config so coveralls recognizes your PR builds as **pull_request** builds. (See above.)

---

> Maybe I'm missing the coveralls job logs, so I can't see what's wrong.

Examining your verbose build logs are always the best place to start when troubleshooting issues with a coveralls build. 

See above for how to enable [verbose mode](https://docs.coveralls.io/troubleshooting#put-it-in-verbose--v) for your integration. If you're using another integration, check their docs or let me know and we'll try to find it together.

---

> # Our setup
> We use Semaphore CI:
> 
>  - [semaphore.yml](https://github.com/akvo/akvo-rsr/blob/9d0a2a39b0f948ffb94cae2687bd20e2b53065d0/.semaphore/semaphore.yml#L27)
>  - [script calling docker-compose](https://github.com/akvo/akvo-rsr/blob/9d0a2a39b0f948ffb94cae2687bd20e2b53065d0/ci/build-semaphoreci.sh#L51)
>  - [docker-compose with the variables being passed](https://github.com/akvo/akvo-rsr/blob/9d0a2a39b0f948ffb94cae2687bd20e2b53065d0/docker-compose.ci.yaml#L16)
>  - [coveralls being called in the docker container](https://github.com/akvo/akvo-rsr/blob/9d0a2a39b0f948ffb94cae2687bd20e2b53065d0/scripts/docker/ci/build.sh#L55)

**Recommendations**:

- Verify correct settings for semaphore in [coveralls-python docs here](https://github.com/TheKevJames/coveralls-python/blob/2610885ab254a0d58277275fc58c415ecca47708/docs/usage/tox.rst#semaphoreci) and mind ["Classic" vs "2.0"](https://github.com/TheKevJames/coveralls-python/blob/48f0ac034b25564145f4ae89f3646f68ac5252a9/coveralls/api.py#L132-L145). More background in the [change log](https://github.com/TheKevJames/coveralls-python/blob/c35bf51671a9608b6b5610e61a1510bf1924882c/CHANGELOG.md#bug-fixes-4).
- Invoke [coveralls-python](https://github.com/TheKevJames/coveralls-python) in `debug` mode, with `coveralls debug`, [here](https://github.com/akvo/akvo-rsr/blob/9d0a2a39b0f948ffb94cae2687bd20e2b53065d0/scripts/docker/ci/build.sh#L55).

**Comment by MichaelAkvo** [comment] 2022-01-06 16:12
Thanks for the in-depth response @afinetooth . It looks like simply passing the `SEMAPHORE_*` env vars fixed the problem with coveralls bot not comments. `coveralls-python` uses them successfully.

I have no idea why the commit message was so messed up. I'll run `coverall-python` in debug mode when I have the time and dump the results here. Hopefully, it'll help.

**Comment by afinetooth** [comment] 2022-01-06 19:43
Hi, @MichaelAkvo. Great. Glad to hear it.

Yes, let me know about the comments. We can keep that open until that part's resolved.

**Comment by MichaelAkvo** [comment] 2022-01-12 16:25
I'm not able to trigger the issue anymore :shrug: and will stop trying. Not sure if you want to leave this open @afinetooth and maybe someone else will run into the issue.

Thanks for you the quick responses nonetheless!

**Comment by afinetooth** [comment] 2022-01-12 20:40
Thanks, @MichaelAkvo. I'll close it but it will be hear for anyone searching for similar patterns.

**Closed as completed by afinetooth** 2022-01-12 20:40 UTC
Labels: set-up, python, troubleshooting, no-pr-comments
