### ISSUE TITLE
Use Github Commit Status API

### ISSUE THREAD

**Issue by saulshanabrook** [lemurheavy/coveralls-public#25] opened 2013-03-27 03:23 UTC
https://github.com/blog/1227-commit-status-api

http://developer.github.com/v3/repos/statuses/

Comments can get annoying...

**Comment by MikaelSmith** [comment] 2015-01-25 23:00
:+1:

I've tried to create a status webhook at https://github.com/mikaelsmith/coveralls-status-hook, however the webhook doesn't seem to pass along enough information to find the relevant pull request. If anyone has a suggestion how to do that, please add an Issue to my project (so as not to derail this too much).

An example of the ![coveralls webhook](https://cloud.githubusercontent.com/assets/8162496/5893674/3c2b354a-a4a2-11e4-9715-7131cf57591b.png) from https://github.com/puppetlabs/cfacter/pull/271.

**Comment by laedit** [comment] 2015-02-01 08:56
:+1:

**Comment by clark800** [comment] 2015-02-02 19:58
:+1:

**Comment by nickmerwin** [comment] 2015-02-02 20:46
Hi all, I've this feature is now live!

There's a new setting here (it's on by default):

![image](https://cloud.githubusercontent.com/assets/1129/6008797/3169d322-aad9-11e4-9058-c0f3f3e51f8d.png)

Now you'll see this on your PR's:
![image](https://cloud.githubusercontent.com/assets/1129/6008805/48250dfc-aad9-11e4-9fd5-3a7db9463a7a.png)

If the coverage decreases, the status will be "failure".

I'm closing this thread for now, but please keep the convo going. Thanks everyone!

**Closed by nickmerwin** 2015-02-02 20:46 UTC

**Comment by Silox** [comment] 2015-02-02 21:04
Awesome feature! I however cannot seem to find the Github options under the "Notication" panel: 
![screen shot 2015-02-02 at 22 02 18](https://cloud.githubusercontent.com/assets/915130/6009126/3b9ce3cc-ab27-11e4-9125-caf252a4cd26.png)

Am I looking in the wrong place?

**Comment by MikaelSmith** [comment] 2015-02-02 21:05
Yes, it's at the bottom of the builds page under "Settings".

**Comment by nickmerwin** [comment] 2015-02-02 21:06
hi @Silox, the setting is on your repo page and is only visible to the user that added the repo to Coveralls.

**Comment by Silox** [comment] 2015-02-02 21:07
Awesome, found it. Thank you! :+1: for this addition!

**Comment by GrahamCampbell** [comment] 2015-02-02 21:19
Ping @keradus. This is live now.

**Comment by jasonmp85** [comment] 2015-02-02 21:36
If the coverage decreases, the status will be "failure".

So there can be literally _no_ regression in coverage? Not even 0.01%? Or is there some user-defined threshold?

**Comment by nickmerwin** [comment] 2015-02-02 21:39
@jasonmp85 if the PR includes un-tested lines of code, shouldn't it raise a red flag?

Seems like the PR status is just a barometer; you can still use the auto-merge button, having a failure status won't prevent you from merging.

**Comment by jasonmp85** [comment] 2015-02-02 21:44
@nickmerwin ideally, yes. In practice I'm writing a PostgreSQL extension in C and sometimes I handle errors that are _very_ difficult to reliably reproduce in their regression test environment, which is pretty black-box. So some lines of error handling may work out to basically be sanity checks that you'd _never_ expect to be triggered (and indeed probably can't trigger without a totally ruined DB), but need to be there to make sure the world is sane.

But I see the argument and it makes sense. Allowing even 0.01% regression means you can slowly dip into "bad" territory over time (boiling frog analogy, etc.). I know the merge button is only advisory, but I'll accept this behavior to push me to prevent regressions.

**Comment by nickmerwin** [comment] 2015-02-02 21:54
@jasonmp85 I like the analogy. Also "0.01%" or any seemingly small percentage might not be the right metric since in a code base of 100K relevant lines that'd still be 10 lines of potentially bug ridden code. 

Maybe we should specify the actual line #'s also, e.g.:

```Coverage decreased (X%) to Y% with Z new missed lines.```

**Comment by keradus** [comment] 2015-02-03 07:40
No need for pinging @GrahamCampbell ;)

**Comment by peternewman** [comment] 2015-02-04 00:17
@nickmerwin I appreciate what you're saying about never decreasing coverage, however we use protobufs and I suspect it must be that (or bison or other bits we use elsewhere), but our coverage can end up going up or down even if all that's been changed are text files, e.g. https://github.com/OpenLightingProject/ola/pull/610 or https://github.com/OpenLightingProject/ola/pull/555 which will mean we'll get false positives if we can't set a threshold. I know we can ignore it, but then you're into the boy who cried wolf territory.

**Comment by jasonmp85** [comment] 2015-02-04 00:20
You're measuring coverage on generated code? Kinda weird, IMO…

**Comment by jasonmp85** [comment] 2015-02-05 07:46
@nickmerwin I'm not seeing this on my project… For instance, citusdata/pg_shard#72 was just pushed. It moves around just a few SQL files, so the coverage remained the same. I see the comment, but not the status. What's up?

**Comment by peternewman** [comment] 2015-02-06 14:15
@jasonmp85 same here, I turned off the comments and no change. I've just tried turning off both sets, saving and re-enabling, so will see if that fixes it somehow.

Regarding coverage of generated code, I see your point, TBH we had the tests already, I just gathered the test data and pushed it to coveralls. However given breaking the generated code will break the program, surely we want to confirm the tests cover the generated code well too, hence wanting good coverage?

**Comment by nickmerwin** [comment] 2015-02-06 19:00
@jasonmp85 looking into that now; the GH API is returning a 404 error when attempting to create a status on that PR.

**Comment by jasonmp85** [comment] 2015-02-06 19:05
@peternewman I'm just saying that _coverage_ of generated code is irrelevant. Your tests should still fail if it breaks, which means the build will fail independent of Coveralls. I use protobufs for another project and don't know what dead code will be in the files it generates, so can't trust on instrumenting it for coverage… But if it breaks, the build will fail, so I'm OK.

@nickmerwin There are a lot of people participating in this issue… should I open a new one, or take this to email, or?

Tried to figure out what other support options existed but don't feel like making a ZenDesk password or whatever.

**Comment by nickmerwin** [comment] 2015-02-06 19:07
@jasonmp85 ok I figured it out -- the public oauth scope Coveralls has always asked for doesn't include the ability to write commit statuses; now it does.

Could you log out then log back in?

**Comment by jasonmp85** [comment] 2015-02-06 21:20
That fixed it. The org needed that one extra permission, though it now also asked for essentially everything against my personal user. You guys should see whether that's a regression or something, but otherwise it's working great.

**Comment by peternewman** [comment] 2015-02-07 14:33
@nickmerwin that fixed it for me too, it only asked for the commit status permission for me @jasonmp85 .

The change has raised one issue though @nickmerwin . Is there an API function within Coveralls to tell it to tell GitHub that it's getting ready to generate some coverage stats? FWIW we use https://github.com/eddyxu/cpp-coveralls . It sort of looks like the parallel build stuff may be relevant. Anyway, our current timeline is something like this:
Push to existing PR
Travis starts
PR reports Travis pending
Bulk of Travis finishes (we have coverage set to allowed failure as coverage is really just of interest to us, not crucial, it being a project with hardware, it can be harder to effectively test all coverage)
PR reports okay (Travis only)
Coverage finishes generating (it takes slightly longer than the standard make check)
Coverage calls into Coveralls
PR reports pending (Travis okay, Coveralls pending)
Coveralls calculates coverage
PR reports complete (Travis okay, Coveralls hopefully okay)

So in an ideal world, it would be great to have a Coveralls API, so at the start of the Travis coverage job, it calls into there, which then calls into GitHub to say Coveralls pending, which will only leave it slightly out of sync with Travis, and reduce the chance of builds having that confusing grey area where Travis is green, and Coveralls isn't listed as pending.

@jasonmp85 I take on board what your saying, and we're going to exclude the generated code from coverage, but playing devils advocate, if you don't have coverage of your generated code, how do you know if the tests are covering the bits you use and hence will fail if it breaks?

**Comment by nickmerwin** [comment] 2015-02-09 17:47
@peternewman yes! cpp-coveralls will need to be updated to support the ```parallel``` option in the API post to Coveralls. That notifies us that we should wait until we receive a webhook to consider a build "done".

More info re: webhook here: https://coveralls.zendesk.com/hc/en-us/articles/203484329

**Comment by nickmerwin** [comment] 2015-02-09 18:13
@jasonmp85 did it ask for private repo read/write access? I've seen a similar report and it's odd because we've only added the request for "commit:status" to our OAuth scopes. Looking for clues. Thanks!

**Comment by peternewman** [comment] 2015-02-10 00:16
Thanks @nickmerwin so the parallel option is the right choice and will achieve what I'm asking for even if we aren't interested in an actual parallel build?

**Comment by nickmerwin** [comment] 2015-02-10 01:46
@peternewman I'm assuming so yes, but would love to hear what you find testing out that flow. Keep me posted, thanks!

**Comment by jasonmp85** [comment] 2015-02-10 04:17
It asked for *everything*. Not for my org (that just showed a dialog asking
for "modified access", i.e. just adding commit status), but for me. I was
kicked out and logged back in and it had a GitHub interstitial asking for
full access. Can't remember whether Coveralls had a public/private option
like many services or if it's all or nothing.

Honestly I avoided doing anything about it for a few hours before
eventually saying "screw it all my code's open source or org-owned anyhow"
and hit OK. But it never stopped asking for the full set of permissions.

—Jason
