### ISSUE TITLE
Branch is only displaying master and badge does not update

### ISSUE THREAD

**Issue by ddold** [lemurheavy/coveralls-public#1594] opened 2021-11-11 17:00 UTC
Testing out Coveralls with a private repo I am noticing some inconsistencies. 
First off the build number was a uid, but turns out that was the value sent from the CircleCI orb and I have a [fix](https://github.com/coverallsapp/orb/pull/15) for that.
But on the main build page it states that I am on the master branch, and when I click on the branches dropdown and try to sync, it spins forever. Also the coverage badge shows as unknown!

My repo is private, so wont be able to share that. The language is Node and I am using [nyc](https://github.com/istanbuljs/nyc) to get the test coverage in lcov format. The CI tool used is CircleCI and I am using the [Coveralls orb](https://circleci.com/developer/orbs/orb/coveralls/coveralls#orb-source) to send the data to Coveralls. The code is stored in a Github repository

![Screenshot 2021-11-11 at 16 50 58](https://user-images.githubusercontent.com/13778631/141337115-cf76799a-a111-4511-a60f-d9307c16aa62.png)
As you can see it shows the last build branch being test_coverage (which is correct). It is very small and on the top left of the screenshot. Everywhere else there is a mention to a branch and it is referencing master

In my config for CircleCI I have the following bits;
```
- coveralls/upload:
          parallel: true
          flag_name: Unit Tests
          verbose: true
...
- coveralls/upload:
          parallel: true
          flag_name: Integration Tests
          verbose: true
...
code-coverage-complete:
    docker:
      - image: circleci/node:14.18.1
    steps:
      - coveralls/upload:
          parallel_finished: true
```

I see there is [coveralls-node](https://github.com/nickmerwin/node-coveralls) lib, is that sending the information through the code and not the CI tool. I haven't tried this but think doing it through CI would be better.

**Comment by afinetooth** [comment] 2021-11-12 23:56
Hi @ddold. 

Strongly agree that `CIRCLE_BUILD_NUM` works better as build number than `CIRCLE_WORKFLOW_ID`. To complete your PR we'd need to make an accompanying change to [node-coveralls here](https://github.com/nickmerwin/node-coveralls/blob/21f7b1da017e1b2386b4354a0d8345937294fd26/lib/getOptions.js#L57-L58) to make the integration pass `CIRCLE_BUILD_NUM` for `service_number`. However, [those lines](https://github.com/nickmerwin/node-coveralls/blob/21f7b1da017e1b2386b4354a0d8345937294fd26/lib/getOptions.js#L57-L58) indicate it's currently being used for `service_job_number`, with which I'm not personally familiar because it's not spec in the [Coveralls API Reference](https://docs.coveralls.io/api-reference). I assume that's an accommodation for some factor related to CircleCI, so best to submit a PR there and let the original developers sort that out. 

You sussed that out correctly, though: the [Coveralls CircleCI Orb](https://github.com/coverallsapp/orb) uses [node-coveralls](https://github.com/nickmerwin/node-coveralls) under-the-hood. [node-coveralls](https://github.com/nickmerwin/node-coveralls) is also the basis of the [Coveralls Github Action](https://github.com/coverallsapp/github-action). I think the goal is to ease maintenance of the particular, official CI tools (Actions, Orbs), those essentially being adapters to a single integration.

Assuming I have the right project (I won't paste the Coveralls URL here since your repo is private, not that anyone but you and your collaborators would be able to see it), the reason your badge reads `unknown` is because you have no builds on your default branch (**master**) in your build history:

![Screen Shot 2021-11-12 at 3 12 16 PM](https://user-images.githubusercontent.com/918667/141593985-4ce2aa4b-2986-4cdc-9073-d128061c21d4.png)

Your badge coverage is intended to represent coverage in the "production" instance of your code, so it's tied to your default branch (**master** in your case).

In addition to that, in order to receive PR comments you'll also need to submit some builds on master because the contents of a PR comment is a comparison between a **pull_request** commit and its **base commit**, which lives on a branch to which the PR will be merged, which is typically your default branch.

I'm assuming you've already configured your CI to build both **pull_request** and **push** type builds (on **master** specifically) and that you just haven't merged your setup branch into **master** yet.

That's very common and in that case, once you proceed to merge your setup branch into **master**, build the new commit in CI and send its coverage report to coveralls, you'll:

1. Start seeing coverage % in your badge
2. Start receiving PR comments in your PRs at Github.

**Comment by ddold** [comment] 2021-11-15 16:27
Hi @afinetooth,

Thanks for your detailed response on this. I opened an issue [here](https://github.com/nickmerwin/node-coveralls/issues/323) in the node-coveralls app to address that issue!

Yes you found the right repo and I just merged my test branch to master and now the badge shows the test percentage, great 👍 

The only other issue I am seeing now is the fetching of the branches. This seems to go on forever. I found [this](https://github.com/lemurheavy/coveralls-public/issues/1581) past issue and read through it. On my dev console I can see the call to `sync_branches.json` returns 500. Reading about your comments saying it could be a CI issue, I turned on verbose logging and can see that CircleCI includes the branch name in the requests

![Screenshot 2021-11-15 at 16 10 39](https://user-images.githubusercontent.com/13778631/141817821-11207057-0687-43dc-95a5-0aa2e03a47fe.png)
![Screenshot 2021-11-15 at 16 13 14](https://user-images.githubusercontent.com/13778631/141817826-25782d24-abd5-45db-af33-7892cdef4279.png)

With the CI sending the branch name, I am not sure what else is wrong and why the branches don't show up on the account?

**Comment by afinetooth** [comment] 2021-11-15 21:01
Hi @ddold.

Thanks for creating that [issue](https://github.com/nickmerwin/node-coveralls/issues/323) and including a reference to the [code](https://github.com/nickmerwin/node-coveralls/blob/21f7b1da017e1b2386b4354a0d8345937294fd26/lib/getOptions.js#L57-L58).

So I was able to reproduce the issue with the sync branches button. It's a bug. I submitted the issue and will feedback with any updates here.

**Closed as completed** 2023-05-22 00:02 UTC
Labels: marked-for-closure, set-up, circle-ci, badge-issues
