### ISSUE TITLE
"run details" say coverage has dropped, but can't see any uncovered lines in the report

### ISSUE THREAD

**Issue by cjw296** [lemurheavy/coveralls-public#1133] opened 2018-05-29 07:13 UTC
Here's the coveralls url: https://coveralls.io/builds/17206674

So, it says:
```
117 of 122 new or added lines in 6 files covered. (95.9%)

1 existing line in 1 file now uncovered.
549 of 555 relevant lines covered (98.92%)
```

...but I can't find any uncovered lines when looking in the "SOURCE FILES ON BUILD 588" and the "NEW MISSED LINES IN DIFF" and "UNCOVERED EXISTING LINES" sections both appear to report that there are no uncovered lines.

Can you walk me through your UI and what I'm missing?

**Comment by bytewalls** [comment] 2018-05-31 15:59
@cjw296,

Sorry for the delayed response. It looks like the issue here is likely caused by having parallel builds, but not using our parallel webhook infrastructure, which tells us that all of your tests are finished being run.

[Here is some documentation](http://docs.coveralls.io/parallel-build-webhook) that should help with setting that up, please let us know if this doesn't solve your problem.

**Comment by cjw296** [comment] 2018-05-31 17:36
Thanks, that seems to have helped a lot...

**Comment by cjw296** [comment] 2018-05-31 17:47
@bytewalls: hasn't helped: https://coveralls.io/builds/17256254

Here's the commit:

https://github.com/Simplistix/mailinglogger/commit/3efe69c461cd7f321012ff4f534d78b966e73993

Here's the submission from one of the two parallel runs: 

https://travis-ci.org/Simplistix/mailinglogger/jobs/386287765#L501

**Comment by cjw296** [comment] 2018-06-07 06:56
Here's another example: https://coveralls.io/builds/17365305

**Comment by bytewalls** [comment] 2018-06-07 16:07
Thanks, sorry about the frustrating intermitant issues, we are looking into this and will work on getting a fix out soon.

**Comment by cjw296** [comment] 2018-06-07 16:21
It would be great if there was an api endpoint *I* could poke, say at the start of the 'coverage' step in the travis jobs linked to the above, to say "no really, I've sent you all the coverage info, now please block until you've done your calcs".

**Comment by cjw296** [comment] 2018-06-14 20:18
Same again: https://coveralls.io/builds/17499686. Weird that it appears to be just this repo that has problems, while another repo of mine has a similar parallel structure and has been fine: https://coveralls.io/builds/17499343

**Comment by cjw296** [comment] 2018-06-15 05:55
I tried deleting the repo and re-creating on coveralls.io, no improvement: https://coveralls.io/builds/17506737

Anyone have a chance to look at this?!

**Comment by cjw296** [comment] 2018-06-15 06:57
I tried the parrallel builds webhook, as you can see, it hasn't helped:

https://travis-ci.org/cjw296/shoehorn/jobs/392585401

**Comment by bytewalls** [comment] 2018-06-15 20:38
@cjw296,

We are working on a fix for this issue.

**Comment by cjw296** [comment] 2018-06-16 16:27
What's the ETA for that fix?

**Comment by cjw296** [comment] 2018-06-16 19:57
This project has now started exhibiting this behaviour as well: https://coveralls.io/builds/17532129

**Comment by bytewalls** [comment] 2018-06-26 18:35
@cjw296 this issue was resolved, you will need to add in the webhook to make sure that the builds are marked as completed. 

The webhook does exactly what you said previously, marking the builds as parallel blocks computation until all builds are received and using the webhook notifies coveralls that we have received all data and can process it.

**Closed by bytewalls** 2018-06-26 18:35 UTC

**Comment by mmoayyed** [comment] 2018-06-26 18:45
Apologies if this is not the right forum to ask: does the webhook also work with Travis CI and their Build Stages? If not, is there a recommended recipe there? (I can certainly create a different issue if that is preferred)

Example:
https://travis-ci.org/apereo/cas/builds/397004259

Each job in a build stage might be configured to run a specific sort of integration test (memcached, redis, etc) and it would be ideal to capture results from all tests from all jobs from all stages for an aggregated view.

**Comment by cjw296** [comment] 2018-06-27 02:55
@bytewalls - what's the recommended way of wiring in the webhook on a TravisCI job that's using Build Stages?

**Comment by bytewalls** [comment] 2018-06-27 23:10
I believe you should be able to use the travis-ci webhook outlined here: https://docs.coveralls.io/parallel-build-webhook with or without build stages.

**Comment by mmoayyed** [comment] 2018-08-07 20:20
I am not sure that is quite working then. Here is a `.travis.yml` file:
https://github.com/apereo/cas/blob/master/.travis.yml

- The `COVERALLS_REPO_TOKEN` variable is defined as an encrypted environment variable
- Notifications webhook is also defined as an encrypted URL
- The Travis CI jobs run in multiple stages with parallel jobs. [This is a recent example](https://travis-ci.org/apereo/cas/builds/412122690)
- The coverage percentage however has and continues to remain at 63%: https://coveralls.io/github/apereo/cas?branch=master

Might I have missed something?
