### ISSUE TITLE
Coverall isn't sending report back

### ISSUE THREAD

**Issue by siwan90** [lemurheavy/coveralls-public#1130] opened 2018-05-25 05:31 UTC
For past couple days, coveralls sometimes isn't sending report status.

**Comment by valendesigns** [comment] 2018-05-25 07:59
+1 having the same issue. Travis is showing that the job was created, but strangely the job is missing all the coverage data and the PR on GitHub never updates the status.
```
Dump submitting json file: /tmp/wordpress/src/wp-content/plugins/tide-api/build/logs/coveralls-upload.json
File size: 166.02 kB
Submitting to https://coveralls.io/api/v1/jobs
Finish submitting. status: 200 OK
Accepted Job #235.1
You can see the build on https://coveralls.io/jobs/36851536
```

**Comment by VPM-DavidM** [comment] 2018-05-25 08:43
+1 experiencing the same issue since yesterday.

Thought it might be related to http://status.coveralls.io/incidents/5hqrzr0y77qh but it's marked as fixed now and I've experienced the issue since then.

**Comment by rpoet-ds** [comment] 2018-05-25 13:28
+1 have the same issue.  Builds submitted after 12:00AM EDT today have not received coverage status.

**Comment by Qwerios** [comment] 2018-05-25 14:29
Appear to be having same issue. No coveralls status being reported for pull requests. Have to disable the check for now #sadpanda

**Comment by bytewalls** [comment] 2018-05-25 16:44
We are aware of this issue, and are investigating it sorry for the inconvenience. Sorry for the inconvenience.

**Comment by yurifds** [comment] 2018-05-25 19:20
I'm having a similar issue. The job is pending a lot of time. Link: https://coveralls.io/builds/17169112. Apparently, the Travis send the coverage data correctly via API.

**Closed** 2018-05-28 16:21 UTC

**Comment by scniro** [comment] 2018-06-05 19:30
@bytewalls This issue seems to be back. Can you share some background on what the cause to this was? I'm integrating coveralls into a new repo and troubleshooting is a challenge now knowing there was a very recent issue.

**Comment by scniro** [comment] 2018-06-06 13:30
@bytewalls seemingly fixed this morning 🤷‍♂️

**Comment by JamesBradbury** [comment] 2018-09-20 08:45
@bytewalls I'm experiencing this issue today. Coveralls seems to have completed the work, but not reported back to GitHub even 17 hours later. I've tried the "Resync with GitHub" button, but it doesn't seem to help. I guess I'll have to turn coveralls off for now.

**Comment by c-bik** [comment] 2019-09-05 14:38
About an year later, same issue!

**Comment by rajaanova** [comment] 2019-10-24 15:33
i am also facing the same issue, same config/script works for one repo and for the other repo its not working, facing this issue for last 20 days or so.

**Comment by hsethi1** [comment] 2020-04-24 06:32
Same issue is happening for couple of months. Tried closing/re-opening the PR, regenerated a new coveralls token and used that with the project. No use. I guess one of the things remaining to be tried is to delete the coveralls project linking with GitHub and maybe trying again. But with this, I believe all the previous coveralls data related to this project would be lost.
