### ISSUE TITLE
Coverage increase / decrease incorrect for pull requests

### ISSUE THREAD

**Issue by lbergelson** [lemurheavy/coveralls-public#463] opened 2015-02-17 18:11 UTC
Hi,

I've noticed that the arrow for coverage increase / decrease seems to be wrong for commits generated during pull requests, and for pull request merge commits.  It looks to me that all pull requests/ merge commits into master are lumped together and the most recent one is used as the standard of coverage. 

Example: 

![screen shot 2015-02-17 at 12 42 36 pm](https://cloud.githubusercontent.com/assets/4700332/6233720/f1700d9c-b6a2-11e4-99b0-cc11afcae14b.png)

Build 344 is the most recent commit to master, the commit prior to that was 335 ,coverage in 344 is 64% and int 335 it was 63%.   However, it says that coverage decreased with that commit.  I think it's because there is a build off of a pull request which increases the coverage to 69%.  This isn't actually committed to master though, so it should still register 344 as increasing coverage.  

It needs to differentiate between un-merged pull request builds on a branch and pushes to the branch which it doesn't seem to do currently.

![tree](https://cloud.githubusercontent.com/assets/4700332/6234111/1cbeea9c-b6a6-11e4-8963-11aa9b24fdaa.png)

**Comment by lbergelson** [comment] 2015-02-17 18:12
I forgot to include the repo, it's the private repo: 

https://github.com/broadinstitute/hellbender

**Comment by GeorgeJahad** [comment] 2015-02-21 01:53
I think we, (the Blueflood team,) may be running into the same problem.

It seems like the coverage algorithm is sometimes using the wrong base commit when calculating the change in coverage.  Here is an example:

In our pull request here:

https://github.com/rackerlabs/blueflood/pull/421

We had two commits with two coveralls reports, the first seems correct, the second wrong.

The first commit shows this report:
Coverage increased (+0.04%) to 29.28% when pulling b7bae55 on tilogaat:numeric-datatype into a8ac5e2 on rackerlabs:master, 

which corresponds to this coveralls build:  https://coveralls.io/builds/1783661

When we added another small commit to the same PR, we got a huge, (incorrect,) jump in coverage, like so:

Coverage increased (+23.87%) to 53.11% when pulling 68a6c98 on tilogaat:numeric-datatype into a8ac5e2 on rackerlabs:master.

which corresponds to this: https://coveralls.io/builds/1822610

Note that both messages refer to the same base commit, a8ac5e2.  

If you go to the first coveralls build page: https://coveralls.io/builds/1783661

and follow the link at commit message, it takes you here: 
https://github.com/rackerlabs/blueflood/commit/9bbe435d57f0134f9ee13254071fab3fd850c622
which is a merge of the same two commits in the "Coverage increased" message, with the base being a8ac5e2

If you do the same thing in the other coveralls build, https://coveralls.io/builds/1822610 it leads you to this github page, 
https://github.com/rackerlabs/blueflood/commit/888c7cf6445eda659fb7272df2ee713df64c06bb

which shows the base commit being 742cd95, not a8ac5e2.  And I think that is wrong.  All of the coverage tests in the PR should be based on a8ac5e2, but I think the second commits coverage value is wrong because the calculations for the second commit are based on wrong base commit, 742cd95.

Please let me know what you think.

Thanks much for a very nice service!

**Comment by nickmerwin** [comment] 2015-02-22 19:54
Thank you very much @lbergelson and @GeorgeJahad for identifying that regression and taking the time to add screenshots, evidence, etc. It was very helpful! The issue is fixed now and coverage changes should only be calculated off of push event builds as opposed to PRs. 

Could you point me to any builds you'd like to have re-processed to reflect this fix?

Thank you!

**Closed by nickmerwin** 2015-02-22 19:54 UTC

**Comment by lbergelson** [comment] 2015-02-23 15:48
@nickmerwin Thanks for solving the problem!  No need to reprocess any past builds.

**Comment by GeorgeJahad** [comment] 2015-02-23 17:52
Thanks for the help!  If it isn't too much trouble, I'd like to see this one redone:

 https://coveralls.io/builds/1822610

**Comment by nickmerwin** [comment] 2015-02-23 20:18
Hi @GeorgeJahad I think that build is correct since it's PR as opposed to one who's coverage change was calculated off of another PR instead of a base build.

Is that not the case?

**Comment by GeorgeJahad** [comment] 2015-02-24 00:04
So the build isn't correct, and I believe it is because it is using the wrong base commit.  If you step through the example I've listed above, I think you'll see what I mean.

**Comment by GeorgeJahad** [comment] 2015-02-24 00:05
To be clear, the build I requested to be redone, is the one I reported in the bug report above.

**Comment by nickmerwin** [comment] 2015-02-24 00:42
Hi @GeorgeJahad could it be that the number a files covered dropped significantly between those two builds?

I see 153 files in the build in question (https://coveralls.io/builds/1822610) and 363 in the other you referenced (https://coveralls.io/builds/1783661)

I'm sorry if I'm still missing the point, I'll go through your example again if the # of files covered isn't the issue.

**Comment by GeorgeJahad** [comment] 2015-02-24 18:02
Yes, there is still a problem. The number of files has not changed.  (The actual commit just removes a few lines from one file.)  I'm including the entire diff below.

Thanks for any more insight you can provide.

$ git diff b7bae55 68a6c98 
diff --git a/blueflood-core/src/main/java/com/rackspacecloud/blueflood/types/DataType.java b/blueflood-core/src/main/java/com/rackspacecloud/blueflood/types/DataType.java
index bb9621e..e5c4ac1 100644
--- a/blueflood-core/src/main/java/com/rackspacecloud/blueflood/types/DataType.java
+++ b/blueflood-core/src/main/java/com/rackspacecloud/blueflood/types/DataType.java
@@ -37,16 +37,10 @@ public class DataType {
     public static DataType getMetricType(Object metricValue) {
         if (metricValue instanceof String) {
             return STRING;
-        } else if (metricValue instanceof Integer) {
-            return NUMERIC;
-        } else if (metricValue instanceof Long) {
-            return NUMERIC;
-        } else if (metricValue instanceof Double) {
+        } else if (metricValue instanceof Number) {
             return NUMERIC;
         } else if (metricValue instanceof Boolean) {
             return BOOLEAN;
-        } else if (metricValue instanceof BigInteger) {
-            return NUMERIC;
         } else {
             throw new RuntimeException("Unknown metric value type " + metricValue.getClass());
         }

**Comment by GeorgeJahad** [comment] 2015-03-04 19:13
any progress?  I see this got closed with the previous fix.  Should I open a separate issue?

**Comment by nickmerwin** [comment] 2015-03-06 04:59
hi @GeorgeJahad, this is still on my radar but I'm sorry I haven't been able to dig into it further. It's on my short term todo list though.

Thank you again for the detailed clues, it's very helpful.

**Comment by GeorgeJahad** [comment] 2015-03-06 17:07
Cool, thanks!  Would you mind marking this issue as open, (or opening it as a separate issue)?, (just so my team doesn't think I'm wasting my time on an issue that you all consider closed.)
