### ISSUE TITLE
Coverage not showing

### ISSUE THREAD

**Issue by benjamintaiwo** [lemurheavy/coveralls-public#973] opened 2017-05-11 23:06 UTC
when I checked coveralls.io, I found there's no build for [benjamintaiwo/inverted-index-api](url) repo. And I have had several passed builds. Please help

**Comment by bgaifullin** [comment] 2017-05-12 13:28
coverage is not showing for project https://coveralls.io/github/mailru/dbr as well.

**Comment by smbrd** [comment] 2017-05-15 09:25
Second on this

**Comment by aeimer** [comment] 2017-05-16 18:41
We have the same problem on our NodeJS-Project https://coveralls.io/github/h-da/geli
We send the Coveragedata with the npm package `node-coveralls`. The builds appear but there are no coverage-data that coveralls.io receives... what are we doing wrong or is this realy a bug?

Best regards,
Alex

**Comment by pmorie** [comment] 2017-05-18 16:07
I have the same problem: https://github.com/pmorie/go-open-service-broker-client.  Individual builds seem to compute coverage fine, but the badget status isn't updated.

**Comment by smbrd** [comment] 2017-05-18 16:19
This issue has been reported on Coveralls bug reporting forum like week ago and nothing happened since: https://github.com/lemurheavy/coveralls-public/issues/973	 <https://github.com/lemurheavy/coveralls-public/issues/973>
You can contact this guy: https://github.com/nickmerwin <https://github.com/nickmerwin>. He is contributor to Coveralls and responded mail once.
I have been struggling with their support and finally chosen Codecov <https://codecov.io/> instead.


/Mateusz

**Comment by nickmerwin** [comment] 2017-05-18 18:59
Hi all, apologies for the delay. In each repo I've taken a look at the issue is that there hasn't been a build on the `master` branch (or default branch as configured on Github). The Coveralls badge will only show the most current % for the default branch (others can be specified with `?branch=other`) and this does not include Pull Requests.

Closing this issue but I've added to our todo list to provide better UI feedback re: "unknown" badges.

Thanks!

**Closed by nickmerwin** 2017-05-18 18:59 UTC

**Comment by bheuvel** [comment] 2017-05-18 19:02
@nickmerwin Having the same "problem", PRs get reported but no master build, how do I trigger a master build, or point me to the apropriate manual, please? 😃 
https://coveralls.io/github/MissionCriticalCloud/vagrant-cloudstack

**Comment by nickmerwin** [comment] 2017-05-18 19:06
Hi @bheuvel you'll need to make sure all commits are building on your CI (btw I don't see your repo on Travis: https://travis-ci.org/missioncriticalcloud/vagrant-cloudstack), that way each will send coverage data to Coveralls.

**Comment by bheuvel** [comment] 2017-05-18 19:10
Hi @nickmerwin , the travis URL is
https://travis-ci.org/MissionCriticalCloud/vagrant-cloudstack
Thanks for having a look.

**Comment by nickmerwin** [comment] 2017-05-18 19:13
@bheuvel ok from the build history it appears it's been a while:

https://travis-ci.org/MissionCriticalCloud/vagrant-cloudstack/builds

You could trigger a new master build with a trivial commit, or wait for the next PR merge to come through.

**Comment by bheuvel** [comment] 2017-05-18 19:18
@nickmerwin Check, see what you mean. Will check that out. Thanks for the help!

**Comment by aeimer** [comment] 2017-05-19 07:46
Hi @nickmerwin, 
as you can see here, we have builds on our default branch (develop) but there are no coverage data visible. How can we  see our coverage or does coveralls donot get our lcovs?

https://travis-ci.org/h-da/geli/branches
https://coveralls.io/github/h-da/geli

**Comment by nickmerwin** [comment] 2017-05-19 19:10
@aeimer it looks like the coverage data coming through on your API posts aren't complete with source file info: https://coveralls.io/builds/11599237 

From your build logs (https://travis-ci.org/h-da/geli/builds/233975359) and travis config (https://github.com/h-da/geli/blob/develop/.travis.yml) it could be that your `.coverage` directory is being cleaned before your `coveralls.sh` runs.

**Comment by aeimer** [comment] 2017-05-20 21:48
@nickmerwin we have forked our project for testing purposes, here have tested exactly this:

https://travis-ci.org/khase/geli#L512

I can `cat` the lcov.info file... I only could image that the format of the lcov is not the way coveralls want it...?!

**Comment by MBARIMike** [comment] 2018-05-03 18:03
I suspect that my `.coverage` directory is also being cleaned before my coveralls script runs. Is there a place on https://coveralls.io/github/stoqs/stoqs?branch=master that would indicate that this is the problem?

**Comment by tobslob** [comment] 2019-04-23 01:40
@MBARIMike please were you able to solve the problem? if yes how?

**Comment by teaglebuilt** [comment] 2019-09-07 19:25
same problem here
