### ISSUE TITLE
Coverage decreased (-0.002%) when editing non PHP file

### ISSUE THREAD

**Issue by soullivaneuh** [lemurheavy/coveralls-public#790] opened 2016-05-30 09:37 UTC
On Sonata projects, we randomly got some "Coverage decreased" error on PR with no modified PHP files.

The coverage should be the same, shouldn't be?

PR Example: https://github.com/sonata-project/SonataAdminBundle/pull/3894

Coveralls report: https://coveralls.io/jobs/14920326

Regards.

**Comment by Soullivaneuh** [comment] 2016-05-30 12:29
Another PR concerned by this issue: https://github.com/sonata-project/SonataPageBundle/pull/659

**Comment by timabbott** [comment] 2016-06-15 19:17
I'm seeing this as well on the Zulip project: https://github.com/zulip/zulip/pull/1040#issuecomment-226288915

For our case, it looks like Coveralls is comparing the coverage on the most recent build in the PR against the coverage for a previous build in the PR; because the developer rebased their branch on top of a newer master that had slightly lower coverage (due to an uncovered file getting longer), it is incorrectly reporting a decrease in coverage on a change that has no effect on coverage.

**Comment by peter-gribanov** [comment] 2017-01-24 10:08
Another example

PR: https://github.com/anime-db/anime-db/pull/167
Coveralls report: https://coveralls.io/builds/9811668

**Comment by peter-gribanov** [comment] 2017-01-25 08:04
Duplicate of #109

**Comment by peter-gribanov** [comment] 2017-01-25 08:14
@Soullivaneuh maybe it would be better to specify a suffix for files in a directory?

```xml
<?xml version="1.0" encoding="UTF-8"?>
<phpunit backupGlobals="false"
         backupStaticAttributes="false"
         colors="true"
         convertErrorsToExceptions="true"
         convertNoticesToExceptions="true"
         convertWarningsToExceptions="true"
         processIsolation="false"
         stopOnFailure="false"
         syntaxCheck="false"
         bootstrap="Tests/tests/bootstrap.php"
>
    <testsuites>
        <testsuite name="AdminBundle Test Suite">
            <directory>./Tests</directory>
        </testsuite>
    </testsuites>

    <filter>
        <whitelist>
            <directory suffix=".php">./</directory>
            <exclude>
                <directory>./Tests/</directory>
                <directory>./DataFixtures/</directory>
                <directory>./Resources/</directory>
                <directory>./vendor/</directory>
                <directory>./coverage/</directory>
            </exclude>
        </whitelist>
    </filter>

    <php>
        <ini name="precision" value="8"/>
    </php>
</phpunit>
```

**Closed** 2020-04-10 10:59 UTC
Labels: legacy, marked-for-closure
