### ISSUE TITLE
Reported 0.0% aggregate coverage despite individual GitHub Actions jobs showing otherwise

### ISSUE THREAD

**Issue by dgw** [lemurheavy/coveralls-public#1562] opened 2021-06-15 19:46 UTC
Coveralls build: https://coveralls.io/builds/40609637
Related commit: https://github.com/sopel-irc/sopel/commit/d62f19ed39a9b09de8ca651bac1166462b4f156b

![image](https://user-images.githubusercontent.com/164140/122114050-75f48d00-cde8-11eb-99cd-f30dbe8a400d.png)

Fortunately a new commit did not experience this problem, but neither had the exact same tree state before (that commit was just the result of a force-push following a squash; the [comparison](https://github.com/sopel-irc/sopel/compare/72557a3d0213206fe13f9270d977a68ecde3bc53..d62f19ed39a9b09de8ca651bac1166462b4f156b) showed no changes).

**Comment by afinetooth** [comment] 2021-06-16 20:33
@dgw if you notice the TOTAL FILES field on that build (0), that indicates we lost the source files (actually, only the coverage stats thereof) before we could perform the final calculation:

![Screen Shot 2021-06-16 at 1 26 37 PM](https://user-images.githubusercontent.com/918667/122288049-7bb0a800-cea6-11eb-8d0f-2902ec902ebc.png)

I'm hoping it's a one-off and will attempt to reconstruct / recalculate the build from coverage stats we would have stored after each job. 

Results of that are...

Apparent success:
https://coveralls.io/builds/40609637

![Screen Shot 2021-06-16 at 1 30 50 PM](https://user-images.githubusercontent.com/918667/122288995-127d6480-cea7-11eb-9ace-aa84771d99a8.png)

Also, noting the updated status message for aggregate coverage:

![Screen Shot 2021-06-16 at 1 32 22 PM](https://user-images.githubusercontent.com/918667/122289200-49537a80-cea7-11eb-9fc5-a902e8aa1cc0.png)

So, I don't know what caused the final calculation job to fail, but since it didn't occur on the next build we can hope it was indeed a one-off.

Let us know if it happens again and we'll look into possible root causes.

(Closing the issue. Just re-open if necessary.)

**Closed as completed by afinetooth** 2021-06-16 20:33 UTC
Labels: site-performance, coverage-merging, parallel-builds, coverage-discrepancies, commit-status, source-file-issues, github

**Comment by dgw** [comment] 2021-06-17 02:50
Yeah, I was very glad that it turned out to be a one-off glitch. Figured it was worth reporting anyway, in case you could piece together some of the causes and improve the service. Will come back here if we see anything similar happen again!
