### ISSUE TITLE
List view not sorting

### ISSUE THREAD

**Issue by covejstewart** [lemurheavy/coveralls-public#1365] opened 2019-10-11 17:40 UTC
**Description**

The List view does not seem to be sorting on any parameter (Coverage/Lines/Relevent/...), and remains the same after selecting the sort ascending/descending buttons.

Private repos hosted on GitHub.

**Use Case:**  
We Use the List View, with 100 Entries shown, and then sort by Coverage to determine targets for Unit Test Creation.

**Screen Shots**
SORT DESCENDING
![sort_1](https://user-images.githubusercontent.com/139935/66672539-59678100-ec13-11e9-9a52-334c09d1c97a.jpg)
SORT ASCENDING
![sort_2](https://user-images.githubusercontent.com/139935/66672565-697f6080-ec13-11e9-8c60-499be42cc521.jpg)

**Comment by pitschr** [comment] 2019-10-31 07:17
I can confirm. I have this issue too. It seems only middle of table is sorted - rest may remain randomized. At least I do not see a logical sort. It seems all areas are affected.

The "tree" also shows all(?) files in the root level. I don't remember that I had this issue in past. So I guess a PullRequest from last few months broke the logic/layout.

As it is always good to have an example, here one public project:
https://coveralls.io/github/pitschr/knx-link?branch=master

p.s. the issue also happens in Private Mode (latest version of Chrome and Edge)

**Comment by MattRiddell** [comment] 2019-11-05 00:36
Yeah I've had this since I started using it (recently) and this problem has led to me searching elsewhere - all the sort things on my private repos are messed up

**Comment by ped7g** [comment] 2019-11-13 11:25
I have this issue on open source project too. It was working correctly for many builds (and still **IS** working for those old builds in history), but then it stopped working and I think every following build has all the sorting options dysfunctional.

The last working build:
https://coveralls.io/builds/25770374 (build number "723" - count of commits in git repo because that's the only workaround for Cirrus CI I did figure out)

The next build has sorting wrong:
https://coveralls.io/builds/25776682 (build number "724", same branch, no actual code change (the commit was touching only README.md)

It is consistently broken across different browsers/[cleaned]cookies/etc, so it really seems like already the data from Coveralls servers prevent the sorting to work.

**Comment by MattRiddell** [comment] 2019-11-14 19:43
There really hasn't been a lot of activity here since I think September 29th when @nickmerwin closed an issue.  I'm not sure anyone monitors these issues.  The last few that were closed were closed by the reporters.

**Comment by tobyink** [comment] 2019-11-17 00:24
I get the same thing. I imagine it's a 2 line fix.

**Comment by majorgilles** [comment] 2020-01-03 12:23
Same issue here, quite an important feature

**Comment by tobyink** [comment] 2020-01-05 02:44
For what it's worth, I've found it pretty easy to get my travis builds to send coverage reports to both coveralls and codecov. Codecov offers some pretty decent reporting (at least for Perl code) and sorting files works nicely.

**Comment by klahnakoski** [comment] 2020-02-08 15:54
This is still an issue:  This is me trying to sort by `missed`

![image](https://user-images.githubusercontent.com/2334429/74088184-59f91280-4a61-11ea-88b0-49cd5a2c05a6.png)

**Comment by Nic30** [comment] 2020-02-20 22:20
I am also suffering from this issue. https://coveralls.io/github/Nic30/hwtLib?branch=master, Do you know if this issue is in client JS or if it is an server issue?

**Comment by dstndstn** [comment] 2020-03-27 14:48
FWIW, this fails in Firefox, Chrome, and Safari.

**Comment by nickmerwin** [comment] 2020-03-31 04:19
Hi all, this is fixed now and I'm sorry it took so long to resolve. We'll be keeping a closer eye on frontend issues like this moving forward.

Thank you for your patience!

**Closed by nickmerwin** 2020-03-31 04:19 UTC

**Comment by Nic30** [comment] 2020-03-31 08:38
@nickmerwin just a funny story:
I moved several of my project to a codecov.io however I find out that they have their own set of bugs (some files randomly missing in some commits, slow repo sync, ...)
So I ended up using local tools and I did hope that one day one of you will fix the critical issues.
And it seems that after a year my wishes come true.
You have my thanks.

**Comment by klahnakoski** [comment] 2020-03-31 18:29
Thank you!  My procrastination saves me again!
