### ISSUE TITLE
Coveralls badge not working for master branch

### ISSUE THREAD

**Issue by dss-osc** [lemurheavy/coveralls-public#1201] opened 2018-10-12 13:09 UTC
Hi, hope someone can help. Im having trouble with the coveralls badge, coverage seems to be reporting fine, however the badge returned when `branch=master` is passed always says `Unknown`. It returns the correct number if a commit hash is passed as the value, but that would mean id need to update the badge on every commit which doesn't seem correct.

https://coveralls.io/github/disneystreaming/pg2k4j

for a specific commit ...
[![Coverage Status](https://coveralls.io/repos/github/disneystreaming/pg2k4j/badge.svg?branch=bb12d734f195ddb91524145418741f89cf47b75f)](https://coveralls.io/github/disneystreaming/pg2k4j?branch=bb12d734f195ddb91524145418741f89cf47b75f)

for a master ...
[![Coverage Status](https://coveralls.io/repos/github/disneystreaming/pg2k4j/badge.svg?branch=master)](https://coveralls.io/github/disneystreaming/pg2k4j?branch=master)

with no branch ...
[![Coverage Status](https://coveralls.io/repos/github/disneystreaming/pg2k4j/badge.svg)](https://coveralls.io/github/disneystreaming/pg2k4j)

Any help would be greatly appreciated,

**Comment by nomadster** [comment] 2019-02-05 12:41
I've tried all the above but my badge still display "coverage:unknown"

**Comment by cbj4074** [comment] 2019-05-21 13:31
I seem to have the same issue.

I've noticed that that problem seems to manifest only in a repository in which all changes are merged-in via merge/pull requests, i.e., we do not commit directly to `master`. Possibly related is the fact that all commits merged in this fashion show [GitHub `web-flow`](https://github.com/web-flow) as the committer, whereas in other repositories to which we commit directly to `master`, the individual committers are shown there instead.

The repository in question is:

https://github.com/indiehd/web-api

I have several other repositories that use Coveralls, with exactly the same configuration, that do not have this issue.

One will notice that clicking on the badge in the above-linked repository leads to what is essentially a blank page, with no coverage data:

https://coveralls.io/github/indiehd/web-api?branch=master

A screenshot of the URL:

![coveralls-blank-master](https://user-images.githubusercontent.com/1236883/58098752-35de6400-7ba8-11e9-94f0-61dc4104b426.PNG)

If we remove the branch specification from the query string, we can at least see some build/coverage data:

https://coveralls.io/github/indiehd/web-api

And a screenshot of the above URL:

![coveralls-no-branch](https://user-images.githubusercontent.com/1236883/58098871-6cb47a00-7ba8-11e9-91c7-8c97bdeda43a.PNG)

When I log-in to Coveralls.io and examine my repositories, the coverage percentage is blank (empty) for the `master` branch of the repository in question:

![coveralls-repos](https://user-images.githubusercontent.com/1236883/58099005-c026c800-7ba8-11e9-985c-b2421225a0f2.PNG)

It can be seen clearly that the Default Branch is set to `master` for the repository in question.

Any insight into what may be happening here is greatly appreciated.

**Comment by orion3000** [comment] 2019-11-15 22:53
I am having the same issue.  The data is getting reported but the badge is not showing any update and the branch master page is blank.

https://coveralls.io/github/orion3000/albert
https://coveralls.io/github/orion3000/albert?branch=master

**Comment by gerritholl** [comment] 2019-12-05 17:16
Did anyone manage to resolve this problem or find a workaround?  I have the same problem.

**Comment by gerritholl** [comment] 2019-12-05 17:48
I have resolved this problem.  In my case, I forgot to install coveralls inside Travis CI.  After adding an installation of coveralls to `.travis.yml`, it worked correctly.

**Comment by nomadster** [comment] 2019-12-05 18:00
Can you be more specific?

**Comment by cbj4074** [comment] 2019-12-05 18:42
I'm curious what, exactly, you changed in `.travis.yaml`, too, @gerritholl .

In my case, we require Coveralls in

https://github.com/indiehd/web-api/blob/master/composer.json#L27

and install it in

https://github.com/indiehd/web-api/blob/master/.travis.yml#L20

Composer should install `require-dev` dependencies by default (that is, there is no need to specify `composer install --dev`, explicitly), and furthermore, if Coveralls had failed to be installed correctly, I would expect an error when we call

```
travis_retry php vendor/bin/php-coveralls
```

Also, as I [noted in my previous comment](https://github.com/lemurheavy/coveralls-public/issues/1201#issuecomment-494392067), we see coverage data (albeit incomplete) if we remove the `?branch=master` from the query string on the Coveralls site, so it's "working" to some extent, albeit incorrectly.

It seems like your problem may have been different than the one that is the subject of this Issue.

**Comment by gerritholl** [comment] 2019-12-05 21:19
For me, this commit solved my problem: https://github.com/gerritholl/fcitools/commit/57c736bd63292bf0e02a7ec13635cf51a6e46cdc

I don't know why I had previously been successful with getting coveralls for another branch.

**Comment by cbj4074** [comment] 2019-12-05 22:43
@dss-osc I notice that coverage information for your `master` branch is now being reported at https://coveralls.io/github/disneystreaming/pg2k4j?branch=master (and hence, the badge in your OP shows `90%`).

Did you change anything in your configuration to fix the issue?!

**Comment by nomadster** [comment] 2019-12-18 13:04
Am still getting coverage:unknown : https://coveralls.io/github/SpasmodicSoftware/AuthenticatedLadder what did you do to fix this?
Thanks

**Comment by cbj4074** [comment] 2019-12-19 17:09
Okay, I solved this, for my particular use-case, anyway.

Ultimately, the problem is that I had disabled the `Build pushed branches` option for the repository in question within the Travis CI interface.

I can also confirm that even though we always merge PRs on GitHub and never push directly to `master`, the PR-merging process via the GitHub UI does indeed seem to trigger a `push` event and thereby initiate a Travis CI build on `master`, in which case the Coveralls data is updated as desired.

With regard to your particular situation @nomadster , I notice that `master` is absent from the Branches dialog for your Coveralls page:

![image](https://user-images.githubusercontent.com/1236883/71191776-14844a00-2255-11ea-97fc-fcc49cd4d9e9.png)

When you're logged-in, do you see a `Sync Branches` option there?

**Comment by cbj4074** [comment] 2019-12-19 17:22
@nomadster Two other thoughts:

1. I notice that clicking the `Repo on Github` link on your https://coveralls.io/github/SpasmodicSoftware/AuthenticatedLadder page leads to a 404 because the `/tree` is appended to the end of the link. Presumably, you included that trailing `/tree` somewhere in your repository configuration on Coveralls.io. I would try removing that.
2. Are you including `service_name: travis-ci` in your Coveralls configuration? I'm not sure that it's necessary, as the documentation is a bit ambiguous, but it's worth trying for the reason I explain at the bottom of step 5 at https://stackoverflow.com/a/54600493/1772379 .

**Comment by karfau** [comment] 2019-12-27 07:18
I have the exact same problem:
- https://coveralls.io/github/karfau/runex?branch=master is a blank page
- badge shows unknown
- 
![image](https://user-images.githubusercontent.com/135657/71504995-ce923c00-287b-11ea-98cf-f4667ba6cc32.png)
branches care not listed

I'm using node-tap to handle the reporting, there are currently no issues reported on that side.
I also used the browser to connect the repo, so not sure what I could have done wrong.

**Comment by cbj4074** [comment] 2019-12-31 15:49
@karfau I receive a 404 at the link you provided. Did you delete your Coveralls profile?

**Comment by karfau** [comment] 2019-12-31 16:17
Yes, sorry, moved to codecov since I was able to finally have a working setup after many attempts. And already cleared up afterwards.

**Closed** 2021-04-09 09:06 UTC
Labels: marked-for-closure
