### ISSUE TITLE
All coverage on LedgerSMB/LedgerSMB reported as new

### ISSUE THREAD

**Issue by ehuelsmann** [lemurheavy/coveralls-public#732] opened 2016-03-06 22:15 UTC
Hi,

Until a few days ago, coverage was nicely reported relative to the last coverage report and the background of the 'master' branch was showing an increasing graph. Now, the graph is gone and all coverage is reported as "new coverage".

Please advise!

Thanks in advance,

Erik.

**Comment by dasfrosty** [comment] 2016-03-08 18:38
I'm getting similar weirdness.  I keep getting multiple notification emails saying "First build on <branch-name>" for the same branch repeatedly.

And now I just got a notification for build #1 with no branch information at all.  To be specific we were on build #326, but then coveralls just created a new build that is labelled build #1!  (https://coveralls.io/builds/5350685)

**Comment by wjwarren** [comment] 2016-03-16 18:58
Same thing happens to my builds too.

> Coverage remained the same on ​*[repo]*​ ​_[branch]_​ from ​*0.0%*​ to ​*[X]%*​

Similar reported issue: https://github.com/lemurheavy/coveralls-public/issues/738

**Comment by greatislander** [comment] 2016-03-17 16:02
Confirmed for https://github.com/pressbooks/pressbooks too, e.g.: https://coveralls.io/builds/5399979

**Comment by greatislander** [comment] 2016-03-23 14:32
Any news on this issue?

**Comment by ehuelsmann** [comment] 2016-04-02 11:22
@greatislander sent a support request through the Coveralls Feedback functionality on March 6. Then sent a reminder 10 days later. Got a response from @nickmerwin telling me a fix had been deployed and needed to be confirmed. Within 2 days, I responded back that the issue *is not* fixed. Unfortunately, no reaction since then, despite reminders :-(

**Comment by daurnimator** [comment] 2016-04-07 05:45
I'm getting same issue on https://coveralls.io/github/daurnimator/lua-http

**Comment by nickmerwin** [comment] 2016-04-21 00:02
Hi all, we're deployed a fix for this. Could everyone check and confirm?

Close for now.

Thank you!

**Closed by nickmerwin** 2016-04-21 00:02 UTC

**Comment by daurnimator** [comment] 2016-04-21 00:27
It's fixed on the main page for the project, but it's now weird on the per-build page. e.g. https://coveralls.io/builds/5813606 for this build:
  - on the main page it showed "-" i.e. no significant change in coverage
  - in the build matrix it's showing an increase in coverage for every item in the matrix
  - in the per-file table it's showing a decrease in every file.

**Comment by nickmerwin** [comment] 2016-04-21 00:39
Hi @daurnimator it looks like that was cached content, now it's showing all unchanged coverage levels.

**Comment by daurnimator** [comment] 2016-04-21 00:52
ack.

**Comment by wjwarren** [comment] 2016-04-21 08:29
Looks good for me too, thanks! :smile:
