### ISSUE TITLE
Cannot configure settings if I wasn't the one who enabled it

### ISSUE THREAD

**Issue by mikekarhoo** [lemurheavy/coveralls-public#1337] opened 2019-08-16 13:48 UTC
I saw this issue here as well https://github.com/lemurheavy/coveralls-public/issues/1163 and it doesn't seem like there was a resolution for it, but that was last year in July.
Basically we're having an issue whereby the person who enabled the project is the person who can edit the settings and view the token. Anyone else do not have this functionality. And unfortunately we're not in contact with the person anymore, so no one is able to update the settings for that particular repo.
Do you know whether there is a way round it?

**Comment by afinetooth** [comment] 2020-04-07 20:33
@mikekarhoo I am not able to reproduce the issue at this time. Which is to say, I am the member of a Github organization and, on a project that I didn't create or set up on Coveralls, I am able to modify the settings.

I hope this means the same is true for you.

I'm a new team member without the full history on this, so apologies if not. I'm going to close the issue for now, with optimism. Just reply here is you need to re-open and we'll have a closer look into your repo(s).

**Closed by afinetooth** 2020-04-07 20:33 UTC
