### ISSUE TITLE
Coveralls not reporting to Github after subscription expired

### ISSUE THREAD

**Issue by jariendeau** [lemurheavy/coveralls-public#1646] opened 2022-07-01 14:54 UTC
Hi all,

After extensive google searches, I've noticed that others have experienced a similar issue.  I've tried a lot of their solutions but to no avail.  Around end of April we renewed our subscription on Coveralls, however, our Pull Requests on GitHub is stuck in the "coverage/coveralls Expected — Waiting for status to be reported" - we have around 6(ish) private repositories on our project.  I've also sent an email to the support team - can we expedite this?  Or can we try to find a solution from within this chat?  I would really appreciate it. 

Thank you!!

**Comment by afinetooth** [comment] 2022-07-01 19:49
Hi, @jariendeau. If you sent the Coveralls URL for your project to support@coveralls.io then I'll get it. But if not, if you could do that, that'll help us investigate.

I will reply to your email request, but two likely possibilities:

1. If the status updates _eventually_ arrive, then you were affected by [recent issues](https://status.coveralls.io/) that have affected performance for the past several days. You can read that as "slow build times"---a long time to receive status updates or PR Comments after submitting a (successful) build to the Coveralls API.
2. If this started happening after the owner of your repo left your organization (or deleted their coveralls.io account), that could be the reason. We leverage the token of your repo owner to perform certain Github API-based tasks, including sending status updates.

I'll look for your email and get you a more definitive reply there.

**Comment by afinetooth** [comment] 2022-07-02 18:06
Hi, @jariendeau. Replied in detail to your email to support@coveralls.io. 

Root cause seemed to be (2) above, or a similar cause for why your repo owners' tokens were being rejected by the Github API.

Suggested some additional steps you can take to avoid this in the future. We can continue in our email thread.

In the meantime, I'll close this issue. 

Feel free to re-open if necessary.

**Closed as completed by afinetooth** 2022-07-02 18:06 UTC
Labels: no-status-updates
