### ISSUE TITLE
No delta shown but coverage has increased / decreased

### ISSUE THREAD

**Issue by caleb15** [lemurheavy/coveralls-public#1469] opened 2020-08-07 19:33 UTC
In https://coveralls.io/builds/32613724 coverage increased/decreased but no delta is shown. Is this a bug?

![image](https://user-images.githubusercontent.com/46505081/89681656-3268f280-d8aa-11ea-85a9-875a54edc355.png)

**Comment by caleb15** [comment] 2020-08-07 19:36
https://github.com/lemurheavy/coveralls-public/issues/1348#issuecomment-531598646

> Comments are only posted when we have the base build present in order to calculate the coverage delta.

Maybe I just need to wait. I'll set a reminder and come back to this later to see if it's still a issue.

**Comment by afinetooth** [comment] 2020-08-07 22:44
Hi @caleb15, per the issue above, yes, the issue is that sometimes we don't have the base build, or if it is still being calculated, we won't have the basis yet for displaying the changes.

That said, I see the deltas in your example. Notice the red numbers to the right of two of those columns, indicating there was `-1` less line COVERED, and `+1` more line MISSED. Those changes are to be read as, "compared to base branch," or "compared to the last build on your base branch."

When I follow the link at the top left of the build page to your last base branch build, the link that reads:
[PR Base - dev (#0)](https://coveralls.io/builds/32613617)

And I go to your SOURCE FILES table and search for:
[ff/mods/metrics/models.py](https://coveralls.io/builds/32613724/source?filename=ff%2Fmods%2Fmetrics%2Fmodels.py)

I see these stats:
![Screen Shot 2020-08-07 at 3 45 37 PM](https://user-images.githubusercontent.com/918667/89693977-0b6bea00-d8c5-11ea-94c0-cc477145e835.png)

Which concur with the above report:

- There _were_ 49 lines COVERED; there are _now_ 48.
- There _were_ 16 lines MISSED; there are _now_ 17.

---

Closing the issue. Hope that covers it. If not, just reply.

**Closed as completed** 2020-08-07 22:47 UTC
Labels: documentation

**Comment by caleb15** [comment] 2020-08-17 17:36
> That said, I see the deltas in your example

Ah, thanks. I see them now. However, I am surprised they don't show up in the delta column Δ. Is this intentional?

**Comment by afinetooth** [comment] 2020-08-19 00:39
@caleb15 good point. I'm not sure if that Δ column is meant to be a summary of absolute differences for the purpose of sorting, or not---I'll try to find out---but the particular changes denoted by the red numbers wouldn't work there, since the types are different. One is lines, the other is hits/line. Thus the individual "deltas."

Thanks for pointing that out, though. We're in process on a re-design so I'm sure a lot of these details are being reconsidered.
