### ISSUE TITLE
source not available

### ISSUE THREAD

**Issue by sbourdeauducq** [lemurheavy/coveralls-public#596] opened 2015-07-29 17:01 UTC
I get the following message when trying to see the contents of a file:
The owner of this repo needs to re-authorize with Github; their OAuth credentials are no longer valid so the file cannot be pulled from the Github API.

I tried following the instructions of issue #375 but it still does not work.

**Comment by sbourdeauducq** [comment] 2015-07-29 17:01
My repository is m-labs/artiq

**Comment by telemachus** [comment] 2015-07-30 10:12
I'm having this same problem on three repos from Bitbucket, all of which are public:

+ https://coveralls.io/bitbucket/telemachus/tapered
+ https://coveralls.io/bitbucket/telemachus/tableutils
+ https://coveralls.io/bitbucket/telemachus/split

I don't see any message about re-authorization. Any attempt to view source files simply leads to a [500 error](https://coveralls.io/builds/3178049/source?filename=..%2Fsrc%2Ftapered.lua).

Any suggestions?

**Comment by nickmerwin** [comment] 2015-08-07 19:33
hi @telemachus that's fixed now and source from all 3 of your repos is loading.

@sbourdeauducq I'm seeing a Github error when viewing a source file in your repo:
https://coveralls.io/files/1024646802

I'll check back in a bit to see if it's still happening.

**Comment by telemachus** [comment] 2015-08-07 22:12
@nickmerwin Thanks

**Comment by akrherz** [comment] 2015-08-10 20:33
Sorry to be annoying, but I continue to see this error on about 80% of the website requests I make for my source code coverage.  This page https://coveralls.io/files/1024646802 also currently errors as per above.

**Comment by tshead2** [comment] 2015-08-11 15:13
I've been getting "SOURCE NOT AVAILABLE
Sorry, the Github API returned an internal server error, please try refreshing this page in a moment." when viewing source code, ~99% of the time, for the past couple of days.  I've experienced this using two different machines on two different networks.  Every once in a while, the source code view will work, then it's gone again some time later.  Here's an example: https://coveralls.io/builds/3270217, but this issue isn't tied to any one build - I've gone back in history and tried to view source on past builds that definitely worked at the time, and had the same issue.

**Comment by dawagner** [comment] 2015-09-03 09:06
I have the same issue on https://coveralls.io/github/01org/parameter-framework - I tried #375 too (enabled private repos, unlinked/relinked my account) to no avail.

**Comment by mtlynch** [comment] 2015-09-04 19:36
I'm seeing this on a public repo as well for a public repo on Github:

https://coveralls.io/github/m-lab/telescope

I tried unlinking and re-linking my Coveralls account with Github and re-syncing my repos, but the problem persists.

**Comment by nickmerwin** [comment] 2015-09-04 21:19
hi @mtlynch that's because your repo's original owner has since removed their account. I've added a function to claim ownership of an orphaned repo if you have admin rights on it.

You can click the new "Claim" button on the repo page here:

https://coveralls.io/github/m-lab/telescope

Cheers!

**Closed by nickmerwin** 2015-09-04 21:19 UTC

**Comment by nickmerwin** [comment] 2015-09-04 21:22
PS, @dawagner @tshead2 your repo had the same issue, since the original owner has since left.

@akrherz the owner of your repo @jordens needs to reauthorize.

**Comment by tshead2** [comment] 2015-09-04 21:33
@nickmerwin - thanks for the followup, but I'm looking at

https://coveralls.io/github/sandialabs/toyplot

and I can't find a "claim" button.  Where is it located?

**Comment by nickmerwin** [comment] 2015-09-04 22:08
@tshead2 ok you should see it now under the builds list.

**Comment by tshead2** [comment] 2015-09-04 23:19
@nickmerwin - thanks, that did the trick - the source code is visible now.  However I am skeptical about your explanation - the repo I just claimed was created by me, and is owned by a github.com organization I created, where I'm a member of the owners group, and have been continuously without any breaks.  The organization does have other owners, and members that have come and gone from other groups and repos, but not this one.

Just a data point in case it's useful.

Thanks,
Tim

**Comment by nickmerwin** [comment] 2015-09-04 23:21
@tshead2 hm did you recently change you github username?

**Comment by tshead2** [comment] 2015-09-04 23:28
@nickmerwin - nope, I've never changed a username.  I do switch back-and-forth between personal and work github accounts, perhaps that might cause confusion with OAuth?

**Comment by mtlynch** [comment] 2015-09-05 17:54
@nickmerwin thanks for the response!

I'm still not seeing a "Claim" button under my builds. Like @tshead2 my experience doesn't match your description. I'm an owner of my repo and I was the one who added it to Coveralls.

In trying to work around other issues, I tried unlinking my Github account, then re-linking and also tried disabling Telescope in Coveralls, then re-enabling, but there should not have been any other owner. I also did not change my Github username.

**Comment by akrherz** [comment] 2015-09-05 19:58
@nickmerwin thanks for the response.  I have no idea who @jordens is nor does he own any of my repos... For example, https://coveralls.io/builds/3369450/source?filename=pyiem%2Fobservation.py and https://github.com/akrherz/pyIEM/blob/master/pyiem/observation.py

**Comment by dawagner** [comment] 2015-09-07 08:37
@nickmerwin I do not see the "claim" button either. The original creator of the repository is still a member of the owning organization (but the membership of that person is private).

Also, I have the same issue on my fork of the repository: https://coveralls.io/github/dawagner/parameter-framework

Thanks for looking at this issue :)

**Comment by nickmerwin** [comment] 2015-09-09 05:09
Alright all, I've changed the way source is pulled from Github API -- it will default to use the OAuth token of the user currently on the site, as opposed to always the repo owner. That way you should be able to see any source file you have access to, regardless of whether or not the owner's tokens have expired.

@tshead2 ok that could have been it, thank you for the clues.

@mtlynch you should be able to access your source files now, but could you link me to your repo also?

@akrherz according to our logs the https://coveralls.io/github/m-labs/artiq repo was added by @jordens on 02/05/15.

@dawagner do you use multiple Github accounts?

**Comment by dawagner** [comment] 2015-09-09 09:15
@nickmerwin thanks, it works now :)

I only use one account.

**Comment by akrherz** [comment] 2015-09-09 12:19
@nickmerwin thanks, it works for me too now.  Unsure why you associated my comments with the m-labs repo, I have nothing to do with that repo.

**Comment by mtlynch** [comment] 2015-09-09 14:06
@nickmerwin - Thanks! That fixed it. I can now see line level coverage in https://coveralls.io/github/m-lab/telescope

@akrherz I think maybe @nickmerwin got streams crossed along the way. m-lab (no s) is my org, no relation to m-labs

**Comment by mtlynch** [comment] 2015-09-09 14:13
>@nickmerwin - Thanks! That fixed it. I can now see line level coverage in https://coveralls.io/github/m-lab/telescope

Oh, hmm. One remaining issue I noticed. You can't see line level coverage if you're not signed in. Is this by design?

e.g. If for this URL:

https://coveralls.io/builds/3516151/source?filename=telescope%2Fquery.py

If I'm signed in as **mtlynch** I can see the source and line level coverage.
If I'm not signed in to Coveralls, I see:
```
SOURCE NOT AVAILABLE
The owner of this repo needs to re-authorize with github; their OAuth credentials are no longer valid so the file cannot be pulled from the github API.```
