### ISSUE TITLE
Bad links to branches from external repositories

### ISSUE THREAD

**Issue by fingolfin** [lemurheavy/coveralls-public#1245] opened 2019-01-11 10:31 UTC
On <https://coveralls.io/github/gap-system/gap> (or any other Coveralls repository page), under "Recent Builds", there is a column "branch" with the name fo the branch from which the build was made; that name also is a hyperlink to the GitHub page for that branch.

Except that link is broken whenever the branch is not in the main repository (here: `gap-system/gap`), but rather comes from a fork (as is usually the case for pull requests). Example: for build 8885 it lists branch `ff-ext` and links to https://github.com/gap-system/gap/tree/ff-ext which gives a 404 error; the correct URL would be https://github.com/stevelinton/gap/tree/ff-ext

This is also reproducible on your own repository: on https://coveralls.io/github/lemurheavy/coveralls-ruby build 350 for branch  `move_work_over_from_original_repo` links to FOO but the correct linke would be https://github.com/Coveralls-Community/coveralls-ruby/tree/move_work_over_from_original_repo (which also gives a 404, as that branch was already deleted, but that doesn't affect the point I am trying to make here)

**Comment by Minoru** [comment] 2021-07-15 15:44
As I explained in https://github.com/lemurheavy/coveralls-public/issues/1384#issuecomment-874000332, this is still an issue.

**Comment by afinetooth** [comment] 2021-07-16 18:01
@fingolfin @Minoru thank you.

As you may be aware, this is a duplicate of this issue:
https://github.com/lemurheavy/coveralls-public/issues/1384

We'll try to update both issues when addressed, but please check there as well if seeking an update just in case.

**Closed** 2022-10-30 17:04 UTC
Labels: potential-bug, marked-for-closure, forked-repos, 4xx-error
