### ISSUE TITLE
Coverage showing as 0%

### ISSUE THREAD

**Issue by mikefrancis** [lemurheavy/coveralls-public#588] opened 2015-07-27 08:31 UTC
Just testing out Coveralls and tried it on a [small repo](https://coveralls.io/github/mikefrancis/tokenizr)

If I go into the latest build [https://coveralls.io/builds/3143840] I see one file has 100% coverage, yet the repo has 0%.

I'm sure this is probably just an issue with how I've got PHPUnit set up, however I'd be willing to share any fixes with the larger PHP community.

Could anyone help?

**Comment by telemachus** [comment] 2015-07-27 13:14
This is a duplicate of #589, probably accidental.

**Closed** 2015-07-27 13:15 UTC

**Comment by mikefrancis** [comment] 2015-07-27 16:10
Ooops, sorry. I have no idea how I created 2 issues but thanks for pointing this out.
