### ISSUE TITLE
coverage unknown

### ISSUE THREAD

**Issue by leonardloo** [lemurheavy/coveralls-public#890] opened 2016-12-02 02:54 UTC
Hi my coverage is unknown in the ATeamHasNoName/CS207Project master branch. Why is that the case? My Travis is passing.

**Comment by joohoi** [comment] 2016-12-04 13:08
I'm seeing this as well

**Comment by leonardloo** [comment] 2016-12-04 17:33
How do we fix that?

**Comment by slivingston** [comment] 2017-01-01 17:53
This issue seems to be a duplicate of #351

**Comment by slivingston** [comment] 2017-01-01 17:56
not necessarily duplicate behavior as reported in #351, but the cause might be the same.

**Closed** 2020-04-10 08:24 UTC
Labels: legacy, marked-for-closure
