### ISSUE TITLE
After switch to parallel builds, Coveralls shows unchanged coverage on folders, but massive decrease in total coverage

### ISSUE THREAD

**Issue by tdonohue** [lemurheavy/coveralls-public#1487] opened 2020-09-21 16:29 UTC
For our open source project, I've recently tried to move to a parallel build strategy in Travis CI + Coveralls.  Previously, we ran both Unit & Integration tests in one build (and one report to Coveralls).  Now, we are attempting to run each separately, and send two reports to Coveralls (for Coveralls to merge). See this PR for the changes in our codebase: https://github.com/DSpace/DSpace/pull/2975

Unfortunately, while Coveralls "sees" that there are now two parallel jobs, it seems to base the "total coverage" on the results of the first job only.  See this Coveralls build: https://coveralls.io/builds/33572622

Looking closely at that build report, the folders at the bottom show **no increase or decrease** in coverage based on the prior build.  However, the two jobs each show a decrease (which makes some sense, as it was one job previously and now split into two).  The total coverage seems to only account for the *first* job, ignoring the results of the second job altogether.

It's always possible there's a configuration error on my end, although I'm following the recommendations at https://docs.coveralls.io/parallel-build-webhook  Suggestions welcome.

**Comment by tdonohue** [comment] 2020-09-21 16:31
May or may not be related to #1484, which is also about correct coverage on Folders but an incorrect total coverage

**Comment by afinetooth** [comment] 2020-09-21 20:50
Hi @tdonohue,

Your implementation of parallel builds looks correct.

First thought upon seeing your result for Build 8533 was that it may have been a one-off caused by an issue we discovered a couple of weeks ago involving a race condition between jobs performing calculations on single vs aggregate jobs. (Something that was occurring on larger projects with many source files.) 

I ran a procedure on your Build 8533 to fix the result and it now looks correct:
https://coveralls.io/builds/33572622

![Screen Shot 2020-09-21 at 1 41 31 PM](https://user-images.githubusercontent.com/918667/93819112-2b0a6800-fc10-11ea-8985-9776197cea24.png)

The question is why this happened on Sep 18, when we resolved the underlying issue ~2-weeks ago. I also see the issue persists for your subsequent builds since Sep 18, so not a one-off for you.

Please let us have a closer look using those builds as further examples. Will get back asap.

**Comment by afinetooth** [comment] 2020-09-21 22:07
@tdonohue as I look more closely into this, I see a reason why this might have occurred and it appears to be because our API did not recognize your build as parallel. Which is odd because, as I mentioned, your `.travis.yml` config looks correct. (I see you've set the global env var `COVERALLS_PARALLEL=true`.)

Can you please do me a favor and call coveralls in [verbose mode](https://docs.coveralls.io/troubleshooting#put-it-in-verbose--v) so we can see the exact JSON you're posting to the API? Another commit to the same PR will work.

I'm not too familiar with the java language integrations (assume you're using something like [coveralls-maven-plugin](https://github.com/trautonen/coveralls-maven-plugin), etc.), but you should probably just be able to add `-v` to this line in your `.travis.yml`:

> - mvn verify -B -P coveralls -v

Calling us in verbose mode will add debug output to the stdout from your travis job that we can then examine.

Here's an example of an open-source project with parallel builds, demo'd for various CIs, including travis:
https://github.com/coverallsapp/coveralls-node-demo

Here's one of its coveralls builds for travis:
https://coveralls.io/builds/33100203

And here's the travis job log for job 1 of 2 for that build:
https://travis-ci.org/github/coverallsapp/coveralls-node-demo/jobs/722548532

Note the debug output we're looking for---`parallel: true`---appearing here around lines 293 & 311:

![Screen Shot 2020-09-21 at 3 12 22 PM](https://user-images.githubusercontent.com/918667/93826795-dc16ff80-fc1c-11ea-9e5c-0358e1b3edcd.png)

Thanks.

**Comment by tdonohue** [comment] 2020-09-22 14:29
@afinetooth : this morning, I've added the Maven `--debug` flag to get verbose output as you described.  This triggered a new build & report at Coveralls (which is ongoing at this moment, likely to fully complete in the next 20mins...just waiting on the second job).  Here's the Coveralls build though: https://coveralls.io/builds/33636567

You correctly guessed that I *am* using [coveralls-maven-plugin](https://github.com/trautonen/coveralls-maven-plugin/) to help send my info to Coveralls.

As for the verbose output, I'm **not** seeing `parallel:true` in the `coveralls.json` which `coveralls-maven-plugin` sends your way.  Here's what I'm seeing in my verbose output (I've removed my email just for privacy):
```
[INFO] Starting Coveralls job for travis-ci (389275470)
[INFO] Git commit 9c2e020 in main
[DEBUG] Complete Job description:
{
  "branch" : "main",
  "dryRun" : false,
  "git" : {
    "branch" : "9c2e0204534c88516c3ac593c7fc0c197c12e2e1",
    "head" : {
      "author_email" : "[my-email-address]",
      "author_name" : "Tim Donohue",
      "committer_email" : "noreply@github.com",
      "committer_name" : "GitHub",
      "id" : "9c2e0204534c88516c3ac593c7fc0c197c12e2e1",
      "message" : "Merge adc037b9f15e7b28f3cef483d00000e5fb5b8ac5 into 2e5efda2faa68bb85ac9b581c1ca0419c825888d\n"
    },
    "remotes" : [ {
      "name" : "origin",
      "url" : "https://github.com/DSpace/DSpace.git"
    } ]
  },
  "pullRequest" : "2975",
  "repoToken" : null,
  "serviceBuildNumber" : "8542",
  "serviceBuildUrl" : null,
  "serviceEnvironment" : {
    "travis_job_id" : "389275470",
    "travis_pull_request" : "2975"
  },
  "serviceJobId" : "389275470",
  "serviceName" : "travis-ci",
  "timestamp" : null
}
[INFO] Writing Coveralls data to /home/travis/build/DSpace/DSpace/dspace/target/coveralls.json...
```

Digging around on my end a bit further, it **looks like this is a bug in coveralls-maven-plugin**.  See this ticket: https://github.com/trautonen/coveralls-maven-plugin/issues/128

So, I'm guessing there may not be anything you or I can do to solve this?  Maybe I need to link this ticket over to `coveralls-maven-plugin` in the hopes of getting their attention on this?

**Comment by afinetooth** [comment] 2020-09-22 16:21
Hi @tdonohue, yes, it looks like there’s a PR waiting on the project where one of my colleagues added support for the parallel flag:
https://github.com/trautonen/coveralls-maven-plugin/pull/130

Immediate recommendation is to fork and use that branch until it’s merged.

**Comment by afinetooth** [comment] 2020-09-25 18:56
Closing the issue for now. Let us know if you need anything else.

**Closed as completed by afinetooth** 2020-09-25 18:56 UTC
Labels: parallel-builds, coverage-discrepancies
