### ISSUE TITLE
Can't open any source file

### ISSUE THREAD

**Issue by zv0n** [lemurheavy/coveralls-public#1426] opened 2020-04-16 07:08 UTC
I've added a repo to coveralls yesterday - https://coveralls.io/gitlab/zvon/tv_rename_cpp

The code coverage percentage seems to work, but when I click on any source file I get 500 error. I'm using cpp-coveralls to upload my data. Is there anything I can do to fix this?

**Comment by msghiorso** [comment] 2020-04-20 16:59
Same for me. Repo - [https://gitlab.com/ENKI-portal/ThermoEngine](https://gitlab.com/ENKI-portal/ThermoEngine)

**Comment by kolychev** [comment] 2020-04-29 05:58
Same here https://coveralls.io/gitlab/webvideo/coveralls-demo. Java project this time, gitlab repo: https://gitlab.com/webvideo/coveralls-demo. Seems to be related to gitlab-hosted repos ?

**Comment by AbhigyanKumar** [comment] 2020-09-30 19:34
This is frustrating me. The same error is shown on my [Go project](https://coveralls.io/builds/33837967/source?filename=log.go).

**Comment by afinetooth** [comment] 2020-10-02 23:44
@zv0n @msghiorso @kolychev @AbhigyanKumar I've reproduced the issue and yes it does appear to be an issue with Gitlab repos. Will reply back as soon as I have an update. Please stand by.

**Comment by afinetooth** [comment] 2020-10-03 00:04
@AbhigyanKumar I'm unable to find a build associated with that project. It appears to have been deleted. Can you verify the build ID, or share the coveralls project URL?

In the meantime, I found what appears to be your only project, so I checked the source files, and this is one by the same name as that in the URL above:
https://coveralls.io/builds/33888804/source?filename=io.go

Seems to be no problem with that one.

However, as noted above, that project is through Github and not Gitlab. Can you share the Gitlab project URL?

**Comment by afinetooth** [comment] 2020-10-03 00:12
@kolychev there seems to be a potential configuration issue with the project you mentioned:
https://coveralls.io/gitlab/webvideo/coveralls-demo

Note the filename on the top file:

![image](https://user-images.githubusercontent.com/918667/94978342-d13c5480-04d1-11eb-9057-673cd8fa05bd.png)

The files there also don't match the file structure of your project at Gitlab:

![Screen Shot 2020-10-02 at 5 10 32 PM](https://user-images.githubusercontent.com/918667/94978430-2f693780-04d2-11eb-82af-9f015cb26cba.png)

The two should be 1-to-1. 

To see what you're actually sending to the coveralls API, try running in [verbose mode](https://docs.coveralls.io/troubleshooting#put-it-in-verbose--v).

That will add debug output showing exactly what's in the JSON you're POSTing.

BTW, we are adding a rescue to keep this from happening again. Going forward, you should receive an error response from the API if your JSON appears to be malformed.

**Comment by afinetooth** [comment] 2020-10-03 00:22
@msghiorso I'm seeing something similar with your project. 

The file structures do not match between the coveralls build:
https://coveralls.io/gitlab/ENKI-portal/ThermoEngine

![Screen Shot 2020-10-02 at 5 19 34 PM](https://user-images.githubusercontent.com/918667/94978694-73107100-04d3-11eb-99a4-7505db65cd9a.png)

and your repo at Gitlab:
https://gitlab.com/ENKI-portal/ThermoEngine

![Screen Shot 2020-10-02 at 5 20 52 PM](https://user-images.githubusercontent.com/918667/94978742-a3580f80-04d3-11eb-9e9d-6eddb2508134.png)

Can you help me understand why, such as if you're only sending a subset of that repo's files, etc. Thanks.

As it stands though, I'm not seeing 500 errors for those source files. Example:
https://coveralls.io/builds/33590926/source?filename=/opt/conda/lib/python3.8/site-packages/thermoengine/__init__.py

Instead I'm getting our SOURCE NOT AVAILABLE page, which we display when we can't find the file at your repo by the passed in filename:

![Screen Shot 2020-10-02 at 5 24 31 PM](https://user-images.githubusercontent.com/918667/94978840-24170b80-04d4-11eb-9e88-ec0493c0a838.png)

That page allows you to adjust filename prefixes or suffixes that may help you correct for an offset between your repo and CI.

**Comment by AbhigyanKumar** [comment] 2020-10-03 04:10
I have fixed everything...

**Comment by afinetooth** [comment] 2020-11-01 02:24
@AbhigyanKumar thanks. 

@kolychev @msghiorso ok to close this one?

**Comment by AbhigyanKumar** [comment] 2020-11-01 09:43
Yes of course! You may close this issue.

**Comment by afinetooth** [comment] 2020-11-03 03:04
@AbhigyanKumar thank you!

**Comment by kolychev** [comment] 2020-11-03 03:28
@afinetooth thank you for investigation! I am ok to close this issue.

**Comment by afinetooth** [comment] 2020-11-03 20:30
Thank you @kolychev

**Closed as completed by afinetooth** 2020-11-03 20:30 UTC
Labels: potential-bug, source-not-available, c / c++, 5xx-error
